-- Smart Banking Management System: Oracle 19c+ core schema
-- Run only in a dedicated project schema. This script never drops existing data.

CREATE TABLE branches (
  branch_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_branches PRIMARY KEY,
  branch_code VARCHAR2(12) NOT NULL CONSTRAINT uk_branches_code UNIQUE,
  branch_name VARCHAR2(100) NOT NULL,
  city VARCHAR2(50) NOT NULL,
  address VARCHAR2(200) NOT NULL,
  phone VARCHAR2(20), swift_code VARCHAR2(20),
  status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL CONSTRAINT ck_branches_status CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE account_types (
  account_type_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_account_types PRIMARY KEY,
  type_name VARCHAR2(40) NOT NULL CONSTRAINT uk_account_types_name UNIQUE,
  description VARCHAR2(200),
  min_balance NUMBER(15,2) DEFAULT 0 NOT NULL CONSTRAINT ck_account_type_min CHECK (min_balance >= 0),
  annual_interest_rate NUMBER(5,2) DEFAULT 0 NOT NULL CONSTRAINT ck_account_type_rate CHECK (annual_interest_rate BETWEEN 0 AND 100),
  status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL CONSTRAINT ck_account_types_status CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE customers (
  customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_customers PRIMARY KEY,
  first_name VARCHAR2(50) NOT NULL, last_name VARCHAR2(50) NOT NULL,
  date_of_birth DATE NOT NULL, gender CHAR(1) CONSTRAINT ck_customer_gender CHECK (gender IN ('M','F','O')),
  phone VARCHAR2(20) NOT NULL CONSTRAINT uk_customer_phone UNIQUE,
  email VARCHAR2(100) CONSTRAINT uk_customer_email UNIQUE,
  national_id VARCHAR2(30) NOT NULL CONSTRAINT uk_customer_nid UNIQUE,
  address VARCHAR2(200) NOT NULL, occupation VARCHAR2(100),
  annual_income NUMBER(15,2) DEFAULT 0 CONSTRAINT ck_customer_income CHECK (annual_income >= 0),
  marital_status VARCHAR2(20),
  status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL CONSTRAINT ck_customers_status CHECK (status IN ('ACTIVE','BLOCKED')),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE employees (
  employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_employees PRIMARY KEY,
  branch_id NUMBER NOT NULL CONSTRAINT fk_employee_branch REFERENCES branches(branch_id),
  employee_code VARCHAR2(20) NOT NULL CONSTRAINT uk_employee_code UNIQUE,
  first_name VARCHAR2(50) NOT NULL, last_name VARCHAR2(50) NOT NULL,
  national_id VARCHAR2(30) NOT NULL CONSTRAINT uk_employee_nid UNIQUE,
  job_title VARCHAR2(100) NOT NULL, email VARCHAR2(100) NOT NULL CONSTRAINT uk_employee_email UNIQUE,
  phone VARCHAR2(20), salary NUMBER(15,2) NOT NULL CONSTRAINT ck_employee_salary CHECK (salary > 0),
  hire_date DATE DEFAULT SYSDATE NOT NULL,
  status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL CONSTRAINT ck_employees_status CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE users (
  user_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_users PRIMARY KEY,
  customer_id NUMBER CONSTRAINT fk_user_customer REFERENCES customers(customer_id),
  employee_id NUMBER CONSTRAINT fk_user_employee REFERENCES employees(employee_id),
  username VARCHAR2(50) NOT NULL CONSTRAINT uk_users_username UNIQUE,
  staff_code VARCHAR2(20) CONSTRAINT uk_users_staff_code UNIQUE,
  password_hash VARCHAR2(255) NOT NULL,
  role VARCHAR2(20) NOT NULL CONSTRAINT ck_users_role CHECK (role IN ('ADMIN','MANAGER','EMPLOYEE','CUSTOMER')),
  is_active CHAR(1) DEFAULT 'Y' NOT NULL CONSTRAINT ck_users_active CHECK (is_active IN ('Y','N')),
  must_change_password CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT ck_users_must_change CHECK (must_change_password IN ('Y','N')),
  account_locked CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT ck_users_locked CHECK (account_locked IN ('Y','N')),
  locked_at TIMESTAMP, password_changed_at TIMESTAMP, updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  last_login TIMESTAMP, failed_login_count NUMBER DEFAULT 0 NOT NULL CONSTRAINT ck_login_count CHECK (failed_login_count >= 0),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_user_principal CHECK (
    (role = 'CUSTOMER' AND customer_id IS NOT NULL AND employee_id IS NULL AND staff_code IS NULL) OR
    (role IN ('MANAGER','EMPLOYEE') AND employee_id IS NOT NULL AND customer_id IS NULL AND staff_code IS NOT NULL) OR
    (role = 'ADMIN' AND customer_id IS NULL AND employee_id IS NULL AND staff_code IS NOT NULL)
  ),
  CONSTRAINT uk_user_customer UNIQUE(customer_id), CONSTRAINT uk_user_employee UNIQUE(employee_id)
);

CREATE TABLE accounts (
  account_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_accounts PRIMARY KEY,
  account_number VARCHAR2(24) NOT NULL CONSTRAINT uk_account_number UNIQUE,
  customer_id NUMBER NOT NULL CONSTRAINT fk_account_customer REFERENCES customers(customer_id),
  branch_id NUMBER NOT NULL CONSTRAINT fk_account_branch REFERENCES branches(branch_id),
  account_type_id NUMBER NOT NULL CONSTRAINT fk_account_type REFERENCES account_types(account_type_id),
  balance NUMBER(15,2) DEFAULT 0 NOT NULL CONSTRAINT ck_account_balance CHECK (balance >= 0),
  currency VARCHAR2(3) DEFAULT 'BDT' NOT NULL CONSTRAINT ck_account_currency CHECK (currency IN ('BDT','USD','EUR')),
  status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL CONSTRAINT ck_account_status CHECK (status IN ('ACTIVE','FROZEN','CLOSED')),
  open_date DATE DEFAULT SYSDATE NOT NULL, close_date DATE, last_transaction_date TIMESTAMP,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_account_close CHECK ((status = 'CLOSED' AND close_date IS NOT NULL) OR status <> 'CLOSED')
);

  CREATE TABLE loan_types (
    loan_type_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_loan_types PRIMARY KEY,
    type_name VARCHAR2(60) NOT NULL CONSTRAINT uk_loan_type_name UNIQUE,
    short_description VARCHAR2(200), detailed_description VARCHAR2(1000),
    minimum_annual_income NUMBER(15,2), processing_fee_percentage NUMBER(5,2) DEFAULT 0 NOT NULL,
    eligibility_summary VARCHAR2(500), required_document_summary VARCHAR2(500),
    interest_method VARCHAR2(20) DEFAULT 'REDUCING_BALANCE' NOT NULL,
    min_amount NUMBER(15,2) NOT NULL, max_amount NUMBER(15,2) NOT NULL,
  annual_interest_rate NUMBER(5,2) NOT NULL, min_term_months NUMBER NOT NULL, max_term_months NUMBER NOT NULL,
  status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL CONSTRAINT ck_loan_type_status CHECK (status IN ('ACTIVE','INACTIVE')),
  CONSTRAINT ck_loan_type_amounts CHECK (min_amount > 0 AND max_amount >= min_amount),
    CONSTRAINT ck_loan_type_rate CHECK (annual_interest_rate BETWEEN 0 AND 100),
    CONSTRAINT ck_loan_type_income CHECK (minimum_annual_income IS NULL OR minimum_annual_income >= 0),
    CONSTRAINT ck_loan_type_fee CHECK (processing_fee_percentage BETWEEN 0 AND 100),
    CONSTRAINT ck_loan_type_method CHECK (interest_method IN ('REDUCING_BALANCE','FLAT_RATE')),
  CONSTRAINT ck_loan_type_terms CHECK (min_term_months > 0 AND max_term_months >= min_term_months)
);

CREATE TABLE loans (
  loan_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_loans PRIMARY KEY,
  loan_number VARCHAR2(30) NOT NULL CONSTRAINT uk_loan_number UNIQUE,
  customer_id NUMBER NOT NULL CONSTRAINT fk_loan_customer REFERENCES customers(customer_id),
  loan_type_id NUMBER NOT NULL CONSTRAINT fk_loan_type REFERENCES loan_types(loan_type_id),
  disbursement_account_id NUMBER NOT NULL CONSTRAINT fk_loan_account REFERENCES accounts(account_id),
  requested_amount NUMBER(15,2) NOT NULL CONSTRAINT ck_loan_requested CHECK (requested_amount > 0),
  approved_amount NUMBER(15,2), interest_rate NUMBER(5,2) NOT NULL CONSTRAINT ck_loan_rate CHECK (interest_rate BETWEEN 0 AND 100),
  term_months NUMBER NOT NULL CONSTRAINT ck_loan_term CHECK (term_months > 0),
  monthly_installment NUMBER(15,2), total_repayable NUMBER(15,2), outstanding_balance NUMBER(15,2),
  status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL CONSTRAINT ck_loan_status CHECK (status IN ('PENDING','APPROVED','REJECTED','ACTIVE','COMPLETED')),
  reviewed_by NUMBER CONSTRAINT fk_loan_reviewer REFERENCES employees(employee_id), reviewed_at TIMESTAMP, rejection_reason VARCHAR2(500),
  application_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, start_date DATE, end_date DATE,
  CONSTRAINT ck_loan_approved_amount CHECK (approved_amount IS NULL OR (approved_amount > 0 AND approved_amount <= requested_amount)),
  CONSTRAINT ck_loan_rejection CHECK (status <> 'REJECTED' OR rejection_reason IS NOT NULL)
);

CREATE TABLE transactions (
  transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_transactions PRIMARY KEY,
  account_id NUMBER NOT NULL CONSTRAINT fk_transaction_account REFERENCES accounts(account_id),
  related_account_id NUMBER CONSTRAINT fk_transaction_related REFERENCES accounts(account_id),
  transaction_type VARCHAR2(30) NOT NULL CONSTRAINT ck_transaction_type CHECK (transaction_type IN ('DEPOSIT','WITHDRAWAL','TRANSFER_DEBIT','TRANSFER_CREDIT','LOAN_DISBURSEMENT','LOAN_PAYMENT','REVERSAL_DEBIT','REVERSAL_CREDIT')),
  amount NUMBER(15,2) NOT NULL CONSTRAINT ck_transaction_amount CHECK (amount > 0),
  previous_balance NUMBER(15,2) NOT NULL, new_balance NUMBER(15,2) NOT NULL,
  status VARCHAR2(12) DEFAULT 'SUCCESS' NOT NULL CONSTRAINT ck_transaction_status CHECK (status IN ('SUCCESS','REVERSED')),
  reference_no VARCHAR2(50) NOT NULL CONSTRAINT uk_transaction_reference UNIQUE,
  description VARCHAR2(200), processed_by NUMBER CONSTRAINT fk_transaction_user REFERENCES users(user_id),
  transaction_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_transaction_balances CHECK (previous_balance >= 0 AND new_balance >= 0)
);

CREATE TABLE fund_transfers (
  transfer_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_transfers PRIMARY KEY,
  transfer_reference VARCHAR2(50) NOT NULL CONSTRAINT uk_transfer_reference UNIQUE,
  from_account_id NUMBER NOT NULL CONSTRAINT fk_transfer_from REFERENCES accounts(account_id),
  to_account_id NUMBER NOT NULL CONSTRAINT fk_transfer_to REFERENCES accounts(account_id),
  amount NUMBER(15,2) NOT NULL CONSTRAINT ck_transfer_amount CHECK (amount > 0),
  debit_transaction_id NUMBER NOT NULL CONSTRAINT fk_transfer_debit REFERENCES transactions(transaction_id),
  credit_transaction_id NUMBER NOT NULL CONSTRAINT fk_transfer_credit REFERENCES transactions(transaction_id),
  initiated_by NUMBER CONSTRAINT fk_transfer_user REFERENCES users(user_id),
  transfer_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_transfer_accounts CHECK (from_account_id <> to_account_id)
);

CREATE TABLE loan_payments (
  payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_loan_payments PRIMARY KEY,
  loan_id NUMBER NOT NULL CONSTRAINT fk_payment_loan REFERENCES loans(loan_id),
  account_id NUMBER NOT NULL CONSTRAINT fk_payment_account REFERENCES accounts(account_id),
  transaction_id NUMBER NOT NULL CONSTRAINT fk_payment_transaction REFERENCES transactions(transaction_id),
  amount NUMBER(15,2) NOT NULL CONSTRAINT ck_payment_amount CHECK (amount > 0),
  previous_outstanding NUMBER(15,2) NOT NULL, new_outstanding NUMBER(15,2) NOT NULL,
  received_by NUMBER CONSTRAINT fk_payment_user REFERENCES users(user_id),
  payment_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_payment_outstanding CHECK (previous_outstanding > 0 AND new_outstanding >= 0)
);

CREATE TABLE audit_log (
  audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_audit_log PRIMARY KEY,
  table_name VARCHAR2(50) NOT NULL, record_id NUMBER, action_name VARCHAR2(30) NOT NULL,
  action_by VARCHAR2(100) DEFAULT SYS_CONTEXT('USERENV','SESSION_USER') NOT NULL,
  old_summary CLOB, new_summary CLOB, action_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE transaction_reversals (
  reversal_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_transaction_reversals PRIMARY KEY,
  original_transaction_id NUMBER NOT NULL CONSTRAINT fk_reversal_original REFERENCES transactions(transaction_id),
  reversal_transaction_id NUMBER NOT NULL CONSTRAINT fk_reversal_transaction REFERENCES transactions(transaction_id),
  reason VARCHAR2(500) NOT NULL,
  reversed_by NUMBER CONSTRAINT fk_reversal_user REFERENCES users(user_id),
  reversed_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  status VARCHAR2(12) DEFAULT 'COMPLETED' NOT NULL CONSTRAINT ck_reversal_status CHECK (status IN ('COMPLETED','FAILED')),
  CONSTRAINT uk_reversal_original UNIQUE(original_transaction_id),
  CONSTRAINT uk_reversal_transaction UNIQUE(reversal_transaction_id)
);

CREATE TABLE user_preferences (
  user_id NUMBER CONSTRAINT pk_user_preferences PRIMARY KEY REFERENCES users(user_id),
  theme VARCHAR2(10) DEFAULT 'SYSTEM' NOT NULL CONSTRAINT ck_preferences_theme CHECK (theme IN ('LIGHT','DARK','SYSTEM')),
  rows_per_page NUMBER DEFAULT 20 NOT NULL CONSTRAINT ck_preferences_rows CHECK (rows_per_page BETWEEN 5 AND 100),
  currency_display VARCHAR2(3) DEFAULT 'BDT' NOT NULL CONSTRAINT ck_preferences_currency CHECK (currency_display='BDT'),
  notifications_enabled CHAR(1) DEFAULT 'Y' NOT NULL CONSTRAINT ck_preferences_notifications CHECK (notifications_enabled IN ('Y','N')),
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE beneficiaries (
  beneficiary_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_beneficiaries PRIMARY KEY,
  customer_id NUMBER NOT NULL CONSTRAINT fk_beneficiary_customer REFERENCES customers(customer_id),
  source_account_id NUMBER NOT NULL CONSTRAINT fk_beneficiary_source REFERENCES accounts(account_id),
  beneficiary_account_id NUMBER NOT NULL CONSTRAINT fk_beneficiary_target REFERENCES accounts(account_id),
  nickname VARCHAR2(100) NOT NULL,
  status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL CONSTRAINT ck_beneficiary_status CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_beneficiary_different CHECK (source_account_id <> beneficiary_account_id)
);

CREATE TABLE customer_kyc (
  kyc_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_customer_kyc PRIMARY KEY,
  customer_id NUMBER NOT NULL CONSTRAINT fk_kyc_customer REFERENCES customers(customer_id),
  document_type VARCHAR2(40),
  document_reference VARCHAR2(100),
  status VARCHAR2(12) DEFAULT 'PENDING' NOT NULL CONSTRAINT ck_kyc_status CHECK (status IN ('PENDING','VERIFIED','REJECTED')),
  submitted_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  reviewed_by NUMBER CONSTRAINT fk_kyc_reviewer REFERENCES users(user_id),
  reviewed_at TIMESTAMP,
  rejection_reason VARCHAR2(500),
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE deposit_schemes (
  scheme_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_deposit_schemes PRIMARY KEY,
  scheme_code VARCHAR2(20) NOT NULL CONSTRAINT uk_deposit_scheme_code UNIQUE,
  scheme_name VARCHAR2(100) NOT NULL CONSTRAINT uk_deposit_scheme_name UNIQUE,
  scheme_type VARCHAR2(30) NOT NULL CONSTRAINT ck_deposit_scheme_type CHECK (scheme_type IN ('FIXED_DEPOSIT','MONTHLY_PROFIT','DPS','SAVINGS_PROFIT','SENIOR_CITIZEN','STUDENT_SAVINGS')),
  minimum_amount NUMBER(15,2) NOT NULL CONSTRAINT ck_deposit_scheme_min CHECK (minimum_amount > 0),
  maximum_amount NUMBER(15,2),
  minimum_months NUMBER NOT NULL,
  maximum_months NUMBER NOT NULL,
  annual_profit_rate NUMBER(7,4) NOT NULL CONSTRAINT ck_deposit_scheme_rate CHECK (annual_profit_rate >= 0 AND annual_profit_rate <= 100),
  calculation_method VARCHAR2(20) DEFAULT 'SIMPLE' NOT NULL CONSTRAINT ck_deposit_scheme_method CHECK (calculation_method IN ('SIMPLE','MONTHLY_COMPOUND')),
  payment_frequency VARCHAR2(20) DEFAULT 'AT_MATURITY' NOT NULL CONSTRAINT ck_deposit_scheme_frequency CHECK (payment_frequency IN ('AT_MATURITY','MONTHLY','RECURRING')),
  tax_percentage NUMBER(5,2) DEFAULT 0 NOT NULL CONSTRAINT ck_deposit_scheme_tax CHECK (tax_percentage BETWEEN 0 AND 100),
  early_withdrawal_rate NUMBER(7,4),
  senior_only CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT ck_deposit_scheme_senior CHECK (senior_only IN ('Y','N')),
  student_only CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT ck_deposit_scheme_student CHECK (student_only IN ('Y','N')),
  status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL CONSTRAINT ck_deposit_scheme_status CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_deposit_scheme_months CHECK (minimum_months > 0 AND maximum_months >= minimum_months),
  CONSTRAINT ck_deposit_scheme_max CHECK (maximum_amount IS NULL OR maximum_amount >= minimum_amount)
);

CREATE TABLE deposit_certificates (
  certificate_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_deposit_certificates PRIMARY KEY,
  certificate_number VARCHAR2(40) NOT NULL CONSTRAINT uk_certificate_number UNIQUE,
  customer_id NUMBER NOT NULL CONSTRAINT fk_certificate_customer REFERENCES customers(customer_id),
  account_id NUMBER CONSTRAINT fk_certificate_account REFERENCES accounts(account_id),
  scheme_id NUMBER NOT NULL CONSTRAINT fk_certificate_scheme REFERENCES deposit_schemes(scheme_id),
  principal_amount NUMBER(15,2) NOT NULL CONSTRAINT ck_certificate_principal CHECK (principal_amount > 0),
  annual_profit_rate NUMBER(7,4) NOT NULL CONSTRAINT ck_certificate_rate CHECK (annual_profit_rate >= 0 AND annual_profit_rate <= 100),
  duration_months NUMBER NOT NULL CONSTRAINT ck_certificate_duration CHECK (duration_months > 0),
  calculation_method VARCHAR2(20) NOT NULL CONSTRAINT ck_certificate_method CHECK (calculation_method IN ('SIMPLE','MONTHLY_COMPOUND')),
  tax_percentage NUMBER(5,2) DEFAULT 0 NOT NULL CONSTRAINT ck_certificate_tax CHECK (tax_percentage BETWEEN 0 AND 100),
  expected_gross_profit NUMBER(15,2) NOT NULL,
  expected_tax NUMBER(15,2) NOT NULL,
  expected_net_profit NUMBER(15,2) NOT NULL,
  expected_maturity_amount NUMBER(15,2) NOT NULL,
  opening_date DATE NOT NULL,
  maturity_date DATE NOT NULL,
  status VARCHAR2(24) DEFAULT 'QUOTATION' NOT NULL CONSTRAINT ck_certificate_status CHECK (status IN ('QUOTATION','ACTIVE','MATURED','CLOSED','PREMATURELY_CLOSED','BLOCKED')),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_certificate_dates CHECK (maturity_date >= opening_date)
);

CREATE SEQUENCE seq_business_reference START WITH 100001 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE login_history (
  login_history_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_login_history PRIMARY KEY,
  user_id NUMBER CONSTRAINT fk_login_history_user REFERENCES users(user_id),
  attempted_username VARCHAR2(50) NOT NULL,
  success_flag CHAR(1) NOT NULL CONSTRAINT ck_login_history_success CHECK (success_flag IN ('Y','N')),
  event_type VARCHAR2(20) DEFAULT 'LOGIN' NOT NULL,
  failure_reason VARCHAR2(100),
  occurred_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
