-- Smart Banking Management System: Oracle 19c+ core schema
-- Run only in a dedicated project schema. This script never drops existing data.

CREATE TABLE branches (
  branch_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_branches PRIMARY KEY,
  branch_code VARCHAR2(12) NOT NULL CONSTRAINT uk_branches_code UNIQUE,
  branch_name VARCHAR2(100) NOT NULL,
  city VARCHAR2(50) NOT NULL,
  address VARCHAR2(200) NOT NULL,
  phone VARCHAR2(20), swift_code VARCHAR2(20),
  status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL CONSTRAINT ck_branches_status CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE account_types (
  account_type_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_account_types PRIMARY KEY,
  type_name VARCHAR2(40) NOT NULL CONSTRAINT uk_account_types_name UNIQUE,
  description VARCHAR2(200),
  min_balance NUMBER(15,2) DEFAULT 0 NOT NULL CONSTRAINT ck_account_type_min CHECK (min_balance >= 0),
  annual_interest_rate NUMBER(5,2) DEFAULT 0 NOT NULL CONSTRAINT ck_account_type_rate CHECK (annual_interest_rate BETWEEN 0 AND 100),
  status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL CONSTRAINT ck_account_types_status CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE customers (
  customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_customers PRIMARY KEY,
  first_name VARCHAR2(50) NOT NULL, last_name VARCHAR2(50) NOT NULL,
  date_of_birth DATE NOT NULL, gender CHAR(1) CONSTRAINT ck_customer_gender CHECK (gender IN ('M','F','O')),
  phone VARCHAR2(20) NOT NULL CONSTRAINT uk_customer_phone UNIQUE,
  email VARCHAR2(100) CONSTRAINT uk_customer_email UNIQUE,
  national_id VARCHAR2(30) NOT NULL CONSTRAINT uk_customer_nid UNIQUE,
  address VARCHAR2(200) NOT NULL, occupation VARCHAR2(100),
  annual_income NUMBER(15,2) DEFAULT 0 CONSTRAINT ck_customer_income CHECK (annual_income >= 0),
  marital_status VARCHAR2(20),
  status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL CONSTRAINT ck_customers_status CHECK (status IN ('ACTIVE','BLOCKED')),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE employees (
  employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_employees PRIMARY KEY,
  branch_id NUMBER NOT NULL CONSTRAINT fk_employee_branch REFERENCES branches(branch_id),
  employee_code VARCHAR2(20) NOT NULL CONSTRAINT uk_employee_code UNIQUE,
  first_name VARCHAR2(50) NOT NULL, last_name VARCHAR2(50) NOT NULL,
  national_id VARCHAR2(30) NOT NULL CONSTRAINT uk_employee_nid UNIQUE,
  job_title VARCHAR2(100) NOT NULL, email VARCHAR2(100) NOT NULL CONSTRAINT uk_employee_email UNIQUE,
  phone VARCHAR2(20), salary NUMBER(15,2) NOT NULL CONSTRAINT ck_employee_salary CHECK (salary > 0),
  hire_date DATE DEFAULT SYSDATE NOT NULL,
  status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL CONSTRAINT ck_employees_status CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE users (
  user_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_users PRIMARY KEY,
  customer_id NUMBER CONSTRAINT fk_user_customer REFERENCES customers(customer_id),
  employee_id NUMBER CONSTRAINT fk_user_employee REFERENCES employees(employee_id),
  username VARCHAR2(50) NOT NULL CONSTRAINT uk_users_username UNIQUE,
  password_hash VARCHAR2(255) NOT NULL,
  role VARCHAR2(20) NOT NULL CONSTRAINT ck_users_role CHECK (role IN ('ADMIN','MANAGER','EMPLOYEE','CUSTOMER')),
  is_active CHAR(1) DEFAULT 'Y' NOT NULL CONSTRAINT ck_users_active CHECK (is_active IN ('Y','N')),
  must_change_password CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT ck_users_must_change CHECK (must_change_password IN ('Y','N')),
  account_locked CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT ck_users_locked CHECK (account_locked IN ('Y','N')),
  locked_at TIMESTAMP, password_changed_at TIMESTAMP, updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  last_login TIMESTAMP, failed_login_count NUMBER DEFAULT 0 NOT NULL CONSTRAINT ck_login_count CHECK (failed_login_count >= 0),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_user_principal CHECK (
    (role = 'CUSTOMER' AND customer_id IS NOT NULL AND employee_id IS NULL) OR
    (role IN ('MANAGER','EMPLOYEE') AND employee_id IS NOT NULL AND customer_id IS NULL) OR
    (role = 'ADMIN' AND customer_id IS NULL)
  ),
  CONSTRAINT uk_user_customer UNIQUE(customer_id), CONSTRAINT uk_user_employee UNIQUE(employee_id)
);

CREATE TABLE accounts (
  account_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_accounts PRIMARY KEY,
  account_number VARCHAR2(24) NOT NULL CONSTRAINT uk_account_number UNIQUE,
  customer_id NUMBER NOT NULL CONSTRAINT fk_account_customer REFERENCES customers(customer_id),
  branch_id NUMBER NOT NULL CONSTRAINT fk_account_branch REFERENCES branches(branch_id),
  account_type_id NUMBER NOT NULL CONSTRAINT fk_account_type REFERENCES account_types(account_type_id),
  balance NUMBER(15,2) DEFAULT 0 NOT NULL CONSTRAINT ck_account_balance CHECK (balance >= 0),
  currency VARCHAR2(3) DEFAULT 'BDT' NOT NULL CONSTRAINT ck_account_currency CHECK (currency IN ('BDT','USD','EUR')),
  status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL CONSTRAINT ck_account_status CHECK (status IN ('ACTIVE','FROZEN','CLOSED')),
  open_date DATE DEFAULT SYSDATE NOT NULL, close_date DATE, last_transaction_date TIMESTAMP,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_account_close CHECK ((status = 'CLOSED' AND close_date IS NOT NULL) OR status <> 'CLOSED')
);

CREATE TABLE loan_types (
  loan_type_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_loan_types PRIMARY KEY,
  type_name VARCHAR2(60) NOT NULL CONSTRAINT uk_loan_type_name UNIQUE,
  min_amount NUMBER(15,2) NOT NULL, max_amount NUMBER(15,2) NOT NULL,
  annual_interest_rate NUMBER(5,2) NOT NULL, min_term_months NUMBER NOT NULL, max_term_months NUMBER NOT NULL,
  status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL CONSTRAINT ck_loan_type_status CHECK (status IN ('ACTIVE','INACTIVE')),
  CONSTRAINT ck_loan_type_amounts CHECK (min_amount > 0 AND max_amount >= min_amount),
  CONSTRAINT ck_loan_type_rate CHECK (annual_interest_rate BETWEEN 0 AND 100),
  CONSTRAINT ck_loan_type_terms CHECK (min_term_months > 0 AND max_term_months >= min_term_months)
);

CREATE TABLE loans (
  loan_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_loans PRIMARY KEY,
  loan_number VARCHAR2(30) NOT NULL CONSTRAINT uk_loan_number UNIQUE,
  customer_id NUMBER NOT NULL CONSTRAINT fk_loan_customer REFERENCES customers(customer_id),
  loan_type_id NUMBER NOT NULL CONSTRAINT fk_loan_type REFERENCES loan_types(loan_type_id),
  disbursement_account_id NUMBER NOT NULL CONSTRAINT fk_loan_account REFERENCES accounts(account_id),
  requested_amount NUMBER(15,2) NOT NULL CONSTRAINT ck_loan_requested CHECK (requested_amount > 0),
  approved_amount NUMBER(15,2), interest_rate NUMBER(5,2) NOT NULL CONSTRAINT ck_loan_rate CHECK (interest_rate BETWEEN 0 AND 100),
  term_months NUMBER NOT NULL CONSTRAINT ck_loan_term CHECK (term_months > 0),
  monthly_installment NUMBER(15,2), total_repayable NUMBER(15,2), outstanding_balance NUMBER(15,2),
  status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL CONSTRAINT ck_loan_status CHECK (status IN ('PENDING','APPROVED','REJECTED','ACTIVE','COMPLETED')),
  reviewed_by NUMBER CONSTRAINT fk_loan_reviewer REFERENCES employees(employee_id), reviewed_at TIMESTAMP, rejection_reason VARCHAR2(500),
  application_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, start_date DATE, end_date DATE,
  CONSTRAINT ck_loan_approved_amount CHECK (approved_amount IS NULL OR (approved_amount > 0 AND approved_amount <= requested_amount)),
  CONSTRAINT ck_loan_rejection CHECK (status <> 'REJECTED' OR rejection_reason IS NOT NULL)
);

CREATE TABLE transactions (
  transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_transactions PRIMARY KEY,
  account_id NUMBER NOT NULL CONSTRAINT fk_transaction_account REFERENCES accounts(account_id),
  related_account_id NUMBER CONSTRAINT fk_transaction_related REFERENCES accounts(account_id),
  transaction_type VARCHAR2(30) NOT NULL CONSTRAINT ck_transaction_type CHECK (transaction_type IN ('DEPOSIT','WITHDRAWAL','TRANSFER_DEBIT','TRANSFER_CREDIT','LOAN_DISBURSEMENT','LOAN_PAYMENT')),
  amount NUMBER(15,2) NOT NULL CONSTRAINT ck_transaction_amount CHECK (amount > 0),
  previous_balance NUMBER(15,2) NOT NULL, new_balance NUMBER(15,2) NOT NULL,
  status VARCHAR2(12) DEFAULT 'SUCCESS' NOT NULL CONSTRAINT ck_transaction_status CHECK (status IN ('SUCCESS','REVERSED')),
  reference_no VARCHAR2(50) NOT NULL CONSTRAINT uk_transaction_reference UNIQUE,
  description VARCHAR2(200), processed_by NUMBER CONSTRAINT fk_transaction_user REFERENCES users(user_id),
  transaction_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_transaction_balances CHECK (previous_balance >= 0 AND new_balance >= 0)
);

CREATE TABLE fund_transfers (
  transfer_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_transfers PRIMARY KEY,
  transfer_reference VARCHAR2(50) NOT NULL CONSTRAINT uk_transfer_reference UNIQUE,
  from_account_id NUMBER NOT NULL CONSTRAINT fk_transfer_from REFERENCES accounts(account_id),
  to_account_id NUMBER NOT NULL CONSTRAINT fk_transfer_to REFERENCES accounts(account_id),
  amount NUMBER(15,2) NOT NULL CONSTRAINT ck_transfer_amount CHECK (amount > 0),
  debit_transaction_id NUMBER NOT NULL CONSTRAINT fk_transfer_debit REFERENCES transactions(transaction_id),
  credit_transaction_id NUMBER NOT NULL CONSTRAINT fk_transfer_credit REFERENCES transactions(transaction_id),
  initiated_by NUMBER CONSTRAINT fk_transfer_user REFERENCES users(user_id),
  transfer_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_transfer_accounts CHECK (from_account_id <> to_account_id)
);

CREATE TABLE loan_payments (
  payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_loan_payments PRIMARY KEY,
  loan_id NUMBER NOT NULL CONSTRAINT fk_payment_loan REFERENCES loans(loan_id),
  account_id NUMBER NOT NULL CONSTRAINT fk_payment_account REFERENCES accounts(account_id),
  transaction_id NUMBER NOT NULL CONSTRAINT fk_payment_transaction REFERENCES transactions(transaction_id),
  amount NUMBER(15,2) NOT NULL CONSTRAINT ck_payment_amount CHECK (amount > 0),
  previous_outstanding NUMBER(15,2) NOT NULL, new_outstanding NUMBER(15,2) NOT NULL,
  received_by NUMBER CONSTRAINT fk_payment_user REFERENCES users(user_id),
  payment_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_payment_outstanding CHECK (previous_outstanding > 0 AND new_outstanding >= 0)
);

CREATE TABLE audit_log (
  audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_audit_log PRIMARY KEY,
  table_name VARCHAR2(50) NOT NULL, record_id NUMBER, action_name VARCHAR2(30) NOT NULL,
  action_by VARCHAR2(100) DEFAULT SYS_CONTEXT('USERENV','SESSION_USER') NOT NULL,
  old_summary CLOB, new_summary CLOB, action_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE SEQUENCE seq_business_reference START WITH 100001 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE login_history (
  login_history_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_login_history PRIMARY KEY,
  user_id NUMBER CONSTRAINT fk_login_history_user REFERENCES users(user_id),
  attempted_username VARCHAR2(50) NOT NULL,
  success_flag CHAR(1) NOT NULL CONSTRAINT ck_login_history_success CHECK (success_flag IN ('Y','N')),
  event_type VARCHAR2(20) DEFAULT 'LOGIN' NOT NULL,
  failure_reason VARCHAR2(100),
  occurred_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
