-- Browser FreeSQL worksheet for a complete empty-schema installation.
-- Review before running; this script does not drop objects.

-- ===== database/sql/01_create_tables.sql =====
-- Smart Banking Management System: Oracle 19c+ core schema
-- Run only in a dedicated project schema. This script never drops existing data.

CREATE TABLE bank_profile (
  profile_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_bank_profile PRIMARY KEY,
  bank_name VARCHAR2(120) NOT NULL,
  short_name VARCHAR2(40) NOT NULL CONSTRAINT uk_bank_profile_short_name UNIQUE,
  head_office_address VARCHAR2(240) NOT NULL,
  support_phone VARCHAR2(30) NOT NULL,
  support_email VARCHAR2(120) NOT NULL,
  website VARCHAR2(160),
  swift_code VARCHAR2(20),
  currency VARCHAR2(3) DEFAULT 'BDT' NOT NULL CONSTRAINT ck_bank_profile_currency CHECK (currency = 'BDT'),
  status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL CONSTRAINT ck_bank_profile_status CHECK (status IN ('ACTIVE','INACTIVE')),
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_bank_profile_singleton CHECK (profile_id = 1)
);

CREATE TABLE branches (
  branch_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_branches PRIMARY KEY,
  branch_code VARCHAR2(12) NOT NULL CONSTRAINT uk_branches_code UNIQUE,
  branch_name VARCHAR2(100) NOT NULL,
  city VARCHAR2(50) NOT NULL,
  address VARCHAR2(200) NOT NULL,
  phone VARCHAR2(20), swift_code VARCHAR2(20),
  status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL CONSTRAINT ck_branches_status CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE account_types (
  account_type_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_account_types PRIMARY KEY,
  type_name VARCHAR2(40) NOT NULL CONSTRAINT uk_account_types_name UNIQUE,
  description VARCHAR2(200),
  min_balance NUMBER(15,2) DEFAULT 0 NOT NULL CONSTRAINT ck_account_type_min CHECK (min_balance >= 0),
  annual_interest_rate NUMBER(5,2) DEFAULT 0 NOT NULL CONSTRAINT ck_account_type_rate CHECK (annual_interest_rate BETWEEN 0 AND 100),
  status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL CONSTRAINT ck_account_types_status CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE customers (
  customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_customers PRIMARY KEY,
  first_name VARCHAR2(50) NOT NULL, last_name VARCHAR2(50) NOT NULL,
  date_of_birth DATE NOT NULL, gender CHAR(1) CONSTRAINT ck_customer_gender CHECK (gender IN ('M','F','O')),
  phone VARCHAR2(20) NOT NULL CONSTRAINT uk_customer_phone UNIQUE,
  email VARCHAR2(100) CONSTRAINT uk_customer_email UNIQUE,
  national_id VARCHAR2(30) NOT NULL CONSTRAINT uk_customer_nid UNIQUE,
  address VARCHAR2(200) NOT NULL, occupation VARCHAR2(100),
  annual_income NUMBER(15,2) DEFAULT 0 CONSTRAINT ck_customer_income CHECK (annual_income >= 0),
  marital_status VARCHAR2(20),
  status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL CONSTRAINT ck_customers_status CHECK (status IN ('ACTIVE','BLOCKED')),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE employees (
  employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_employees PRIMARY KEY,
  branch_id NUMBER NOT NULL CONSTRAINT fk_employee_branch REFERENCES branches(branch_id),
  employee_code VARCHAR2(20) NOT NULL CONSTRAINT uk_employee_code UNIQUE,
  first_name VARCHAR2(50) NOT NULL, last_name VARCHAR2(50) NOT NULL,
  national_id VARCHAR2(30) NOT NULL CONSTRAINT uk_employee_nid UNIQUE,
  job_title VARCHAR2(100) NOT NULL, email VARCHAR2(100) NOT NULL CONSTRAINT uk_employee_email UNIQUE,
  phone VARCHAR2(20), salary NUMBER(15,2) NOT NULL CONSTRAINT ck_employee_salary CHECK (salary > 0),
  hire_date DATE DEFAULT SYSDATE NOT NULL,
  status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL CONSTRAINT ck_employees_status CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE users (
  user_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_users PRIMARY KEY,
  customer_id NUMBER CONSTRAINT fk_user_customer REFERENCES customers(customer_id),
  employee_id NUMBER CONSTRAINT fk_user_employee REFERENCES employees(employee_id),
  username VARCHAR2(50) NOT NULL CONSTRAINT uk_users_username UNIQUE,
  staff_code VARCHAR2(20) CONSTRAINT uk_users_staff_code UNIQUE,
  display_name VARCHAR2(100),
  password_hash VARCHAR2(255) NOT NULL,
  role VARCHAR2(20) NOT NULL CONSTRAINT ck_users_role CHECK (role IN ('ADMIN','MANAGER','EMPLOYEE','CUSTOMER')),
  is_active CHAR(1) DEFAULT 'Y' NOT NULL CONSTRAINT ck_users_active CHECK (is_active IN ('Y','N')),
  must_change_password CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT ck_users_must_change CHECK (must_change_password IN ('Y','N')),
  account_locked CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT ck_users_locked CHECK (account_locked IN ('Y','N')),
  locked_at TIMESTAMP, password_changed_at TIMESTAMP, updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  last_login TIMESTAMP, failed_login_count NUMBER DEFAULT 0 NOT NULL CONSTRAINT ck_login_count CHECK (failed_login_count >= 0),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_user_principal CHECK (
    (role = 'CUSTOMER' AND customer_id IS NOT NULL AND employee_id IS NULL AND staff_code IS NULL) OR
    (role IN ('ADMIN','MANAGER','EMPLOYEE') AND employee_id IS NOT NULL AND customer_id IS NULL AND staff_code IS NOT NULL)
  ),
  CONSTRAINT uk_user_customer UNIQUE(customer_id), CONSTRAINT uk_user_employee UNIQUE(employee_id)
);

CREATE TABLE accounts (
  account_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_accounts PRIMARY KEY,
  account_number VARCHAR2(24) NOT NULL CONSTRAINT uk_account_number UNIQUE,
  customer_id NUMBER NOT NULL CONSTRAINT fk_account_customer REFERENCES customers(customer_id),
  branch_id NUMBER NOT NULL CONSTRAINT fk_account_branch REFERENCES branches(branch_id),
  account_type_id NUMBER NOT NULL CONSTRAINT fk_account_type REFERENCES account_types(account_type_id),
  balance NUMBER(15,2) DEFAULT 0 NOT NULL CONSTRAINT ck_account_balance CHECK (balance >= 0),
  currency VARCHAR2(3) DEFAULT 'BDT' NOT NULL CONSTRAINT ck_account_currency CHECK (currency IN ('BDT','USD','EUR')),
  status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL CONSTRAINT ck_account_status CHECK (status IN ('ACTIVE','FROZEN','CLOSED')),
  open_date DATE DEFAULT SYSDATE NOT NULL, close_date DATE, last_transaction_date TIMESTAMP,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_account_close CHECK ((status = 'CLOSED' AND close_date IS NOT NULL) OR status <> 'CLOSED')
);

  CREATE TABLE loan_types (
    loan_type_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_loan_types PRIMARY KEY,
    type_name VARCHAR2(60) NOT NULL CONSTRAINT uk_loan_type_name UNIQUE,
    short_description VARCHAR2(200), detailed_description VARCHAR2(1000),
    minimum_annual_income NUMBER(15,2), processing_fee_percentage NUMBER(5,2) DEFAULT 0 NOT NULL,
    eligibility_summary VARCHAR2(500), required_document_summary VARCHAR2(500),
    interest_method VARCHAR2(20) DEFAULT 'REDUCING_BALANCE' NOT NULL,
    min_amount NUMBER(15,2) NOT NULL, max_amount NUMBER(15,2) NOT NULL,
  annual_interest_rate NUMBER(5,2) NOT NULL, min_term_months NUMBER NOT NULL, max_term_months NUMBER NOT NULL,
  status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL CONSTRAINT ck_loan_type_status CHECK (status IN ('ACTIVE','INACTIVE')),
  CONSTRAINT ck_loan_type_amounts CHECK (min_amount > 0 AND max_amount >= min_amount),
    CONSTRAINT ck_loan_type_rate CHECK (annual_interest_rate BETWEEN 0 AND 100),
    CONSTRAINT ck_loan_type_income CHECK (minimum_annual_income IS NULL OR minimum_annual_income >= 0),
    CONSTRAINT ck_loan_type_fee CHECK (processing_fee_percentage BETWEEN 0 AND 100),
    CONSTRAINT ck_loan_type_method CHECK (interest_method IN ('REDUCING_BALANCE','FLAT_RATE')),
  CONSTRAINT ck_loan_type_terms CHECK (min_term_months > 0 AND max_term_months >= min_term_months)
);

CREATE TABLE loans (
  loan_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_loans PRIMARY KEY,
  loan_number VARCHAR2(30) NOT NULL CONSTRAINT uk_loan_number UNIQUE,
  customer_id NUMBER NOT NULL CONSTRAINT fk_loan_customer REFERENCES customers(customer_id),
  loan_type_id NUMBER NOT NULL CONSTRAINT fk_loan_type REFERENCES loan_types(loan_type_id),
  disbursement_account_id NUMBER NOT NULL CONSTRAINT fk_loan_account REFERENCES accounts(account_id),
  requested_amount NUMBER(15,2) NOT NULL CONSTRAINT ck_loan_requested CHECK (requested_amount > 0),
  approved_amount NUMBER(15,2), interest_rate NUMBER(5,2) NOT NULL CONSTRAINT ck_loan_rate CHECK (interest_rate BETWEEN 0 AND 100),
  term_months NUMBER NOT NULL CONSTRAINT ck_loan_term CHECK (term_months > 0),
  monthly_installment NUMBER(15,2), total_repayable NUMBER(15,2), outstanding_balance NUMBER(15,2),
  status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL CONSTRAINT ck_loan_status CHECK (status IN ('PENDING','APPROVED','REJECTED','ACTIVE','COMPLETED')),
  reviewed_by NUMBER CONSTRAINT fk_loan_reviewer REFERENCES employees(employee_id), reviewed_at TIMESTAMP, rejection_reason VARCHAR2(500),
  application_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, start_date DATE, end_date DATE,
  CONSTRAINT ck_loan_approved_amount CHECK (approved_amount IS NULL OR (approved_amount > 0 AND approved_amount <= requested_amount)),
  CONSTRAINT ck_loan_rejection CHECK (status <> 'REJECTED' OR rejection_reason IS NOT NULL)
);

CREATE TABLE transactions (
  transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_transactions PRIMARY KEY,
  account_id NUMBER NOT NULL CONSTRAINT fk_transaction_account REFERENCES accounts(account_id),
  related_account_id NUMBER CONSTRAINT fk_transaction_related REFERENCES accounts(account_id),
  transaction_type VARCHAR2(30) NOT NULL CONSTRAINT ck_transaction_type CHECK (transaction_type IN ('DEPOSIT','WITHDRAWAL','TRANSFER_DEBIT','TRANSFER_CREDIT','LOAN_DISBURSEMENT','LOAN_PAYMENT','REVERSAL_DEBIT','REVERSAL_CREDIT')),
  amount NUMBER(15,2) NOT NULL CONSTRAINT ck_transaction_amount CHECK (amount > 0),
  previous_balance NUMBER(15,2) NOT NULL, new_balance NUMBER(15,2) NOT NULL,
  status VARCHAR2(12) DEFAULT 'SUCCESS' NOT NULL CONSTRAINT ck_transaction_status CHECK (status IN ('SUCCESS','REVERSED')),
  reference_no VARCHAR2(50) NOT NULL CONSTRAINT uk_transaction_reference UNIQUE,
  description VARCHAR2(200), processed_by NUMBER CONSTRAINT fk_transaction_user REFERENCES users(user_id),
  transaction_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_transaction_balances CHECK (previous_balance >= 0 AND new_balance >= 0)
);

CREATE TABLE fund_transfers (
  transfer_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_transfers PRIMARY KEY,
  transfer_reference VARCHAR2(50) NOT NULL CONSTRAINT uk_transfer_reference UNIQUE,
  from_account_id NUMBER NOT NULL CONSTRAINT fk_transfer_from REFERENCES accounts(account_id),
  to_account_id NUMBER NOT NULL CONSTRAINT fk_transfer_to REFERENCES accounts(account_id),
  amount NUMBER(15,2) NOT NULL CONSTRAINT ck_transfer_amount CHECK (amount > 0),
  debit_transaction_id NUMBER NOT NULL CONSTRAINT fk_transfer_debit REFERENCES transactions(transaction_id),
  credit_transaction_id NUMBER NOT NULL CONSTRAINT fk_transfer_credit REFERENCES transactions(transaction_id),
  initiated_by NUMBER CONSTRAINT fk_transfer_user REFERENCES users(user_id),
  transfer_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_transfer_accounts CHECK (from_account_id <> to_account_id)
);

CREATE TABLE loan_payments (
  payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_loan_payments PRIMARY KEY,
  loan_id NUMBER NOT NULL CONSTRAINT fk_payment_loan REFERENCES loans(loan_id),
  account_id NUMBER NOT NULL CONSTRAINT fk_payment_account REFERENCES accounts(account_id),
  transaction_id NUMBER NOT NULL CONSTRAINT fk_payment_transaction REFERENCES transactions(transaction_id),
  amount NUMBER(15,2) NOT NULL CONSTRAINT ck_payment_amount CHECK (amount > 0),
  previous_outstanding NUMBER(15,2) NOT NULL, new_outstanding NUMBER(15,2) NOT NULL,
  received_by NUMBER CONSTRAINT fk_payment_user REFERENCES users(user_id),
  payment_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_payment_outstanding CHECK (previous_outstanding > 0 AND new_outstanding >= 0)
);

CREATE TABLE audit_log (
  audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_audit_log PRIMARY KEY,
  table_name VARCHAR2(50) NOT NULL, record_id NUMBER, action_name VARCHAR2(30) NOT NULL,
  action_by VARCHAR2(100) DEFAULT SYS_CONTEXT('USERENV','SESSION_USER') NOT NULL,
  old_summary CLOB, new_summary CLOB, action_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE transaction_reversals (
  reversal_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_transaction_reversals PRIMARY KEY,
  original_transaction_id NUMBER NOT NULL CONSTRAINT fk_reversal_original REFERENCES transactions(transaction_id),
  reversal_transaction_id NUMBER NOT NULL CONSTRAINT fk_reversal_transaction REFERENCES transactions(transaction_id),
  reason VARCHAR2(500) NOT NULL,
  reversed_by NUMBER CONSTRAINT fk_reversal_user REFERENCES users(user_id),
  reversed_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  status VARCHAR2(12) DEFAULT 'COMPLETED' NOT NULL CONSTRAINT ck_reversal_status CHECK (status IN ('COMPLETED','FAILED')),
  CONSTRAINT uk_reversal_original UNIQUE(original_transaction_id),
  CONSTRAINT uk_reversal_transaction UNIQUE(reversal_transaction_id)
);

CREATE TABLE user_preferences (
  user_id NUMBER CONSTRAINT pk_user_preferences PRIMARY KEY REFERENCES users(user_id),
  theme VARCHAR2(10) DEFAULT 'SYSTEM' NOT NULL CONSTRAINT ck_preferences_theme CHECK (theme IN ('LIGHT','DARK','SYSTEM')),
  rows_per_page NUMBER DEFAULT 20 NOT NULL CONSTRAINT ck_preferences_rows CHECK (rows_per_page BETWEEN 5 AND 100),
  currency_display VARCHAR2(3) DEFAULT 'BDT' NOT NULL CONSTRAINT ck_preferences_currency CHECK (currency_display='BDT'),
  notifications_enabled CHAR(1) DEFAULT 'Y' NOT NULL CONSTRAINT ck_preferences_notifications CHECK (notifications_enabled IN ('Y','N')),
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE beneficiaries (
  beneficiary_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_beneficiaries PRIMARY KEY,
  customer_id NUMBER NOT NULL CONSTRAINT fk_beneficiary_customer REFERENCES customers(customer_id),
  source_account_id NUMBER NOT NULL CONSTRAINT fk_beneficiary_source REFERENCES accounts(account_id),
  beneficiary_account_id NUMBER NOT NULL CONSTRAINT fk_beneficiary_target REFERENCES accounts(account_id),
  nickname VARCHAR2(100) NOT NULL,
  status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL CONSTRAINT ck_beneficiary_status CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_beneficiary_different CHECK (source_account_id <> beneficiary_account_id)
);

CREATE TABLE customer_kyc (
  kyc_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_customer_kyc PRIMARY KEY,
  customer_id NUMBER NOT NULL CONSTRAINT fk_kyc_customer REFERENCES customers(customer_id),
  document_type VARCHAR2(40),
  document_reference VARCHAR2(100),
  status VARCHAR2(12) DEFAULT 'PENDING' NOT NULL CONSTRAINT ck_kyc_status CHECK (status IN ('PENDING','VERIFIED','REJECTED')),
  submitted_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  reviewed_by NUMBER CONSTRAINT fk_kyc_reviewer REFERENCES users(user_id),
  reviewed_at TIMESTAMP,
  rejection_reason VARCHAR2(500),
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE deposit_schemes (
  scheme_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_deposit_schemes PRIMARY KEY,
  scheme_code VARCHAR2(20) NOT NULL CONSTRAINT uk_deposit_scheme_code UNIQUE,
  scheme_name VARCHAR2(100) NOT NULL CONSTRAINT uk_deposit_scheme_name UNIQUE,
  scheme_type VARCHAR2(30) NOT NULL CONSTRAINT ck_deposit_scheme_type CHECK (scheme_type IN ('FIXED_DEPOSIT','MONTHLY_PROFIT','DPS','SAVINGS_PROFIT','SENIOR_CITIZEN','STUDENT_SAVINGS')),
  minimum_amount NUMBER(15,2) NOT NULL CONSTRAINT ck_deposit_scheme_min CHECK (minimum_amount > 0),
  maximum_amount NUMBER(15,2),
  minimum_months NUMBER NOT NULL,
  maximum_months NUMBER NOT NULL,
  annual_profit_rate NUMBER(7,4) NOT NULL CONSTRAINT ck_deposit_scheme_rate CHECK (annual_profit_rate >= 0 AND annual_profit_rate <= 100),
  calculation_method VARCHAR2(20) DEFAULT 'SIMPLE' NOT NULL CONSTRAINT ck_deposit_scheme_method CHECK (calculation_method IN ('SIMPLE','MONTHLY_COMPOUND')),
  payment_frequency VARCHAR2(20) DEFAULT 'AT_MATURITY' NOT NULL CONSTRAINT ck_deposit_scheme_frequency CHECK (payment_frequency IN ('AT_MATURITY','MONTHLY','RECURRING')),
  tax_percentage NUMBER(5,2) DEFAULT 0 NOT NULL CONSTRAINT ck_deposit_scheme_tax CHECK (tax_percentage BETWEEN 0 AND 100),
  early_withdrawal_rate NUMBER(7,4),
  senior_only CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT ck_deposit_scheme_senior CHECK (senior_only IN ('Y','N')),
  student_only CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT ck_deposit_scheme_student CHECK (student_only IN ('Y','N')),
  status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL CONSTRAINT ck_deposit_scheme_status CHECK (status IN ('ACTIVE','INACTIVE')),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_deposit_scheme_months CHECK (minimum_months > 0 AND maximum_months >= minimum_months),
  CONSTRAINT ck_deposit_scheme_max CHECK (maximum_amount IS NULL OR maximum_amount >= minimum_amount)
);

CREATE TABLE deposit_certificates (
  certificate_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_deposit_certificates PRIMARY KEY,
  certificate_number VARCHAR2(40) NOT NULL CONSTRAINT uk_certificate_number UNIQUE,
  customer_id NUMBER NOT NULL CONSTRAINT fk_certificate_customer REFERENCES customers(customer_id),
  account_id NUMBER CONSTRAINT fk_certificate_account REFERENCES accounts(account_id),
  scheme_id NUMBER NOT NULL CONSTRAINT fk_certificate_scheme REFERENCES deposit_schemes(scheme_id),
  principal_amount NUMBER(15,2) NOT NULL CONSTRAINT ck_certificate_principal CHECK (principal_amount > 0),
  annual_profit_rate NUMBER(7,4) NOT NULL CONSTRAINT ck_certificate_rate CHECK (annual_profit_rate >= 0 AND annual_profit_rate <= 100),
  duration_months NUMBER NOT NULL CONSTRAINT ck_certificate_duration CHECK (duration_months > 0),
  calculation_method VARCHAR2(20) NOT NULL CONSTRAINT ck_certificate_method CHECK (calculation_method IN ('SIMPLE','MONTHLY_COMPOUND')),
  tax_percentage NUMBER(5,2) DEFAULT 0 NOT NULL CONSTRAINT ck_certificate_tax CHECK (tax_percentage BETWEEN 0 AND 100),
  expected_gross_profit NUMBER(15,2) NOT NULL,
  expected_tax NUMBER(15,2) NOT NULL,
  expected_net_profit NUMBER(15,2) NOT NULL,
  expected_maturity_amount NUMBER(15,2) NOT NULL,
  opening_date DATE NOT NULL,
  maturity_date DATE NOT NULL,
  status VARCHAR2(24) DEFAULT 'QUOTATION' NOT NULL CONSTRAINT ck_certificate_status CHECK (status IN ('QUOTATION','ACTIVE','MATURED','CLOSED','PREMATURELY_CLOSED','BLOCKED')),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_certificate_dates CHECK (maturity_date >= opening_date)
);

CREATE SEQUENCE seq_business_reference START WITH 100001 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE login_history (
  login_history_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_login_history PRIMARY KEY,
  user_id NUMBER CONSTRAINT fk_login_history_user REFERENCES users(user_id),
  attempted_username VARCHAR2(50) NOT NULL,
  success_flag CHAR(1) NOT NULL CONSTRAINT ck_login_history_success CHECK (success_flag IN ('Y','N')),
  event_type VARCHAR2(20) DEFAULT 'LOGIN' NOT NULL,
  failure_reason VARCHAR2(100),
  occurred_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE notifications (
  notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_notifications PRIMARY KEY,
  user_id NUMBER NOT NULL CONSTRAINT fk_notification_user REFERENCES users(user_id),
  event_type VARCHAR2(40) NOT NULL,
  title VARCHAR2(160) NOT NULL,
  message VARCHAR2(1000) NOT NULL,
  entity_type VARCHAR2(40), entity_id NUMBER,
  is_read CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT ck_notification_read CHECK (is_read IN ('Y','N')),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  read_at TIMESTAMP
);

CREATE TABLE service_requests (
  request_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_service_requests PRIMARY KEY,
  request_number VARCHAR2(30) NOT NULL CONSTRAINT uk_service_request_number UNIQUE,
  customer_id NUMBER NOT NULL CONSTRAINT fk_service_request_customer REFERENCES customers(customer_id),
  branch_id NUMBER NOT NULL CONSTRAINT fk_service_request_branch REFERENCES branches(branch_id),
  request_type VARCHAR2(30) NOT NULL CONSTRAINT ck_service_request_type CHECK (request_type IN ('ACCOUNT_FREEZE','ACCOUNT_UNFREEZE','STATEMENT','PROFILE_HELP','BENEFICIARY_HELP','LOAN_INFORMATION','GENERAL_SUPPORT')),
  subject VARCHAR2(160) NOT NULL, description VARCHAR2(1000) NOT NULL,
  status VARCHAR2(20) DEFAULT 'OPEN' NOT NULL CONSTRAINT ck_service_request_status CHECK (status IN ('OPEN','IN_PROGRESS','RESOLVED','REJECTED','CANCELLED')),
  assigned_to NUMBER CONSTRAINT fk_service_request_assignee REFERENCES employees(employee_id),
  resolution_note VARCHAR2(1000), created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, resolved_at TIMESTAMP
);

-- ===== database/sql/02_constraints.sql =====
-- Constraints are declared beside their columns in 01_create_tables.sql so beginners can
-- understand each rule in context. These additional rules require separate ALTER statements.
ALTER TABLE loans ADD CONSTRAINT ck_loan_totals CHECK (
  (status IN ('PENDING','REJECTED') AND outstanding_balance IS NULL)
  OR (status IN ('APPROVED','ACTIVE','COMPLETED') AND total_repayable > 0 AND outstanding_balance >= 0)
);

ALTER TABLE fund_transfers ADD CONSTRAINT uk_transfer_debit UNIQUE (debit_transaction_id);
ALTER TABLE fund_transfers ADD CONSTRAINT uk_transfer_credit UNIQUE (credit_transaction_id);
ALTER TABLE loan_payments ADD CONSTRAINT uk_payment_transaction UNIQUE (transaction_id);

-- ===== database/sql/05_indexes.sql =====
CREATE INDEX idx_accounts_customer ON accounts(customer_id, status);
CREATE INDEX idx_accounts_branch ON accounts(branch_id, status);
CREATE INDEX idx_employees_branch ON employees(branch_id, status);
CREATE INDEX idx_transactions_account_date ON transactions(account_id, transaction_date DESC);
CREATE INDEX idx_transactions_type_date ON transactions(transaction_type, transaction_date DESC);
CREATE INDEX idx_loans_customer_status ON loans(customer_id, status);
CREATE INDEX idx_loans_status_date ON loans(status, application_date);
CREATE INDEX idx_audit_date ON audit_log(action_date DESC);
CREATE UNIQUE INDEX uk_users_username_lower ON users(LOWER(username));
CREATE UNIQUE INDEX uk_users_staff_code_lower ON users(LOWER(staff_code));
CREATE INDEX idx_users_role_active ON users(role, is_active, account_locked);
CREATE INDEX idx_users_employee ON users(employee_id);
CREATE INDEX idx_login_history_user_date ON login_history(user_id, occurred_at DESC);
CREATE INDEX idx_login_history_attempt_date ON login_history(attempted_username, occurred_at DESC);
CREATE INDEX idx_reversal_original ON transaction_reversals(original_transaction_id);
CREATE INDEX idx_reversal_date ON transaction_reversals(reversed_at DESC);
CREATE INDEX idx_beneficiary_customer_status ON beneficiaries(customer_id, status, updated_at DESC);
CREATE INDEX idx_beneficiary_source ON beneficiaries(source_account_id, status);
CREATE UNIQUE INDEX uk_beneficiary_active ON beneficiaries(
  CASE WHEN status='ACTIVE' THEN customer_id END,
  CASE WHEN status='ACTIVE' THEN source_account_id END,
  CASE WHEN status='ACTIVE' THEN beneficiary_account_id END
);
CREATE INDEX idx_kyc_customer_status ON customer_kyc(customer_id, status, updated_at DESC);
CREATE INDEX idx_kyc_status_date ON customer_kyc(status, submitted_at DESC);
CREATE INDEX idx_deposit_scheme_status ON deposit_schemes(status, scheme_type);
CREATE INDEX idx_certificate_customer_status ON deposit_certificates(customer_id, status, maturity_date);
CREATE INDEX idx_certificate_account ON deposit_certificates(account_id, status);
CREATE INDEX idx_certificate_maturity ON deposit_certificates(maturity_date, status);
CREATE INDEX idx_notifications_user_read ON notifications(user_id,is_read,created_at DESC);
CREATE INDEX idx_service_requests_customer ON service_requests(customer_id,status,updated_at DESC);
CREATE INDEX idx_service_requests_branch ON service_requests(branch_id,status,updated_at DESC);
CREATE INDEX idx_service_requests_assignee ON service_requests(assigned_to,status,updated_at DESC);

-- ===== database/sql/03_insert_sample_data.sql =====
-- Deterministic fictional reference data for the Smart Banking Management System.
-- No application users, passwords, customers, accounts, or ledger rows are created here.

MERGE INTO bank_profile b
USING (SELECT 1 profile_id FROM dual) s
   ON (b.profile_id = s.profile_id)
WHEN MATCHED THEN UPDATE SET
  bank_name='Smart Bank Limited', short_name='Smart Bank',
  head_office_address='DEMO Head Office, Motijheel, Dhaka',
  support_phone='DEMO-09600-00000', support_email='support@example.test',
  website='https://smartbank.example.test', swift_code='DEMO-SBMS-000',
  currency='BDT', status='ACTIVE', updated_at=SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT(
  profile_id,bank_name,short_name,head_office_address,support_phone,
  support_email,website,swift_code,currency,status
) VALUES(
  1,'Smart Bank Limited','Smart Bank','DEMO Head Office, Motijheel, Dhaka',
  'DEMO-09600-00000','support@example.test','https://smartbank.example.test',
  'DEMO-SBMS-000','BDT','ACTIVE'
);

MERGE INTO branches b USING (SELECT 'HO-001' branch_code FROM dual) s ON (b.branch_code=s.branch_code)
WHEN MATCHED THEN UPDATE SET branch_name='Smart Bank Head Office',city='Dhaka',address='DEMO Head Office, Motijheel',phone='DEMO-02-0000',swift_code='DEMO-SBMS-HO',status='ACTIVE'
WHEN NOT MATCHED THEN INSERT(branch_code,branch_name,city,address,phone,swift_code) VALUES('HO-001','Smart Bank Head Office','Dhaka','DEMO Head Office, Motijheel','DEMO-02-0000','DEMO-SBMS-HO');
MERGE INTO branches b USING (SELECT 'DHK-001' branch_code FROM dual) s ON (b.branch_code=s.branch_code)
WHEN MATCHED THEN UPDATE SET branch_name='Dhanmondi Main Branch',city='Dhaka',address='DEMO Campus Road, Dhanmondi',phone='DEMO-02-0001',swift_code='DEMO-SBMS-001',status='ACTIVE'
WHEN NOT MATCHED THEN INSERT(branch_code,branch_name,city,address,phone,swift_code) VALUES('DHK-001','Dhanmondi Main Branch','Dhaka','DEMO Campus Road, Dhanmondi','DEMO-02-0001','DEMO-SBMS-001');
MERGE INTO branches b USING (SELECT 'UTT-001' branch_code FROM dual) s ON (b.branch_code=s.branch_code)
WHEN MATCHED THEN UPDATE SET branch_name='Uttara Branch',city='Dhaka',address='DEMO Sector 7, Uttara',phone='DEMO-02-0002',swift_code='DEMO-SBMS-002',status='ACTIVE'
WHEN NOT MATCHED THEN INSERT(branch_code,branch_name,city,address,phone,swift_code) VALUES('UTT-001','Uttara Branch','Dhaka','DEMO Sector 7, Uttara','DEMO-02-0002','DEMO-SBMS-002');
MERGE INTO branches b USING (SELECT 'CTG-001' branch_code FROM dual) s ON (b.branch_code=s.branch_code)
WHEN MATCHED THEN UPDATE SET branch_name='Agrabad Branch',city='Chattogram',address='DEMO Commercial Area, Agrabad',phone='DEMO-02-0003',swift_code='DEMO-SBMS-003',status='ACTIVE'
WHEN NOT MATCHED THEN INSERT(branch_code,branch_name,city,address,phone,swift_code) VALUES('CTG-001','Agrabad Branch','Chattogram','DEMO Commercial Area, Agrabad','DEMO-02-0003','DEMO-SBMS-003');
MERGE INTO branches b USING (SELECT 'CHP-001' branch_code FROM dual) s ON (b.branch_code=s.branch_code)
WHEN MATCHED THEN UPDATE SET branch_name='Chandpur Branch',city='Chandpur',address='DEMO River Road, Chandpur',phone='DEMO-02-0004',swift_code='DEMO-SBMS-004',status='ACTIVE'
WHEN NOT MATCHED THEN INSERT(branch_code,branch_name,city,address,phone,swift_code) VALUES('CHP-001','Chandpur Branch','Chandpur','DEMO River Road, Chandpur','DEMO-02-0004','DEMO-SBMS-004');

MERGE INTO account_types t USING (SELECT 'Savings' type_name FROM dual) s ON (t.type_name=s.type_name)
WHEN MATCHED THEN UPDATE SET description='Personal savings account',min_balance=1000,annual_interest_rate=3.5,status='ACTIVE'
WHEN NOT MATCHED THEN INSERT(type_name,description,min_balance,annual_interest_rate) VALUES('Savings','Personal savings account',1000,3.5);
MERGE INTO account_types t USING (SELECT 'Current' type_name FROM dual) s ON (t.type_name=s.type_name)
WHEN MATCHED THEN UPDATE SET description='Everyday current account',min_balance=5000,annual_interest_rate=0,status='ACTIVE'
WHEN NOT MATCHED THEN INSERT(type_name,description,min_balance,annual_interest_rate) VALUES('Current','Everyday current account',5000,0);
MERGE INTO account_types t USING (SELECT 'Student' type_name FROM dual) s ON (t.type_name=s.type_name)
WHEN MATCHED THEN UPDATE SET description='Fictional student account',min_balance=500,annual_interest_rate=2.5,status='ACTIVE'
WHEN NOT MATCHED THEN INSERT(type_name,description,min_balance,annual_interest_rate) VALUES('Student','Fictional student account',500,2.5);
MERGE INTO account_types t USING (SELECT 'Business' type_name FROM dual) s ON (t.type_name=s.type_name)
WHEN MATCHED THEN UPDATE SET description='Fictional small business account',min_balance=10000,annual_interest_rate=1.25,status='ACTIVE'
WHEN NOT MATCHED THEN INSERT(type_name,description,min_balance,annual_interest_rate) VALUES('Business','Fictional small business account',10000,1.25);
MERGE INTO account_types t USING (SELECT 'Salary' type_name FROM dual) s ON (t.type_name=s.type_name)
WHEN MATCHED THEN UPDATE SET description='Fictional salary account',min_balance=1000,annual_interest_rate=2,status='ACTIVE'
WHEN NOT MATCHED THEN INSERT(type_name,description,min_balance,annual_interest_rate) VALUES('Salary','Fictional salary account',1000,2);

INSERT INTO deposit_schemes(scheme_code,scheme_name,scheme_type,minimum_amount,maximum_amount,minimum_months,maximum_months,annual_profit_rate,calculation_method,payment_frequency,tax_percentage,early_withdrawal_rate)
SELECT 'FD-SIMPLE','Classroom Fixed Deposit','FIXED_DEPOSIT',10000,5000000,3,36,8,'SIMPLE','AT_MATURITY',10,3 FROM dual WHERE NOT EXISTS (SELECT 1 FROM deposit_schemes WHERE scheme_code='FD-SIMPLE');
INSERT INTO deposit_schemes(scheme_code,scheme_name,scheme_type,minimum_amount,maximum_amount,minimum_months,maximum_months,annual_profit_rate,calculation_method,payment_frequency,tax_percentage,early_withdrawal_rate)
SELECT 'FD-COMPOUND','Monthly Compound Deposit','MONTHLY_PROFIT',10000,5000000,6,36,8.5,'MONTHLY_COMPOUND','AT_MATURITY',10,3 FROM dual WHERE NOT EXISTS (SELECT 1 FROM deposit_schemes WHERE scheme_code='FD-COMPOUND');
INSERT INTO deposit_schemes(scheme_code,scheme_name,scheme_type,minimum_amount,maximum_amount,minimum_months,maximum_months,annual_profit_rate,calculation_method,payment_frequency,tax_percentage,early_withdrawal_rate)
SELECT 'DPS-EDU','Educational DPS','DPS',500,100000,12,36,7.25,'MONTHLY_COMPOUND','RECURRING',5,2 FROM dual WHERE NOT EXISTS (SELECT 1 FROM deposit_schemes WHERE scheme_code='DPS-EDU');
INSERT INTO deposit_schemes(scheme_code,scheme_name,scheme_type,minimum_amount,maximum_amount,minimum_months,maximum_months,annual_profit_rate,calculation_method,payment_frequency,tax_percentage,early_withdrawal_rate,student_only)
SELECT 'STUDENT-SAVE','Student Savings Estimate','STUDENT_SAVINGS',1000,100000,3,24,6,'SIMPLE','AT_MATURITY',0,2,'Y' FROM dual WHERE NOT EXISTS (SELECT 1 FROM deposit_schemes WHERE scheme_code='STUDENT-SAVE');

COMMIT;

-- ===== database/sql/04_views.sql =====
CREATE OR REPLACE VIEW vw_customer_account_summary AS
SELECT c.customer_id,c.first_name||' '||c.last_name customer_name,a.account_id,a.account_number,
       t.type_name,b.branch_name,a.balance,a.currency,a.status,a.open_date
FROM customers c JOIN accounts a ON a.customer_id=c.customer_id
JOIN account_types t ON t.account_type_id=a.account_type_id JOIN branches b ON b.branch_id=a.branch_id;

CREATE OR REPLACE VIEW vw_branch_performance AS
SELECT b.branch_id,b.branch_code,b.branch_name,
       COUNT(DISTINCT a.account_id) total_accounts,COUNT(DISTINCT a.customer_id) total_customers,
       NVL(SUM(CASE WHEN a.status<>'CLOSED' THEN a.balance ELSE 0 END),0) total_balance
FROM branches b LEFT JOIN accounts a ON a.branch_id=b.branch_id GROUP BY b.branch_id,b.branch_code,b.branch_name;

CREATE OR REPLACE VIEW vw_account_transaction_summary AS
SELECT a.account_id,a.account_number,COUNT(t.transaction_id) transaction_count,
       NVL(SUM(CASE WHEN t.transaction_type IN('DEPOSIT','TRANSFER_CREDIT','LOAN_DISBURSEMENT') THEN t.amount ELSE 0 END),0) total_credit,
       NVL(SUM(CASE WHEN t.transaction_type IN('WITHDRAWAL','TRANSFER_DEBIT','LOAN_PAYMENT') THEN t.amount ELSE 0 END),0) total_debit
FROM accounts a LEFT JOIN transactions t ON t.account_id=a.account_id GROUP BY a.account_id,a.account_number;

CREATE OR REPLACE VIEW vw_loan_summary AS
SELECT l.loan_id,l.loan_number,c.first_name||' '||c.last_name customer_name,lt.type_name,
       l.requested_amount,l.approved_amount,l.monthly_installment,l.outstanding_balance,l.status,l.application_date
FROM loans l JOIN customers c ON c.customer_id=l.customer_id JOIN loan_types lt ON lt.loan_type_id=l.loan_type_id;

CREATE OR REPLACE VIEW vw_daily_transaction_totals AS
SELECT TRUNC(transaction_date) transaction_day,transaction_type,COUNT(*) transaction_count,SUM(amount) total_amount
FROM transactions WHERE status='SUCCESS' GROUP BY TRUNC(transaction_date),transaction_type;

CREATE OR REPLACE VIEW vw_pending_loan_applications AS
SELECT l.loan_id,l.loan_number,l.customer_id,c.first_name||' '||c.last_name customer_name,
       lt.type_name,l.requested_amount,l.term_months,l.application_date,a.branch_id
FROM loans l JOIN customers c ON c.customer_id=l.customer_id JOIN loan_types lt ON lt.loan_type_id=l.loan_type_id
JOIN accounts a ON a.account_id=l.disbursement_account_id WHERE l.status='PENDING';

CREATE OR REPLACE VIEW vw_account_statement AS
SELECT t.transaction_id,t.account_id,t.reference_no,t.transaction_type,t.amount,t.previous_balance,t.new_balance running_balance,
       t.status,t.transaction_date,
       CASE WHEN t.transaction_type IN ('DEPOSIT','TRANSFER_CREDIT','LOAN_DISBURSEMENT','REVERSAL_CREDIT') THEN t.amount ELSE 0 END credit,
       CASE WHEN t.transaction_type IN ('WITHDRAWAL','TRANSFER_DEBIT','LOAN_PAYMENT','REVERSAL_DEBIT') THEN t.amount ELSE 0 END debit
FROM transactions t;

CREATE OR REPLACE VIEW vw_deposit_certificate_reminders AS
SELECT d.certificate_id,d.certificate_number,d.customer_id,d.account_id,d.maturity_date,
       d.expected_maturity_amount,d.status,s.scheme_name,
       CASE WHEN d.status='MATURED' OR d.maturity_date < TRUNC(SYSDATE) THEN 'ALREADY_MATURED'
            WHEN d.maturity_date <= TRUNC(SYSDATE)+7 THEN 'WITHIN_7_DAYS'
            WHEN EXTRACT(MONTH FROM d.maturity_date)=EXTRACT(MONTH FROM SYSDATE)
             AND EXTRACT(YEAR FROM d.maturity_date)=EXTRACT(YEAR FROM SYSDATE) THEN 'THIS_MONTH'
            ELSE 'FUTURE' END reminder_category
FROM deposit_certificates d JOIN deposit_schemes s ON s.scheme_id=d.scheme_id
WHERE d.status IN ('QUOTATION','ACTIVE','MATURED');

-- ===== database/sql/07_functions.sql =====
CREATE OR REPLACE FUNCTION fn_get_account_balance(p_account_number IN VARCHAR2) RETURN NUMBER IS
  v_balance accounts.balance%TYPE;
BEGIN
  SELECT balance INTO v_balance FROM accounts WHERE account_number = p_account_number;
  RETURN v_balance;
EXCEPTION WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20001, 'Account not found.');
END;
/

CREATE OR REPLACE FUNCTION fn_total_customer_balance(p_customer_id IN NUMBER) RETURN NUMBER IS
  v_total NUMBER(15,2);
BEGIN
  SELECT NVL(SUM(balance), 0) INTO v_total FROM accounts WHERE customer_id = p_customer_id AND status <> 'CLOSED';
  RETURN v_total;
END;
/

CREATE OR REPLACE FUNCTION fn_calculate_emi(p_principal IN NUMBER, p_annual_rate IN NUMBER, p_months IN NUMBER) RETURN NUMBER IS
  v_rate NUMBER;
BEGIN
  IF p_principal <= 0 OR p_annual_rate < 0 OR p_months <= 0 THEN RAISE_APPLICATION_ERROR(-20002, 'Invalid EMI inputs.'); END IF;
  IF p_annual_rate = 0 THEN RETURN ROUND(p_principal / p_months, 2); END IF;
  v_rate := p_annual_rate / 1200;
  RETURN ROUND(p_principal * v_rate * POWER(1 + v_rate, p_months) / (POWER(1 + v_rate, p_months) - 1), 2);
END;
/

CREATE OR REPLACE FUNCTION fn_generate_account_number RETURN VARCHAR2 IS
BEGIN
  RETURN '10' || TO_CHAR(SYSDATE, 'YYMMDD') || LPAD(seq_business_reference.NEXTVAL, 8, '0');
END;
/

CREATE OR REPLACE FUNCTION fn_generate_loan_number RETURN VARCHAR2 IS
BEGIN
  RETURN 'LN' || TO_CHAR(SYSDATE, 'YYMMDD') || LPAD(seq_business_reference.NEXTVAL, 8, '0');
END;
/

-- ===== database/sql/11_packages.sql =====
CREATE OR REPLACE PACKAGE pkg_banking_operations AS
  PROCEDURE open_account(p_customer_id NUMBER, p_branch_id NUMBER, p_account_type_id NUMBER, p_initial_deposit NUMBER, p_processed_by NUMBER, p_account_number OUT VARCHAR2);
  PROCEDURE deposit(p_account_number VARCHAR2, p_amount NUMBER, p_processed_by NUMBER, p_reference OUT VARCHAR2);
  PROCEDURE withdraw(p_account_number VARCHAR2, p_amount NUMBER, p_processed_by NUMBER, p_reference OUT VARCHAR2);
  PROCEDURE transfer_funds(p_from_account VARCHAR2, p_to_account VARCHAR2, p_amount NUMBER, p_processed_by NUMBER, p_owner_customer_id NUMBER, p_reference OUT VARCHAR2);
  PROCEDURE change_status(p_account_id NUMBER, p_status VARCHAR2);
  PROCEDURE reverse_transaction(p_transaction_id NUMBER, p_reversed_by NUMBER, p_reason VARCHAR2, p_reference OUT VARCHAR2);
  FUNCTION get_available_balance(p_account_number VARCHAR2) RETURN NUMBER;
END pkg_banking_operations;
/

CREATE OR REPLACE PACKAGE BODY pkg_banking_operations AS
  FUNCTION reference(p_prefix VARCHAR2) RETURN VARCHAR2 IS
  BEGIN RETURN p_prefix || TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3') || LPAD(seq_business_reference.NEXTVAL,6,'0'); END;

  PROCEDURE assert_amount(p_amount NUMBER) IS
  BEGIN IF p_amount IS NULL OR p_amount <= 0 THEN RAISE_APPLICATION_ERROR(-20010,'Amount must be greater than zero.'); END IF; END;

  PROCEDURE open_account(
    p_customer_id NUMBER,
    p_branch_id NUMBER,
    p_account_type_id NUMBER,
    p_initial_deposit NUMBER,
    p_processed_by NUMBER,
    p_account_number OUT VARCHAR2
  ) IS
    v_min NUMBER(15,2);
    v_customer NUMBER;
    v_branch NUMBER;
    v_type NUMBER;
    v_account_id NUMBER;
    v_initial_reference VARCHAR2(50);
  BEGIN
    SELECT COUNT(*)
      INTO v_customer
      FROM customers
     WHERE customer_id = p_customer_id
       AND status = 'ACTIVE';

    SELECT COUNT(*)
      INTO v_branch
      FROM branches
     WHERE branch_id = p_branch_id
       AND status = 'ACTIVE';

    SELECT COUNT(*), MAX(min_balance)
      INTO v_type, v_min
      FROM account_types
     WHERE account_type_id = p_account_type_id
       AND status = 'ACTIVE';

    IF v_customer = 0 THEN
      RAISE_APPLICATION_ERROR(-20011, 'Active customer not found.');
    END IF;

    IF v_branch = 0 THEN
      RAISE_APPLICATION_ERROR(-20012, 'Active branch not found.');
    END IF;

    IF v_type = 0 THEN
      RAISE_APPLICATION_ERROR(-20013, 'Active account type not found.');
    END IF;

    IF NVL(p_initial_deposit, 0) < v_min THEN
      RAISE_APPLICATION_ERROR(
        -20014,
        'Initial deposit is below the minimum balance.'
      );
    END IF;

    p_account_number := fn_generate_account_number();

    INSERT INTO accounts(
      account_number,
      customer_id,
      branch_id,
      account_type_id,
      balance
    )
    VALUES(
      p_account_number,
      p_customer_id,
      p_branch_id,
      p_account_type_id,
      NVL(p_initial_deposit, 0)
    )
    RETURNING account_id INTO v_account_id;

    IF NVL(p_initial_deposit, 0) > 0 THEN
      -- Generate the reference in PL/SQL before using it in SQL.
      v_initial_reference := reference('DEP');

      INSERT INTO transactions(
        account_id,
        transaction_type,
        amount,
        previous_balance,
        new_balance,
        reference_no,
        description,
        processed_by
      )
      VALUES(
        v_account_id,
        'DEPOSIT',
        p_initial_deposit,
        0,
        p_initial_deposit,
        v_initial_reference,
        'Initial deposit',
        p_processed_by
      );
    END IF;
  END;

  PROCEDURE deposit(p_account_number VARCHAR2, p_amount NUMBER, p_processed_by NUMBER, p_reference OUT VARCHAR2) IS
    v_id NUMBER; v_old NUMBER(15,2); v_status VARCHAR2(12);
  BEGIN
    SAVEPOINT deposit_start;
    assert_amount(p_amount);
    SELECT account_id,balance,status INTO v_id,v_old,v_status FROM accounts WHERE account_number=p_account_number FOR UPDATE;
    IF v_status <> 'ACTIVE' THEN RAISE_APPLICATION_ERROR(-20015,'Account is not active.'); END IF;
    p_reference:=reference('DEP');
    UPDATE accounts SET balance=v_old+p_amount,last_transaction_date=SYSTIMESTAMP WHERE account_id=v_id;
    INSERT INTO transactions(account_id,transaction_type,amount,previous_balance,new_balance,reference_no,description,processed_by)
    VALUES(v_id,'DEPOSIT',p_amount,v_old,v_old+p_amount,p_reference,'Cash deposit',p_processed_by);
  EXCEPTION WHEN NO_DATA_FOUND THEN ROLLBACK TO deposit_start; RAISE_APPLICATION_ERROR(-20016,'Account not found.'); WHEN OTHERS THEN ROLLBACK TO deposit_start; RAISE;
  END;

  PROCEDURE withdraw(p_account_number VARCHAR2, p_amount NUMBER, p_processed_by NUMBER, p_reference OUT VARCHAR2) IS
    v_id NUMBER; v_old NUMBER(15,2); v_min NUMBER(15,2); v_status VARCHAR2(12);
  BEGIN
    SAVEPOINT withdrawal_start;
    assert_amount(p_amount);
    SELECT a.account_id,a.balance,a.status,t.min_balance INTO v_id,v_old,v_status,v_min FROM accounts a JOIN account_types t ON t.account_type_id=a.account_type_id WHERE a.account_number=p_account_number FOR UPDATE OF a.balance;
    IF v_status <> 'ACTIVE' THEN RAISE_APPLICATION_ERROR(-20017,'Account is not active.'); END IF;
    IF v_old-p_amount < v_min THEN RAISE_APPLICATION_ERROR(-20018,'Insufficient available balance after minimum balance.'); END IF;
    p_reference:=reference('WDL'); UPDATE accounts SET balance=v_old-p_amount,last_transaction_date=SYSTIMESTAMP WHERE account_id=v_id;
    INSERT INTO transactions(account_id,transaction_type,amount,previous_balance,new_balance,reference_no,description,processed_by)
    VALUES(v_id,'WITHDRAWAL',p_amount,v_old,v_old-p_amount,p_reference,'Cash withdrawal',p_processed_by);
  EXCEPTION WHEN NO_DATA_FOUND THEN ROLLBACK TO withdrawal_start; RAISE_APPLICATION_ERROR(-20019,'Account not found.'); WHEN OTHERS THEN ROLLBACK TO withdrawal_start; RAISE;
  END;

  PROCEDURE transfer_funds(p_from_account VARCHAR2, p_to_account VARCHAR2, p_amount NUMBER, p_processed_by NUMBER, p_owner_customer_id NUMBER, p_reference OUT VARCHAR2) IS
    v_from_id NUMBER; v_to_id NUMBER; v_from_old NUMBER(15,2); v_to_old NUMBER(15,2); v_min NUMBER(15,2); v_from_status VARCHAR2(12); v_to_status VARCHAR2(12); v_owner NUMBER; v_debit NUMBER; v_credit NUMBER;
  BEGIN
    SAVEPOINT transfer_start;
    assert_amount(p_amount);
    IF p_from_account=p_to_account THEN RAISE_APPLICATION_ERROR(-20020,'Source and destination must differ.'); END IF;
    -- Lock in account-id order to reduce deadlock risk between concurrent transfers.
    SELECT account_id INTO v_from_id FROM accounts WHERE account_number=p_from_account;
    SELECT account_id INTO v_to_id FROM accounts WHERE account_number=p_to_account;
    FOR r IN (SELECT account_id FROM accounts WHERE account_id IN(v_from_id,v_to_id) ORDER BY account_id FOR UPDATE) LOOP NULL; END LOOP;
    SELECT a.balance,a.status,a.customer_id,t.min_balance INTO v_from_old,v_from_status,v_owner,v_min FROM accounts a JOIN account_types t ON t.account_type_id=a.account_type_id WHERE a.account_id=v_from_id;
    SELECT balance,status INTO v_to_old,v_to_status FROM accounts WHERE account_id=v_to_id;
    IF v_from_status<>'ACTIVE' OR v_to_status<>'ACTIVE' THEN RAISE_APPLICATION_ERROR(-20021,'Both accounts must be active.'); END IF;
    IF p_owner_customer_id IS NOT NULL AND v_owner<>p_owner_customer_id THEN RAISE_APPLICATION_ERROR(-20022,'Source account is not owned by this customer.'); END IF;
    IF v_from_old-p_amount<v_min THEN RAISE_APPLICATION_ERROR(-20023,'Insufficient available balance after minimum balance.'); END IF;
    p_reference:=reference('TRF');
    UPDATE accounts SET balance=v_from_old-p_amount,last_transaction_date=SYSTIMESTAMP WHERE account_id=v_from_id;
    UPDATE accounts SET balance=v_to_old+p_amount,last_transaction_date=SYSTIMESTAMP WHERE account_id=v_to_id;
    INSERT INTO transactions(account_id,related_account_id,transaction_type,amount,previous_balance,new_balance,reference_no,description,processed_by)
    VALUES(v_from_id,v_to_id,'TRANSFER_DEBIT',p_amount,v_from_old,v_from_old-p_amount,p_reference||'-D','Fund transfer debit',p_processed_by) RETURNING transaction_id INTO v_debit;
    INSERT INTO transactions(account_id,related_account_id,transaction_type,amount,previous_balance,new_balance,reference_no,description,processed_by)
    VALUES(v_to_id,v_from_id,'TRANSFER_CREDIT',p_amount,v_to_old,v_to_old+p_amount,p_reference||'-C','Fund transfer credit',p_processed_by) RETURNING transaction_id INTO v_credit;
    INSERT INTO fund_transfers(transfer_reference,from_account_id,to_account_id,amount,debit_transaction_id,credit_transaction_id,initiated_by)
    VALUES(p_reference,v_from_id,v_to_id,p_amount,v_debit,v_credit,p_processed_by);
  EXCEPTION WHEN NO_DATA_FOUND THEN ROLLBACK TO transfer_start; RAISE_APPLICATION_ERROR(-20024,'One or both accounts were not found.'); WHEN OTHERS THEN ROLLBACK TO transfer_start; RAISE;
  END;

  PROCEDURE change_status(p_account_id NUMBER,p_status VARCHAR2) IS v_balance NUMBER;
  BEGIN
    IF p_status NOT IN ('ACTIVE','FROZEN','CLOSED') THEN RAISE_APPLICATION_ERROR(-20025,'Invalid account status.'); END IF;
    SELECT balance INTO v_balance FROM accounts WHERE account_id=p_account_id FOR UPDATE;
    IF p_status='CLOSED' AND v_balance<>0 THEN RAISE_APPLICATION_ERROR(-20026,'A non-zero account cannot be closed.'); END IF;
    UPDATE accounts SET status=p_status,close_date=CASE WHEN p_status='CLOSED' THEN SYSDATE ELSE NULL END WHERE account_id=p_account_id;
  EXCEPTION WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20027,'Account not found.'); END;

  PROCEDURE reverse_transaction(p_transaction_id NUMBER, p_reversed_by NUMBER, p_reason VARCHAR2, p_reference OUT VARCHAR2) IS
    v_account_id NUMBER; v_amount NUMBER(15,2); v_type VARCHAR2(30); v_status VARCHAR2(12);
    v_account_number VARCHAR2(24); v_balance NUMBER(15,2); v_new_balance NUMBER(15,2);
    v_reversal_type VARCHAR2(30); v_reversal_id NUMBER;
  BEGIN
    SAVEPOINT reversal_start;
    IF TRIM(p_reason) IS NULL THEN RAISE_APPLICATION_ERROR(-20029,'Reversal reason is required.'); END IF;
    SELECT t.account_id,t.amount,t.transaction_type,t.status,a.account_number
      INTO v_account_id,v_amount,v_type,v_status,v_account_number
      FROM transactions t JOIN accounts a ON a.account_id=t.account_id
     WHERE t.transaction_id=p_transaction_id FOR UPDATE;
    IF v_status <> 'SUCCESS' THEN RAISE_APPLICATION_ERROR(-20030,'Only successful transactions can be reversed.'); END IF;
    IF v_type NOT IN ('DEPOSIT','WITHDRAWAL') THEN RAISE_APPLICATION_ERROR(-20031,'Only deposits and withdrawals can be reversed.'); END IF;
    SELECT COUNT(*) INTO v_reversal_id FROM transaction_reversals WHERE original_transaction_id=p_transaction_id;
    IF v_reversal_id > 0 THEN RAISE_APPLICATION_ERROR(-20032,'This transaction has already been reversed.'); END IF;
    SELECT balance,status INTO v_balance,v_status FROM accounts WHERE account_id=v_account_id FOR UPDATE;
    IF v_status <> 'ACTIVE' THEN RAISE_APPLICATION_ERROR(-20035,'Account is not active.'); END IF;
    IF v_type='DEPOSIT' THEN
      v_new_balance:=v_balance-v_amount; v_reversal_type:='REVERSAL_DEBIT';
      IF v_new_balance < 0 THEN RAISE_APPLICATION_ERROR(-20033,'Reversal would create a negative balance.'); END IF;
    ELSE
      v_new_balance:=v_balance+v_amount; v_reversal_type:='REVERSAL_CREDIT';
    END IF;
    p_reference:=reference('REV');
    UPDATE accounts SET balance=v_new_balance,last_transaction_date=SYSTIMESTAMP WHERE account_id=v_account_id;
    INSERT INTO transactions(account_id,transaction_type,amount,previous_balance,new_balance,reference_no,description,processed_by)
    VALUES(v_account_id,v_reversal_type,v_amount,v_balance,v_new_balance,p_reference,'Reversal of transaction '||p_transaction_id,p_reversed_by)
    RETURNING transaction_id INTO v_reversal_id;
    INSERT INTO transaction_reversals(original_transaction_id,reversal_transaction_id,reason,reversed_by)
    VALUES(p_transaction_id,v_reversal_id,TRIM(p_reason),p_reversed_by);
    INSERT INTO audit_log(table_name,record_id,action_name,action_by,new_summary)
    VALUES('TRANSACTIONS',p_transaction_id,'REVERSAL',NVL(TO_CHAR(p_reversed_by),'SYSTEM'),'reversal_reference='||p_reference||';reason='||TRIM(p_reason));
  EXCEPTION WHEN NO_DATA_FOUND THEN ROLLBACK TO reversal_start; RAISE_APPLICATION_ERROR(-20034,'Original transaction not found.');
    WHEN OTHERS THEN ROLLBACK TO reversal_start; RAISE;
  END;

  FUNCTION get_available_balance(p_account_number VARCHAR2) RETURN NUMBER IS v_balance NUMBER; v_min NUMBER;
  BEGIN SELECT a.balance,t.min_balance INTO v_balance,v_min FROM accounts a JOIN account_types t ON t.account_type_id=a.account_type_id WHERE a.account_number=p_account_number AND a.status='ACTIVE'; RETURN GREATEST(v_balance-v_min,0);
  EXCEPTION WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20028,'Active account not found.'); END;
END pkg_banking_operations;
/

CREATE OR REPLACE PACKAGE pkg_loan_operations AS
  PROCEDURE apply_for_loan(p_customer_id NUMBER,p_loan_type_id NUMBER,p_account_id NUMBER,p_amount NUMBER,p_term_months NUMBER,p_loan_number OUT VARCHAR2);
  PROCEDURE approve_loan(p_loan_id NUMBER,p_approved_amount NUMBER,p_reviewer_employee_id NUMBER,p_processed_by NUMBER,p_reference OUT VARCHAR2);
  PROCEDURE reject_loan(p_loan_id NUMBER,p_reason VARCHAR2,p_reviewer_employee_id NUMBER);
  PROCEDURE record_payment(p_loan_id NUMBER,p_account_number VARCHAR2,p_amount NUMBER,p_received_by NUMBER,p_reference OUT VARCHAR2);
  FUNCTION remaining_installments(p_loan_id NUMBER) RETURN NUMBER;
END pkg_loan_operations;
/

CREATE OR REPLACE PACKAGE BODY pkg_loan_operations AS
  PROCEDURE apply_for_loan(p_customer_id NUMBER,p_loan_type_id NUMBER,p_account_id NUMBER,p_amount NUMBER,p_term_months NUMBER,p_loan_number OUT VARCHAR2) IS v_min NUMBER;v_max NUMBER;v_rate NUMBER;v_tmin NUMBER;v_tmax NUMBER;v_owner NUMBER;
  BEGIN SELECT min_amount,max_amount,annual_interest_rate,min_term_months,max_term_months INTO v_min,v_max,v_rate,v_tmin,v_tmax FROM loan_types WHERE loan_type_id=p_loan_type_id AND status='ACTIVE'; SELECT customer_id INTO v_owner FROM accounts WHERE account_id=p_account_id AND status='ACTIVE';
    IF v_owner<>p_customer_id THEN RAISE_APPLICATION_ERROR(-20100,'Disbursement account is not owned by customer.'); END IF;
    IF p_amount NOT BETWEEN v_min AND v_max OR p_term_months NOT BETWEEN v_tmin AND v_tmax THEN RAISE_APPLICATION_ERROR(-20101,'Amount or term is outside loan type limits.'); END IF;
    p_loan_number:=fn_generate_loan_number(); INSERT INTO loans(loan_number,customer_id,loan_type_id,disbursement_account_id,requested_amount,interest_rate,term_months) VALUES(p_loan_number,p_customer_id,p_loan_type_id,p_account_id,p_amount,v_rate,p_term_months);
  EXCEPTION WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20102,'Loan type or account not found.'); END;
  PROCEDURE approve_loan(p_loan_id NUMBER,p_approved_amount NUMBER,p_reviewer_employee_id NUMBER,p_processed_by NUMBER,p_reference OUT VARCHAR2) IS v_status VARCHAR2(20);v_requested NUMBER;v_account NUMBER;v_old NUMBER;v_emi NUMBER;v_total NUMBER;v_term NUMBER;
  BEGIN SAVEPOINT loan_approval; SELECT status,requested_amount,disbursement_account_id,term_months INTO v_status,v_requested,v_account,v_term FROM loans WHERE loan_id=p_loan_id FOR UPDATE; IF v_status<>'PENDING' THEN RAISE_APPLICATION_ERROR(-20103,'Loan has already been decided.'); END IF; IF p_approved_amount<=0 OR p_approved_amount>v_requested THEN RAISE_APPLICATION_ERROR(-20104,'Approved amount is invalid.'); END IF;
    SELECT balance INTO v_old FROM accounts WHERE account_id=v_account AND status='ACTIVE' FOR UPDATE; SELECT fn_calculate_emi(p_approved_amount,interest_rate,term_months) INTO v_emi FROM loans WHERE loan_id=p_loan_id; v_total:=ROUND(v_emi*v_term,2); p_reference:='LND'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3')||seq_business_reference.NEXTVAL;
    UPDATE accounts SET balance=v_old+p_approved_amount,last_transaction_date=SYSTIMESTAMP WHERE account_id=v_account;
    INSERT INTO transactions(account_id,transaction_type,amount,previous_balance,new_balance,reference_no,description,processed_by) VALUES(v_account,'LOAN_DISBURSEMENT',p_approved_amount,v_old,v_old+p_approved_amount,p_reference,'Loan disbursement',p_processed_by);
    UPDATE loans SET approved_amount=p_approved_amount,monthly_installment=v_emi,total_repayable=v_total,outstanding_balance=v_total,status='ACTIVE',reviewed_by=p_reviewer_employee_id,reviewed_at=SYSTIMESTAMP,start_date=SYSDATE,end_date=ADD_MONTHS(SYSDATE,term_months) WHERE loan_id=p_loan_id;
  EXCEPTION WHEN NO_DATA_FOUND THEN ROLLBACK TO loan_approval; RAISE_APPLICATION_ERROR(-20105,'Pending loan or active account not found.'); WHEN OTHERS THEN ROLLBACK TO loan_approval; RAISE; END;
  PROCEDURE reject_loan(p_loan_id NUMBER,p_reason VARCHAR2,p_reviewer_employee_id NUMBER) IS v_status VARCHAR2(20); BEGIN IF TRIM(p_reason) IS NULL THEN RAISE_APPLICATION_ERROR(-20106,'Rejection reason is required.'); END IF; SELECT status INTO v_status FROM loans WHERE loan_id=p_loan_id FOR UPDATE; IF v_status<>'PENDING' THEN RAISE_APPLICATION_ERROR(-20107,'Loan has already been decided.'); END IF; UPDATE loans SET status='REJECTED',rejection_reason=TRIM(p_reason),reviewed_by=p_reviewer_employee_id,reviewed_at=SYSTIMESTAMP WHERE loan_id=p_loan_id; EXCEPTION WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20108,'Loan not found.'); END;
  PROCEDURE record_payment(p_loan_id NUMBER,p_account_number VARCHAR2,p_amount NUMBER,p_received_by NUMBER,p_reference OUT VARCHAR2) IS
    v_out NUMBER;
    v_status VARCHAR2(20);
    v_account NUMBER;
    v_old NUMBER;
    v_tx NUMBER;
    v_new NUMBER;
    v_loan_customer NUMBER;
    v_account_customer NUMBER;
  BEGIN
    SAVEPOINT loan_payment;
    IF p_amount IS NULL OR p_amount<=0 THEN RAISE_APPLICATION_ERROR(-20109,'Payment must be positive.'); END IF;
    SELECT outstanding_balance,status,customer_id
      INTO v_out,v_status,v_loan_customer
      FROM loans WHERE loan_id=p_loan_id FOR UPDATE;
    IF v_status<>'ACTIVE' THEN RAISE_APPLICATION_ERROR(-20110,'Only active loans accept payment.'); END IF;
    IF p_amount>v_out THEN RAISE_APPLICATION_ERROR(-20111,'Payment exceeds outstanding balance.'); END IF;
    SELECT account_id,balance,customer_id
      INTO v_account,v_old,v_account_customer
      FROM accounts WHERE account_number=p_account_number AND status='ACTIVE' FOR UPDATE;
    IF v_account_customer<>v_loan_customer THEN RAISE_APPLICATION_ERROR(-20115,'Payment account does not belong to the loan customer.'); END IF;
    IF p_amount>v_old THEN RAISE_APPLICATION_ERROR(-20112,'Insufficient account balance.'); END IF;
    v_new:=v_out-p_amount;
    p_reference:='LNP'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3')||seq_business_reference.NEXTVAL;
    UPDATE accounts SET balance=v_old-p_amount,last_transaction_date=SYSTIMESTAMP WHERE account_id=v_account;
    INSERT INTO transactions(account_id,transaction_type,amount,previous_balance,new_balance,reference_no,description,processed_by)
    VALUES(v_account,'LOAN_PAYMENT',p_amount,v_old,v_old-p_amount,p_reference,'Loan payment',p_received_by)
    RETURNING transaction_id INTO v_tx;
    INSERT INTO loan_payments(loan_id,account_id,transaction_id,amount,previous_outstanding,new_outstanding,received_by)
    VALUES(p_loan_id,v_account,v_tx,p_amount,v_out,v_new,p_received_by);
    UPDATE loans SET outstanding_balance=v_new,status=CASE WHEN v_new=0 THEN 'COMPLETED' ELSE 'ACTIVE' END WHERE loan_id=p_loan_id;
  EXCEPTION WHEN NO_DATA_FOUND THEN ROLLBACK TO loan_payment; RAISE_APPLICATION_ERROR(-20113,'Loan or account not found.'); WHEN OTHERS THEN ROLLBACK TO loan_payment; RAISE; END;
  FUNCTION remaining_installments(p_loan_id NUMBER) RETURN NUMBER IS v_out NUMBER;v_emi NUMBER; BEGIN SELECT outstanding_balance,monthly_installment INTO v_out,v_emi FROM loans WHERE loan_id=p_loan_id; RETURN CASE WHEN v_out=0 THEN 0 ELSE CEIL(v_out/v_emi) END; EXCEPTION WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20114,'Loan not found.'); END;
END pkg_loan_operations;
/

-- ===== database/sql/08_procedures.sql =====
-- Compatibility wrappers for classroom demonstrations. New application code calls packages.
CREATE OR REPLACE PROCEDURE pr_deposit(p_account_number VARCHAR2,p_amount NUMBER,p_processed_by NUMBER,p_reference OUT VARCHAR2) AS
BEGIN pkg_banking_operations.deposit(p_account_number,p_amount,p_processed_by,p_reference); END;
/
CREATE OR REPLACE PROCEDURE pr_withdraw(p_account_number VARCHAR2,p_amount NUMBER,p_processed_by NUMBER,p_reference OUT VARCHAR2) AS
BEGIN pkg_banking_operations.withdraw(p_account_number,p_amount,p_processed_by,p_reference); END;
/
CREATE OR REPLACE PROCEDURE pr_transfer(p_from_account VARCHAR2,p_to_account VARCHAR2,p_amount NUMBER,p_processed_by NUMBER,p_owner_customer_id NUMBER,p_reference OUT VARCHAR2) AS
BEGIN pkg_banking_operations.transfer_funds(p_from_account,p_to_account,p_amount,p_processed_by,p_owner_customer_id,p_reference); END;
/

-- ===== database/sql/10_triggers.sql =====
CREATE OR REPLACE FUNCTION fn_audit_actor RETURN VARCHAR2 IS
BEGIN
  RETURN COALESCE(
    SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'),
    SYS_CONTEXT('USERENV', 'SESSION_USER')
  );
END;
/

CREATE OR REPLACE TRIGGER trg_audit_customer_update
AFTER UPDATE ON customers
FOR EACH ROW
BEGIN
  INSERT INTO audit_log(table_name,record_id,action_name,action_by,old_summary,new_summary)
  VALUES(
    'CUSTOMERS', :NEW.customer_id, 'UPDATE', fn_audit_actor(),
    'status='||:OLD.status||';phone='||:OLD.phone,
    'status='||:NEW.status||';phone='||:NEW.phone
  );
END;
/

CREATE OR REPLACE TRIGGER trg_audit_account_status
AFTER UPDATE OF status ON accounts
FOR EACH ROW
WHEN (OLD.status <> NEW.status)
BEGIN
  INSERT INTO audit_log(table_name,record_id,action_name,action_by,old_summary,new_summary)
  VALUES('ACCOUNTS',:NEW.account_id,'STATUS_CHANGE',fn_audit_actor(),'status='||:OLD.status,'status='||:NEW.status);
END;
/

CREATE OR REPLACE TRIGGER trg_audit_loan_status
AFTER UPDATE OF status ON loans
FOR EACH ROW
WHEN (OLD.status <> NEW.status)
BEGIN
  INSERT INTO audit_log(table_name,record_id,action_name,action_by,old_summary,new_summary)
  VALUES('LOANS',:NEW.loan_id,'STATUS_CHANGE',fn_audit_actor(),'status='||:OLD.status,'status='||:NEW.status);
END;
/

CREATE OR REPLACE TRIGGER trg_protect_financial_history
BEFORE UPDATE OR DELETE ON transactions
BEGIN
  RAISE_APPLICATION_ERROR(-20200,'Financial transaction history cannot be updated or deleted. Use a controlled reversal entry.');
END;
/

CREATE OR REPLACE TRIGGER trg_validate_user_staff_code
BEFORE INSERT OR UPDATE OF employee_id, staff_code, role ON users
FOR EACH ROW
DECLARE
  v_employee_code employees.employee_code%TYPE;
BEGIN
  :NEW.username := LOWER(TRIM(:NEW.username));
  :NEW.role := UPPER(TRIM(:NEW.role));
  IF :NEW.staff_code IS NOT NULL THEN
    :NEW.staff_code := UPPER(TRIM(:NEW.staff_code));
  END IF;

  IF :NEW.role IN ('ADMIN', 'MANAGER', 'EMPLOYEE') THEN
    IF :NEW.employee_id IS NULL OR :NEW.customer_id IS NOT NULL THEN
      RAISE_APPLICATION_ERROR(-20309, 'Staff users must link to an employee and cannot link to a customer.');
    END IF;
    SELECT employee_code INTO v_employee_code FROM employees WHERE employee_id = :NEW.employee_id AND status = 'ACTIVE';
    IF :NEW.staff_code IS NULL OR UPPER(TRIM(:NEW.staff_code)) <> UPPER(TRIM(v_employee_code)) THEN
      RAISE_APPLICATION_ERROR(-20310, 'Staff code must match the linked active employee code.');
    END IF;
  ELSIF :NEW.role = 'CUSTOMER' THEN
    IF :NEW.customer_id IS NULL OR :NEW.employee_id IS NOT NULL OR :NEW.staff_code IS NOT NULL THEN
      RAISE_APPLICATION_ERROR(-20311, 'Customer users must link only to a customer.');
    END IF;
  ELSE
    RAISE_APPLICATION_ERROR(-20313, 'Unsupported application role.');
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20312, 'Staff users must link to an existing employee.');
END;
/

-- ===== database/sql/12_viva_demo_data.sql =====
-- Deterministic fictional university demonstration data.
-- No users or passwords are created here; run the runtime seed for staff logins.

MERGE INTO loan_types t USING (SELECT 'Personal Loan' type_name FROM dual) s ON (t.type_name=s.type_name)
WHEN MATCHED THEN UPDATE SET short_description='Flexible personal finance',detailed_description='Educational reducing-balance product for household needs.',minimum_annual_income=300000,processing_fee_percentage=1,eligibility_summary='Stable income and verified KYC',required_document_summary='DEMO identity and income evidence',interest_method='REDUCING_BALANCE',min_amount=50000,max_amount=1000000,annual_interest_rate=11.5,min_term_months=6,max_term_months=60,status='ACTIVE'
WHEN NOT MATCHED THEN INSERT(type_name,short_description,detailed_description,minimum_annual_income,processing_fee_percentage,eligibility_summary,required_document_summary,interest_method,min_amount,max_amount,annual_interest_rate,min_term_months,max_term_months) VALUES('Personal Loan','Flexible personal finance','Educational reducing-balance product for household needs.',300000,1,'Stable income and verified KYC','DEMO identity and income evidence','REDUCING_BALANCE',50000,1000000,11.5,6,60);
MERGE INTO loan_types t USING (SELECT 'Home Loan' type_name FROM dual) s ON (t.type_name=s.type_name)
WHEN MATCHED THEN UPDATE SET short_description='Home purchase finance',detailed_description='Educational long-term product for an eligible home purchase.',minimum_annual_income=600000,processing_fee_percentage=.5,eligibility_summary='Stable income, address and KYC',required_document_summary='DEMO identity, income and property evidence',interest_method='REDUCING_BALANCE',min_amount=500000,max_amount=10000000,annual_interest_rate=8.75,min_term_months=12,max_term_months=240,status='ACTIVE'
WHEN NOT MATCHED THEN INSERT(type_name,short_description,detailed_description,minimum_annual_income,processing_fee_percentage,eligibility_summary,required_document_summary,interest_method,min_amount,max_amount,annual_interest_rate,min_term_months,max_term_months) VALUES('Home Loan','Home purchase finance','Educational long-term product for an eligible home purchase.',600000,.5,'Stable income, address and KYC','DEMO identity, income and property evidence','REDUCING_BALANCE',500000,10000000,8.75,12,240);
INSERT INTO loan_types(type_name,short_description,detailed_description,minimum_annual_income,processing_fee_percentage,eligibility_summary,required_document_summary,interest_method,min_amount,max_amount,annual_interest_rate,min_term_months,max_term_months)
SELECT 'Education Loan','Study support','Educational financing for tuition and learning expenses.',240000,0.25,'Admission evidence and stable sponsor income','DEMO identity, admission and income evidence','REDUCING_BALANCE',25000,1500000,9.25,6,84 FROM dual WHERE NOT EXISTS (SELECT 1 FROM loan_types WHERE type_name='Education Loan');
INSERT INTO loan_types(type_name,short_description,detailed_description,minimum_annual_income,processing_fee_percentage,eligibility_summary,required_document_summary,interest_method,min_amount,max_amount,annual_interest_rate,min_term_months,max_term_months)
SELECT 'Small Business Loan','Startup and working capital','Educational working-capital finance for small enterprises.',360000,1.25,'Operating history and verified cash flow','DEMO identity, trade evidence and cash-flow summary','REDUCING_BALANCE',100000,2500000,12.25,6,72 FROM dual WHERE NOT EXISTS (SELECT 1 FROM loan_types WHERE type_name='Small Business Loan');
INSERT INTO loan_types(type_name,short_description,detailed_description,minimum_annual_income,processing_fee_percentage,eligibility_summary,required_document_summary,interest_method,min_amount,max_amount,annual_interest_rate,min_term_months,max_term_months)
SELECT 'Vehicle Loan','Vehicle purchase finance','Educational vehicle finance with reducing-balance interest.',420000,0.75,'Stable income and verified vehicle quotation','DEMO identity, income and quotation evidence','REDUCING_BALANCE',150000,4000000,10.75,12,84 FROM dual WHERE NOT EXISTS (SELECT 1 FROM loan_types WHERE type_name='Vehicle Loan');
INSERT INTO loan_types(type_name,short_description,detailed_description,minimum_annual_income,processing_fee_percentage,eligibility_summary,required_document_summary,interest_method,min_amount,max_amount,annual_interest_rate,min_term_months,max_term_months)
SELECT 'Emergency Loan','Short-term emergency support','Educational short-term support subject to review.',180000,1.5,'Verified customer and urgent need evidence','DEMO identity and supporting explanation','FLAT_RATE',25000,300000,13.5,3,24 FROM dual WHERE NOT EXISTS (SELECT 1 FROM loan_types WHERE type_name='Emergency Loan');

INSERT INTO deposit_schemes(scheme_code,scheme_name,scheme_type,minimum_amount,maximum_amount,minimum_months,maximum_months,annual_profit_rate,calculation_method,payment_frequency,tax_percentage,early_withdrawal_rate)
SELECT 'FD-PREMIUM','Premium Classroom Deposit','FIXED_DEPOSIT',50000,10000000,6,60,9,'SIMPLE','AT_MATURITY',10,4 FROM dual WHERE NOT EXISTS (SELECT 1 FROM deposit_schemes WHERE scheme_code='FD-PREMIUM');
INSERT INTO deposit_schemes(scheme_code,scheme_name,scheme_type,minimum_amount,maximum_amount,minimum_months,maximum_months,annual_profit_rate,calculation_method,payment_frequency,tax_percentage,early_withdrawal_rate)
SELECT 'DPS-FLEX','Flexible Classroom DPS','DPS',1000,200000,12,60,7.75,'MONTHLY_COMPOUND','RECURRING',5,2 FROM dual WHERE NOT EXISTS (SELECT 1 FROM deposit_schemes WHERE scheme_code='DPS-FLEX');
INSERT INTO deposit_schemes(scheme_code,scheme_name,scheme_type,minimum_amount,maximum_amount,minimum_months,maximum_months,annual_profit_rate,calculation_method,payment_frequency,tax_percentage,early_withdrawal_rate)
SELECT 'SENIOR-SAVE','Senior Classroom Savings','SENIOR_CITIZEN',1000,2000000,3,36,7.5,'SIMPLE','AT_MATURITY',5,2 FROM dual WHERE NOT EXISTS (SELECT 1 FROM deposit_schemes WHERE scheme_code='SENIOR-SAVE');

MERGE INTO employees e USING (SELECT 'A-ID-001' employee_code FROM dual) s ON (e.employee_code=s.employee_code)
WHEN MATCHED THEN UPDATE SET branch_id=(SELECT branch_id FROM branches WHERE branch_code='HO-001'),first_name='Mohammad',last_name='Mrinmoy',national_id='DEMO-EMP-NID-001',job_title='System Administrator',email='mohammad.mrinmoy@example.test',phone='DEMO-018-0101',salary=120000,status='ACTIVE'
WHEN NOT MATCHED THEN INSERT(branch_id,employee_code,first_name,last_name,national_id,job_title,email,phone,salary) SELECT branch_id,'A-ID-001','Mohammad','Mrinmoy','DEMO-EMP-NID-001','System Administrator','mohammad.mrinmoy@example.test','DEMO-018-0101',120000 FROM branches WHERE branch_code='HO-001';
MERGE INTO employees e USING (SELECT 'A-ID-002' employee_code FROM dual) s ON (e.employee_code=s.employee_code)
WHEN MATCHED THEN UPDATE SET branch_id=(SELECT branch_id FROM branches WHERE branch_code='HO-001'),first_name='Sirajum',last_name='Monira',national_id='DEMO-EMP-NID-002',job_title='System Administrator',email='sirajum.monira@example.test',phone='DEMO-018-0102',salary=118000,status='ACTIVE'
WHEN NOT MATCHED THEN INSERT(branch_id,employee_code,first_name,last_name,national_id,job_title,email,phone,salary) SELECT branch_id,'A-ID-002','Sirajum','Monira','DEMO-EMP-NID-002','System Administrator','sirajum.monira@example.test','DEMO-018-0102',118000 FROM branches WHERE branch_code='HO-001';
MERGE INTO employees e USING (SELECT 'A-ID-003' employee_code FROM dual) s ON (e.employee_code=s.employee_code)
WHEN MATCHED THEN UPDATE SET branch_id=(SELECT branch_id FROM branches WHERE branch_code='HO-001'),first_name='Ashik',last_name='Uz-zaman',national_id='DEMO-EMP-NID-003',job_title='System Administrator',email='ashik.uzzaman@example.test',phone='DEMO-018-0103',salary=116000,status='ACTIVE'
WHEN NOT MATCHED THEN INSERT(branch_id,employee_code,first_name,last_name,national_id,job_title,email,phone,salary) SELECT branch_id,'A-ID-003','Ashik','Uz-zaman','DEMO-EMP-NID-003','System Administrator','ashik.uzzaman@example.test','DEMO-018-0103',116000 FROM branches WHERE branch_code='HO-001';
MERGE INTO employees e USING (SELECT 'A-ID-004' employee_code FROM dual) s ON (e.employee_code=s.employee_code)
WHEN MATCHED THEN UPDATE SET branch_id=(SELECT branch_id FROM branches WHERE branch_code='HO-001'),first_name='Ikhteir',last_name='Asif',national_id='DEMO-EMP-NID-004',job_title='System Administrator',email='ikhteir.asif@example.test',phone='DEMO-018-0104',salary=114000,status='ACTIVE'
WHEN NOT MATCHED THEN INSERT(branch_id,employee_code,first_name,last_name,national_id,job_title,email,phone,salary) SELECT branch_id,'A-ID-004','Ikhteir','Asif','DEMO-EMP-NID-004','System Administrator','ikhteir.asif@example.test','DEMO-018-0104',114000 FROM branches WHERE branch_code='HO-001';
MERGE INTO employees e USING (SELECT 'M-ID-001' employee_code FROM dual) s ON (e.employee_code=s.employee_code)
WHEN MATCHED THEN UPDATE SET branch_id=(SELECT branch_id FROM branches WHERE branch_code='DHK-001'),first_name='Mayen',last_name='Majumder',national_id='DEMO-EMP-NID-005',job_title='Project Supervisor / Branch Manager',email='mayen.majumder@example.test',phone='DEMO-018-0105',salary=90000,status='ACTIVE'
WHEN NOT MATCHED THEN INSERT(branch_id,employee_code,first_name,last_name,national_id,job_title,email,phone,salary) SELECT branch_id,'M-ID-001','Mayen','Majumder','DEMO-EMP-NID-005','Project Supervisor / Branch Manager','mayen.majumder@example.test','DEMO-018-0105',90000 FROM branches WHERE branch_code='DHK-001';
MERGE INTO employees e USING (SELECT 'E-ID-001' employee_code FROM dual) s ON (e.employee_code=s.employee_code)
WHEN MATCHED THEN UPDATE SET branch_id=(SELECT branch_id FROM branches WHERE branch_code='DHK-001'),first_name='Mashrur',last_name='Hasan',national_id='DEMO-EMP-NID-006',job_title='Senior Banking Officer',email='mashrur.hasan@example.test',phone='DEMO-018-0106',salary=55000,status='ACTIVE'
WHEN NOT MATCHED THEN INSERT(branch_id,employee_code,first_name,last_name,national_id,job_title,email,phone,salary) SELECT branch_id,'E-ID-001','Mashrur','Hasan','DEMO-EMP-NID-006','Senior Banking Officer','mashrur.hasan@example.test','DEMO-018-0106',55000 FROM branches WHERE branch_code='DHK-001';
MERGE INTO employees e USING (SELECT 'E-ID-002' employee_code FROM dual) s ON (e.employee_code=s.employee_code)
WHEN MATCHED THEN UPDATE SET branch_id=(SELECT branch_id FROM branches WHERE branch_code='UTT-001'),first_name='Risha',last_name='Khan',national_id='DEMO-EMP-NID-007',job_title='Customer Service Officer',email='risha.khan@example.test',phone='DEMO-018-0107',salary=52000,status='ACTIVE'
WHEN NOT MATCHED THEN INSERT(branch_id,employee_code,first_name,last_name,national_id,job_title,email,phone,salary) SELECT branch_id,'E-ID-002','Risha','Khan','DEMO-EMP-NID-007','Customer Service Officer','risha.khan@example.test','DEMO-018-0107',52000 FROM branches WHERE branch_code='UTT-001';
MERGE INTO employees e USING (SELECT 'E-ID-003' employee_code FROM dual) s ON (e.employee_code=s.employee_code)
WHEN MATCHED THEN UPDATE SET branch_id=(SELECT branch_id FROM branches WHERE branch_code='CTG-001'),first_name='Samin',last_name='Hasan',national_id='DEMO-EMP-NID-008',job_title='Credit Officer',email='samin.hasan@example.test',phone='DEMO-018-0108',salary=56000,status='ACTIVE'
WHEN NOT MATCHED THEN INSERT(branch_id,employee_code,first_name,last_name,national_id,job_title,email,phone,salary) SELECT branch_id,'E-ID-003','Samin','Hasan','DEMO-EMP-NID-008','Credit Officer','samin.hasan@example.test','DEMO-018-0108',56000 FROM branches WHERE branch_code='CTG-001';
MERGE INTO employees e USING (SELECT 'E-ID-004' employee_code FROM dual) s ON (e.employee_code=s.employee_code)
WHEN MATCHED THEN UPDATE SET branch_id=(SELECT branch_id FROM branches WHERE branch_code='CHP-001'),first_name='Abrar',last_name='Karib',national_id='DEMO-EMP-NID-009',job_title='Service Officer',email='abrar.karib@example.test',phone='DEMO-018-0109',salary=51000,status='ACTIVE'
WHEN NOT MATCHED THEN INSERT(branch_id,employee_code,first_name,last_name,national_id,job_title,email,phone,salary) SELECT branch_id,'E-ID-004','Abrar','Karib','DEMO-EMP-NID-009','Service Officer','abrar.karib@example.test','DEMO-018-0109',51000 FROM branches WHERE branch_code='CHP-001';
MERGE INTO employees e USING (SELECT 'E-ID-005' employee_code FROM dual) s ON (e.employee_code=s.employee_code)
WHEN MATCHED THEN UPDATE SET branch_id=(SELECT branch_id FROM branches WHERE branch_code='DHK-001'),first_name='Rakib',last_name='Hasan',national_id='DEMO-EMP-NID-010',job_title='Operations Officer',email='rakib.hasan@example.test',phone='DEMO-018-0110',salary=53000,status='ACTIVE'
WHEN NOT MATCHED THEN INSERT(branch_id,employee_code,first_name,last_name,national_id,job_title,email,phone,salary) SELECT branch_id,'E-ID-005','Rakib','Hasan','DEMO-EMP-NID-010','Operations Officer','rakib.hasan@example.test','DEMO-018-0110',53000 FROM branches WHERE branch_code='DHK-001';
MERGE INTO employees e USING (SELECT 'E-ID-006' employee_code FROM dual) s ON (e.employee_code=s.employee_code)
WHEN MATCHED THEN UPDATE SET branch_id=(SELECT branch_id FROM branches WHERE branch_code='UTT-001'),first_name='Prapto',last_name='Sorkar',national_id='DEMO-EMP-NID-011',job_title='Account Officer',email='prapto.sorkar@example.test',phone='DEMO-018-0111',salary=50000,status='ACTIVE'
WHEN NOT MATCHED THEN INSERT(branch_id,employee_code,first_name,last_name,national_id,job_title,email,phone,salary) SELECT branch_id,'E-ID-006','Prapto','Sorkar','DEMO-EMP-NID-011','Account Officer','prapto.sorkar@example.test','DEMO-018-0111',50000 FROM branches WHERE branch_code='UTT-001';
MERGE INTO employees e USING (SELECT 'E-ID-007' employee_code FROM dual) s ON (e.employee_code=s.employee_code)
WHEN MATCHED THEN UPDATE SET branch_id=(SELECT branch_id FROM branches WHERE branch_code='CTG-001'),first_name='Sayba',last_name='Tasnim',national_id='DEMO-EMP-NID-012',job_title='Loan Officer',email='sayba.tasnim@example.test',phone='DEMO-018-0112',salary=54000,status='ACTIVE'
WHEN NOT MATCHED THEN INSERT(branch_id,employee_code,first_name,last_name,national_id,job_title,email,phone,salary) SELECT branch_id,'E-ID-007','Sayba','Tasnim','DEMO-EMP-NID-012','Loan Officer','sayba.tasnim@example.test','DEMO-018-0112',54000 FROM branches WHERE branch_code='CTG-001';
MERGE INTO employees e USING (SELECT 'E-ID-008' employee_code FROM dual) s ON (e.employee_code=s.employee_code)
WHEN MATCHED THEN UPDATE SET branch_id=(SELECT branch_id FROM branches WHERE branch_code='CHP-001'),first_name='Tasnia',last_name='Suborno',national_id='DEMO-EMP-NID-013',job_title='Customer Support Officer',email='tasnia.suborno@example.test',phone='DEMO-018-0113',salary=50000,status='ACTIVE'
WHEN NOT MATCHED THEN INSERT(branch_id,employee_code,first_name,last_name,national_id,job_title,email,phone,salary) SELECT branch_id,'E-ID-008','Tasnia','Suborno','DEMO-EMP-NID-013','Customer Support Officer','tasnia.suborno@example.test','DEMO-018-0113',50000 FROM branches WHERE branch_code='CHP-001';

DECLARE
  TYPE t_name_list IS TABLE OF VARCHAR2(80); names t_name_list := t_name_list('Nusrat Jahan','Shamim Hasan','Geko Topadar','Chypher Hasan','Ryna Jahan','Jet Bagom','Chember Rahman','Astra Tabbassum','Raze Akter','Skye Tasnim','Clove Hasan','Tasfia Neon','Abul Phenix','Sage Mostofa','Mohammad Yoru','Jahanggir Harbor','Alongir Tejo','Luna Kabir','Orion Sultana','Nova Rahman','Farhan Noor','Meher Afroz','Tanim Chowdhury','Priya Saha','Zayan Ahmed');
  v_first VARCHAR2(50); v_last VARCHAR2(50); v_space PLS_INTEGER;
BEGIN
  FOR i IN 1..names.COUNT LOOP
    v_space := INSTR(names(i),' '); v_first := SUBSTR(names(i),1,v_space-1); v_last := SUBSTR(names(i),v_space+1);
    INSERT INTO customers(first_name,last_name,date_of_birth,gender,phone,email,national_id,address,occupation,annual_income,marital_status,status)
    SELECT v_first,v_last,ADD_MONTHS(DATE '1985-01-01',i*7),'O','DEMO-CUST-'||LPAD(i,4,'0'),LOWER(REPLACE(names(i),' ','-'))||'@example.test','DEMO-NID-'||LPAD(i,4,'0'),'DEMO Address '||LPAD(i,2,'0'),'Demo Occupation '||LPAD(i,2,'0'),300000+i*25000,CASE WHEN MOD(i,2)=0 THEN 'MARRIED' ELSE 'SINGLE' END,'ACTIVE' FROM dual
    WHERE NOT EXISTS (SELECT 1 FROM customers WHERE national_id='DEMO-NID-'||LPAD(i,4,'0'));
  END LOOP;
END;
/

INSERT INTO customer_kyc(customer_id,status,document_type,document_reference)
SELECT c.customer_id,CASE WHEN MOD(c.customer_id,4)=0 THEN 'VERIFIED' ELSE 'PENDING' END,'NID','DEMO-KYC-'||c.national_id FROM customers c WHERE c.national_id LIKE 'DEMO-NID-%' AND NOT EXISTS (SELECT 1 FROM customer_kyc k WHERE k.customer_id=c.customer_id);

DECLARE
  v_number VARCHAR2(24); v_type NUMBER; v_branch NUMBER; v_amount NUMBER; v_existing_account_count NUMBER;
BEGIN
  SELECT account_type_id INTO v_type FROM account_types WHERE type_name='Savings';
  FOR c IN (SELECT c.customer_id,ROW_NUMBER() OVER (ORDER BY c.customer_id) rn FROM customers c WHERE c.national_id LIKE 'DEMO-NID-%') LOOP
    SELECT COUNT(*) INTO v_existing_account_count FROM accounts a WHERE a.customer_id=c.customer_id;
    IF v_existing_account_count = 0 THEN
      SELECT branch_id INTO v_branch FROM branches WHERE branch_code=CASE MOD(c.rn-1,4) WHEN 0 THEN 'DHK-001' WHEN 1 THEN 'UTT-001' WHEN 2 THEN 'CTG-001' ELSE 'CHP-001' END;
      v_amount := 18000 + c.rn*250;
      pkg_banking_operations.open_account(c.customer_id,v_branch,v_type,v_amount,NULL,v_number);
    END IF;
  END LOOP;
END;
/

DECLARE v_number VARCHAR2(24); v_type NUMBER; v_branch NUMBER;
BEGIN
  SELECT account_type_id INTO v_type FROM account_types WHERE type_name='Current';
  FOR c IN (SELECT customer_id,ROW_NUMBER() OVER (ORDER BY customer_id) rn FROM customers WHERE national_id LIKE 'DEMO-NID-%') LOOP
    SELECT branch_id INTO v_branch FROM accounts WHERE customer_id=c.customer_id AND ROWNUM=1;
    pkg_banking_operations.open_account(c.customer_id,v_branch,v_type,5000,NULL,v_number);
  END LOOP;
END;
/

DECLARE v_ref VARCHAR2(100); v_count NUMBER := 0;
BEGIN
  FOR a IN (SELECT account_number FROM (SELECT account_number,ROW_NUMBER() OVER (ORDER BY account_id) rn FROM accounts) WHERE rn <= 30) LOOP
    pkg_banking_operations.deposit(a.account_number,750,NULL,v_ref); v_count := v_count+1;
  END LOOP;
  FOR a IN (SELECT account_number FROM (SELECT account_number,ROW_NUMBER() OVER (ORDER BY account_id) rn FROM accounts) WHERE rn <= 15) LOOP
    pkg_banking_operations.withdraw(a.account_number,250,NULL,v_ref); v_count := v_count+1;
  END LOOP;
END;
/

DECLARE v_ref VARCHAR2(100); v_owner NUMBER;
BEGIN
  FOR pair IN (SELECT from_account,to_account,owner_customer_id FROM (
    SELECT a.account_number from_account,LEAD(a.account_number) OVER (ORDER BY a.account_id) to_account,a.customer_id owner_customer_id,ROW_NUMBER() OVER (ORDER BY a.account_id) rn FROM accounts a) WHERE rn <= 10 AND to_account IS NOT NULL) LOOP
    pkg_banking_operations.transfer_funds(pair.from_account,pair.to_account,300,NULL,pair.owner_customer_id,v_ref);
  END LOOP;
END;
/

DECLARE v_number VARCHAR2(40); v_type NUMBER; v_emp NUMBER; v_count NUMBER := 0;
BEGIN
  SELECT employee_id INTO v_emp FROM employees WHERE employee_code='M-ID-001';
  FOR a IN (SELECT account_id,customer_id,account_number,ROW_NUMBER() OVER (ORDER BY account_id) rn FROM accounts WHERE ROWNUM <= 10) LOOP
    SELECT loan_type_id INTO v_type FROM (SELECT loan_type_id,ROW_NUMBER() OVER (ORDER BY loan_type_id) rn FROM loan_types WHERE status='ACTIVE') WHERE rn=1+MOD(a.rn-1,6);
    pkg_loan_operations.apply_for_loan(a.customer_id,v_type,a.account_id,50000+MOD(a.rn,5)*10000,12,v_number);
  END LOOP;
  FOR l IN (SELECT loan_id,requested_amount FROM (SELECT loan_id,requested_amount,ROW_NUMBER() OVER (ORDER BY loan_id) rn FROM loans WHERE status='PENDING') WHERE rn <= 4) LOOP
    pkg_loan_operations.approve_loan(l.loan_id,l.requested_amount,v_emp,NULL,v_number);
  END LOOP;
  FOR l IN (SELECT loan_id FROM (SELECT loan_id,ROW_NUMBER() OVER (ORDER BY loan_id) rn FROM loans WHERE status='PENDING') WHERE rn <= 2) LOOP
    pkg_loan_operations.reject_loan(l.loan_id,'Demo affordability review',v_emp);
  END LOOP;
  FOR l IN (SELECT loan_id,account_number FROM (SELECT l.loan_id,a.account_number,ROW_NUMBER() OVER (ORDER BY l.loan_id) rn FROM loans l JOIN accounts a ON a.account_id=l.disbursement_account_id WHERE l.status='ACTIVE') WHERE rn <= 2) LOOP
    pkg_loan_operations.record_payment(l.loan_id,l.account_number,1000,NULL,v_number);
  END LOOP;
END;
/

INSERT INTO beneficiaries(customer_id,source_account_id,beneficiary_account_id,nickname)
SELECT a.customer_id,a.account_id,b.account_id,'Demo beneficiary '||a.customer_id FROM accounts a JOIN accounts b ON b.account_id=a.account_id+1 WHERE a.customer_id IN (SELECT customer_id FROM customers WHERE national_id LIKE 'DEMO-NID-%') AND a.account_id<>b.account_id AND NOT EXISTS (SELECT 1 FROM beneficiaries x WHERE x.customer_id=a.customer_id AND x.source_account_id=a.account_id AND x.beneficiary_account_id=b.account_id);

INSERT INTO deposit_certificates(certificate_number,customer_id,account_id,scheme_id,principal_amount,annual_profit_rate,duration_months,calculation_method,tax_percentage,expected_gross_profit,expected_tax,expected_net_profit,expected_maturity_amount,opening_date,maturity_date,status)
SELECT 'DEMO-QUOTE-'||LPAD(c.customer_id,6,'0'),c.customer_id,a.account_id,s.scheme_id,25000,s.annual_profit_rate,12,s.calculation_method,s.tax_percentage,ROUND(25000*s.annual_profit_rate/100,2),ROUND(25000*s.annual_profit_rate/100*s.tax_percentage/100,2),ROUND(25000*s.annual_profit_rate/100*(1-s.tax_percentage/100),2),ROUND(25000+25000*s.annual_profit_rate/100*(1-s.tax_percentage/100),2),TRUNC(SYSDATE),ADD_MONTHS(TRUNC(SYSDATE),12),'QUOTATION' FROM customers c JOIN accounts a ON a.customer_id=c.customer_id CROSS JOIN (SELECT * FROM deposit_schemes WHERE scheme_code='FD-SIMPLE') s WHERE c.national_id LIKE 'DEMO-NID-%' AND ROWNUM <= 8 AND NOT EXISTS (SELECT 1 FROM deposit_certificates d WHERE d.certificate_number='DEMO-QUOTE-'||LPAD(c.customer_id,6,'0'));

INSERT INTO service_requests(request_number,customer_id,branch_id,request_type,subject,description)
SELECT 'DEMO-SR-'||LPAD(c.customer_id,6,'0'),c.customer_id,a.branch_id,CASE MOD(c.customer_id,6) WHEN 0 THEN 'ACCOUNT_FREEZE' WHEN 1 THEN 'STATEMENT' WHEN 2 THEN 'PROFILE_HELP' WHEN 3 THEN 'BENEFICIARY_HELP' WHEN 4 THEN 'LOAN_INFORMATION' ELSE 'GENERAL_SUPPORT' END,'Demo service request','Fictional university demonstration request.' FROM customers c JOIN accounts a ON a.customer_id=c.customer_id WHERE c.national_id LIKE 'DEMO-NID-%' AND ROWNUM <= 10 AND NOT EXISTS (SELECT 1 FROM service_requests r WHERE r.request_number='DEMO-SR-'||LPAD(c.customer_id,6,'0'));
INSERT INTO audit_log(table_name,record_id,action_name,action_by,new_summary)
SELECT 'DEMO_DATA',c.customer_id,'VIVA_SEED','SYSTEM','Fictional university demonstration data'
FROM customers c
WHERE c.national_id LIKE 'DEMO-NID-%'
  AND ROWNUM <= 5
  AND NOT EXISTS (
    SELECT 1 FROM audit_log a
    WHERE a.table_name='DEMO_DATA' AND a.record_id=c.customer_id
      AND a.action_name='VIVA_SEED'
  );
COMMIT;
