-- Browser FreeSQL worksheet for a non-destructive upgrade of an existing Phase 1-3 schema.
-- It preserves customers, accounts, transactions and balances.

-- ===== database/worksheet/phase1_upgrade.sql =====
-- FreeSQL/SQL*Plus pasteable Phase 1 upgrade. Non-destructive; no passwords.
DECLARE
  PROCEDURE add_column(p_sql VARCHAR2) IS BEGIN EXECUTE IMMEDIATE p_sql; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1430,-2260) THEN RAISE; END IF; END;
  PROCEDURE add_index(p_sql VARCHAR2) IS BEGIN EXECUTE IMMEDIATE p_sql; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955,-1408) THEN RAISE; END IF; END;
BEGIN
  add_column('ALTER TABLE users ADD (must_change_password CHAR(1) DEFAULT ''N'' NOT NULL)');
  add_column('ALTER TABLE users ADD (account_locked CHAR(1) DEFAULT ''N'' NOT NULL)');
  add_column('ALTER TABLE users ADD (locked_at TIMESTAMP)');
  add_column('ALTER TABLE users ADD (password_changed_at TIMESTAMP)');
  add_column('ALTER TABLE users ADD (updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)');
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE users ADD CONSTRAINT ck_users_must_change CHECK (must_change_password IN (''Y'',''N''))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-2260,-2275) THEN RAISE; END IF; END;
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE users ADD CONSTRAINT ck_users_locked CHECK (account_locked IN (''Y'',''N''))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-2260,-2275) THEN RAISE; END IF; END;
  BEGIN EXECUTE IMMEDIATE 'CREATE TABLE login_history (login_history_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_login_history PRIMARY KEY,user_id NUMBER CONSTRAINT fk_login_history_user REFERENCES users(user_id),attempted_username VARCHAR2(50) NOT NULL,success_flag CHAR(1) NOT NULL CONSTRAINT ck_login_history_success CHECK (success_flag IN (''Y'',''N'')),event_type VARCHAR2(20) DEFAULT ''LOGIN'' NOT NULL,failure_reason VARCHAR2(100),occurred_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE<>-955 THEN RAISE; END IF; END;
  add_index('CREATE INDEX idx_users_username_lower ON users(LOWER(username))');
  add_index('CREATE INDEX idx_users_role_active ON users(role,is_active,account_locked)');
  add_index('CREATE INDEX idx_users_employee ON users(employee_id)');
  add_index('CREATE INDEX idx_login_history_user_date ON login_history(user_id,occurred_at DESC)');
  add_index('CREATE INDEX idx_login_history_attempt_date ON login_history(attempted_username,occurred_at DESC)');
  DBMS_OUTPUT.PUT_LINE('Phase 1 staff-login upgrade complete.');
END;
/
SELECT name,type,line,position,text FROM user_errors ORDER BY name,sequence;

-- ===== database/worksheet/phase2_upgrade.sql =====
-- Browser FreeSQL non-destructive Phase 2 upgrade.
-- Non-destructive Phase 2 upgrade. Run as the BANK_APP schema owner.
-- It preserves existing ledger rows and adds only compensating-ledger metadata,
-- customer tools, and supporting indexes.
DECLARE
  PROCEDURE exec_ignore(p_sql VARCHAR2, p_codes SYS.ODCINUMBERLIST) IS
    v_ignored BOOLEAN := FALSE;
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION WHEN OTHERS THEN
    FOR i IN 1..p_codes.COUNT LOOP IF SQLCODE=p_codes(i) THEN v_ignored:=TRUE; END IF; END LOOP;
    IF NOT v_ignored THEN RAISE; END IF;
  END;
BEGIN
  exec_ignore('ALTER TABLE transactions DROP CONSTRAINT ck_transaction_type', SYS.ODCINUMBERLIST(-2443));
  exec_ignore('ALTER TABLE transactions ADD CONSTRAINT ck_transaction_type CHECK (transaction_type IN (''DEPOSIT'',''WITHDRAWAL'',''TRANSFER_DEBIT'',''TRANSFER_CREDIT'',''LOAN_DISBURSEMENT'',''LOAN_PAYMENT'',''REVERSAL_DEBIT'',''REVERSAL_CREDIT''))', SYS.ODCINUMBERLIST(-2260,-2275));
  exec_ignore('CREATE TABLE transaction_reversals (reversal_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_transaction_reversals PRIMARY KEY,original_transaction_id NUMBER NOT NULL CONSTRAINT fk_reversal_original REFERENCES transactions(transaction_id),reversal_transaction_id NUMBER NOT NULL CONSTRAINT fk_reversal_transaction REFERENCES transactions(transaction_id),reason VARCHAR2(500) NOT NULL,reversed_by NUMBER CONSTRAINT fk_reversal_user REFERENCES users(user_id),reversed_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,status VARCHAR2(12) DEFAULT ''COMPLETED'' NOT NULL CONSTRAINT ck_reversal_status CHECK (status IN (''COMPLETED'',''FAILED'')),CONSTRAINT uk_reversal_original UNIQUE(original_transaction_id),CONSTRAINT uk_reversal_transaction UNIQUE(reversal_transaction_id))', SYS.ODCINUMBERLIST(-955));
  exec_ignore('CREATE TABLE user_preferences (user_id NUMBER CONSTRAINT pk_user_preferences PRIMARY KEY REFERENCES users(user_id),theme VARCHAR2(10) DEFAULT ''SYSTEM'' NOT NULL CONSTRAINT ck_preferences_theme CHECK (theme IN (''LIGHT'',''DARK'',''SYSTEM'')),rows_per_page NUMBER DEFAULT 20 NOT NULL CONSTRAINT ck_preferences_rows CHECK (rows_per_page BETWEEN 5 AND 100),currency_display VARCHAR2(3) DEFAULT ''BDT'' NOT NULL CONSTRAINT ck_preferences_currency CHECK (currency_display=''BDT''),notifications_enabled CHAR(1) DEFAULT ''Y'' NOT NULL CONSTRAINT ck_preferences_notifications CHECK (notifications_enabled IN (''Y'',''N'')),updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)', SYS.ODCINUMBERLIST(-955));
  exec_ignore('CREATE TABLE beneficiaries (beneficiary_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_beneficiaries PRIMARY KEY,customer_id NUMBER NOT NULL CONSTRAINT fk_beneficiary_customer REFERENCES customers(customer_id),source_account_id NUMBER NOT NULL CONSTRAINT fk_beneficiary_source REFERENCES accounts(account_id),beneficiary_account_id NUMBER NOT NULL CONSTRAINT fk_beneficiary_target REFERENCES accounts(account_id),nickname VARCHAR2(100) NOT NULL,status VARCHAR2(12) DEFAULT ''ACTIVE'' NOT NULL CONSTRAINT ck_beneficiary_status CHECK (status IN (''ACTIVE'',''INACTIVE'')),created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,CONSTRAINT ck_beneficiary_different CHECK (source_account_id<>beneficiary_account_id))', SYS.ODCINUMBERLIST(-955));
  exec_ignore('CREATE TABLE customer_kyc (kyc_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_customer_kyc PRIMARY KEY,customer_id NUMBER NOT NULL CONSTRAINT fk_kyc_customer REFERENCES customers(customer_id),document_type VARCHAR2(40),document_reference VARCHAR2(100),status VARCHAR2(12) DEFAULT ''PENDING'' NOT NULL CONSTRAINT ck_kyc_status CHECK (status IN (''PENDING'',''VERIFIED'',''REJECTED'')),submitted_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,reviewed_by NUMBER CONSTRAINT fk_kyc_reviewer REFERENCES users(user_id),reviewed_at TIMESTAMP,rejection_reason VARCHAR2(500),updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)', SYS.ODCINUMBERLIST(-955));
  exec_ignore('CREATE INDEX idx_reversal_original ON transaction_reversals(original_transaction_id)', SYS.ODCINUMBERLIST(-955,-1408));
  exec_ignore('CREATE INDEX idx_reversal_date ON transaction_reversals(reversed_at DESC)', SYS.ODCINUMBERLIST(-955,-1408));
  exec_ignore('CREATE INDEX idx_beneficiary_customer_status ON beneficiaries(customer_id,status,updated_at DESC)', SYS.ODCINUMBERLIST(-955,-1408));
  exec_ignore('CREATE INDEX idx_beneficiary_source ON beneficiaries(source_account_id,status)', SYS.ODCINUMBERLIST(-955,-1408));
  exec_ignore('CREATE UNIQUE INDEX uk_beneficiary_active ON beneficiaries(CASE WHEN status=''ACTIVE'' THEN customer_id END,CASE WHEN status=''ACTIVE'' THEN source_account_id END,CASE WHEN status=''ACTIVE'' THEN beneficiary_account_id END)', SYS.ODCINUMBERLIST(-955,-1408));
  exec_ignore('CREATE INDEX idx_kyc_customer_status ON customer_kyc(customer_id,status,updated_at DESC)', SYS.ODCINUMBERLIST(-955,-1408));
  exec_ignore('CREATE INDEX idx_kyc_status_date ON customer_kyc(status,submitted_at DESC)', SYS.ODCINUMBERLIST(-955,-1408));
  DBMS_OUTPUT.PUT_LINE('Phase 2 customer-tools upgrade complete.');
END;
/
SELECT name,type,line,position,text FROM user_errors ORDER BY name,sequence;
-- Recompile the maintained package/view sources after the DDL upgrade:

-- ===== database/migrations/003_deposit_profit_suite.sql =====
-- Non-destructive Phase 3 upgrade. Run as the BANK_APP schema owner.
-- This adds educational schemes/quotations only; it never posts money or changes balances.
DECLARE
  PROCEDURE exec_ignore(p_sql VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
  END;
BEGIN
  exec_ignore('CREATE TABLE deposit_schemes (scheme_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_deposit_schemes PRIMARY KEY,scheme_code VARCHAR2(20) NOT NULL CONSTRAINT uk_deposit_scheme_code UNIQUE,scheme_name VARCHAR2(100) NOT NULL CONSTRAINT uk_deposit_scheme_name UNIQUE,scheme_type VARCHAR2(30) NOT NULL CONSTRAINT ck_deposit_scheme_type CHECK (scheme_type IN (''FIXED_DEPOSIT'',''MONTHLY_PROFIT'',''DPS'',''SAVINGS_PROFIT'',''SENIOR_CITIZEN'',''STUDENT_SAVINGS'')),minimum_amount NUMBER(15,2) NOT NULL CONSTRAINT ck_deposit_scheme_min CHECK (minimum_amount > 0),maximum_amount NUMBER(15,2),minimum_months NUMBER NOT NULL,maximum_months NUMBER NOT NULL,annual_profit_rate NUMBER(7,4) NOT NULL CONSTRAINT ck_deposit_scheme_rate CHECK (annual_profit_rate BETWEEN 0 AND 100),calculation_method VARCHAR2(20) DEFAULT ''SIMPLE'' NOT NULL CONSTRAINT ck_deposit_scheme_method CHECK (calculation_method IN (''SIMPLE'',''MONTHLY_COMPOUND'')),payment_frequency VARCHAR2(20) DEFAULT ''AT_MATURITY'' NOT NULL CONSTRAINT ck_deposit_scheme_frequency CHECK (payment_frequency IN (''AT_MATURITY'',''MONTHLY'',''RECURRING'')),tax_percentage NUMBER(5,2) DEFAULT 0 NOT NULL CONSTRAINT ck_deposit_scheme_tax CHECK (tax_percentage BETWEEN 0 AND 100),early_withdrawal_rate NUMBER(7,4),senior_only CHAR(1) DEFAULT ''N'' NOT NULL,student_only CHAR(1) DEFAULT ''N'' NOT NULL,status VARCHAR2(12) DEFAULT ''ACTIVE'' NOT NULL,created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)');
  exec_ignore('CREATE TABLE deposit_certificates (certificate_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_deposit_certificates PRIMARY KEY,certificate_number VARCHAR2(40) NOT NULL CONSTRAINT uk_certificate_number UNIQUE,customer_id NUMBER NOT NULL CONSTRAINT fk_certificate_customer REFERENCES customers(customer_id),account_id NUMBER CONSTRAINT fk_certificate_account REFERENCES accounts(account_id),scheme_id NUMBER NOT NULL CONSTRAINT fk_certificate_scheme REFERENCES deposit_schemes(scheme_id),principal_amount NUMBER(15,2) NOT NULL,annual_profit_rate NUMBER(7,4) NOT NULL,duration_months NUMBER NOT NULL,calculation_method VARCHAR2(20) NOT NULL,tax_percentage NUMBER(5,2) DEFAULT 0 NOT NULL,expected_gross_profit NUMBER(15,2) NOT NULL,expected_tax NUMBER(15,2) NOT NULL,expected_net_profit NUMBER(15,2) NOT NULL,expected_maturity_amount NUMBER(15,2) NOT NULL,opening_date DATE NOT NULL,maturity_date DATE NOT NULL,status VARCHAR2(24) DEFAULT ''QUOTATION'' NOT NULL,created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)');
  exec_ignore('CREATE INDEX idx_deposit_scheme_status ON deposit_schemes(status,scheme_type)');
  exec_ignore('CREATE INDEX idx_certificate_customer_status ON deposit_certificates(customer_id,status,maturity_date)');
  exec_ignore('CREATE INDEX idx_certificate_account ON deposit_certificates(account_id,status)');
  exec_ignore('CREATE INDEX idx_certificate_maturity ON deposit_certificates(maturity_date,status)');
  exec_ignore('ALTER TABLE deposit_schemes ADD CONSTRAINT ck_deposit_scheme_type CHECK (scheme_type IN (''FIXED_DEPOSIT'',''MONTHLY_PROFIT'',''DPS'',''SAVINGS_PROFIT'',''SENIOR_CITIZEN'',''STUDENT_SAVINGS''))');
  exec_ignore('ALTER TABLE deposit_schemes ADD CONSTRAINT ck_deposit_scheme_rate CHECK (annual_profit_rate BETWEEN 0 AND 100)');
  exec_ignore('ALTER TABLE deposit_schemes ADD CONSTRAINT ck_deposit_scheme_method CHECK (calculation_method IN (''SIMPLE'',''MONTHLY_COMPOUND''))');
  exec_ignore('ALTER TABLE deposit_schemes ADD CONSTRAINT ck_deposit_scheme_frequency CHECK (payment_frequency IN (''AT_MATURITY'',''MONTHLY'',''RECURRING''))');
  exec_ignore('ALTER TABLE deposit_schemes ADD CONSTRAINT ck_deposit_scheme_tax CHECK (tax_percentage BETWEEN 0 AND 100)');
  exec_ignore('ALTER TABLE deposit_schemes ADD CONSTRAINT ck_deposit_scheme_senior CHECK (senior_only IN (''Y'',''N''))');
  exec_ignore('ALTER TABLE deposit_schemes ADD CONSTRAINT ck_deposit_scheme_student CHECK (student_only IN (''Y'',''N''))');
  exec_ignore('ALTER TABLE deposit_schemes ADD CONSTRAINT ck_deposit_scheme_status CHECK (status IN (''ACTIVE'',''INACTIVE''))');
  exec_ignore('ALTER TABLE deposit_schemes ADD CONSTRAINT ck_deposit_scheme_months CHECK (minimum_months > 0 AND maximum_months >= minimum_months)');
  exec_ignore('ALTER TABLE deposit_schemes ADD CONSTRAINT ck_deposit_scheme_max CHECK (maximum_amount IS NULL OR maximum_amount >= minimum_amount)');
  exec_ignore('ALTER TABLE deposit_certificates ADD CONSTRAINT ck_certificate_principal CHECK (principal_amount > 0)');
  exec_ignore('ALTER TABLE deposit_certificates ADD CONSTRAINT ck_certificate_rate CHECK (annual_profit_rate BETWEEN 0 AND 100)');
  exec_ignore('ALTER TABLE deposit_certificates ADD CONSTRAINT ck_certificate_duration CHECK (duration_months > 0)');
  exec_ignore('ALTER TABLE deposit_certificates ADD CONSTRAINT ck_certificate_method CHECK (calculation_method IN (''SIMPLE'',''MONTHLY_COMPOUND''))');
  exec_ignore('ALTER TABLE deposit_certificates ADD CONSTRAINT ck_certificate_tax CHECK (tax_percentage BETWEEN 0 AND 100)');
  exec_ignore('ALTER TABLE deposit_certificates ADD CONSTRAINT ck_certificate_status CHECK (status IN (''QUOTATION'',''ACTIVE'',''MATURED'',''CLOSED'',''PREMATURELY_CLOSED'',''BLOCKED''))');
  exec_ignore('ALTER TABLE deposit_certificates ADD CONSTRAINT ck_certificate_dates CHECK (maturity_date >= opening_date)');
  INSERT INTO deposit_schemes(scheme_code,scheme_name,scheme_type,minimum_amount,maximum_amount,minimum_months,maximum_months,annual_profit_rate,calculation_method,payment_frequency,tax_percentage,early_withdrawal_rate) SELECT 'FD-SIMPLE','Classroom Fixed Deposit','FIXED_DEPOSIT',10000,5000000,3,36,8,'SIMPLE','AT_MATURITY',10,3 FROM dual WHERE NOT EXISTS (SELECT 1 FROM deposit_schemes WHERE scheme_code='FD-SIMPLE');
  INSERT INTO deposit_schemes(scheme_code,scheme_name,scheme_type,minimum_amount,maximum_amount,minimum_months,maximum_months,annual_profit_rate,calculation_method,payment_frequency,tax_percentage,early_withdrawal_rate) SELECT 'FD-COMPOUND','Monthly Compound Deposit','MONTHLY_PROFIT',10000,5000000,6,36,8.5,'MONTHLY_COMPOUND','AT_MATURITY',10,3 FROM dual WHERE NOT EXISTS (SELECT 1 FROM deposit_schemes WHERE scheme_code='FD-COMPOUND');
  INSERT INTO deposit_schemes(scheme_code,scheme_name,scheme_type,minimum_amount,maximum_amount,minimum_months,maximum_months,annual_profit_rate,calculation_method,payment_frequency,tax_percentage,early_withdrawal_rate) SELECT 'DPS-EDU','Educational DPS','DPS',500,100000,12,36,7.25,'MONTHLY_COMPOUND','RECURRING',5,2 FROM dual WHERE NOT EXISTS (SELECT 1 FROM deposit_schemes WHERE scheme_code='DPS-EDU');
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Phase 3 deposit-profit upgrade complete.');
END;
/
SELECT name,type,line,position,text FROM user_errors ORDER BY name,sequence;

-- ===== database/migrations/004_final_viva_hardening.sql =====
-- Non-destructive Final Viva Hardening upgrade.
-- Adds stable staff IDs and case-insensitive lookup without changing passwords or ledger rows.
DECLARE
  PROCEDURE ignore_expected(p_sql VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1430, -2260, -2275, -1408) THEN RAISE; END IF;
  END;
BEGIN
  ignore_expected('ALTER TABLE loan_types ADD (short_description VARCHAR2(200))');
  ignore_expected('ALTER TABLE loan_types ADD (detailed_description VARCHAR2(1000))');
  ignore_expected('ALTER TABLE loan_types ADD (minimum_annual_income NUMBER(15,2))');
  ignore_expected('ALTER TABLE loan_types ADD (processing_fee_percentage NUMBER(5,2) DEFAULT 0 NOT NULL)');
  ignore_expected('ALTER TABLE loan_types ADD (eligibility_summary VARCHAR2(500))');
  ignore_expected('ALTER TABLE loan_types ADD (required_document_summary VARCHAR2(500))');
  ignore_expected('ALTER TABLE loan_types ADD (interest_method VARCHAR2(20) DEFAULT ''REDUCING_BALANCE'' NOT NULL)');
  ignore_expected('ALTER TABLE loan_types ADD CONSTRAINT ck_loan_type_income CHECK (minimum_annual_income IS NULL OR minimum_annual_income >= 0)');
  ignore_expected('ALTER TABLE loan_types ADD CONSTRAINT ck_loan_type_fee CHECK (processing_fee_percentage BETWEEN 0 AND 100)');
  ignore_expected('ALTER TABLE loan_types ADD CONSTRAINT ck_loan_type_method CHECK (interest_method IN (''REDUCING_BALANCE'',''FLAT_RATE''))');
  ignore_expected('ALTER TABLE users ADD (staff_code VARCHAR2(20))');
  UPDATE users u
       WHEN u.role='ADMIN' THEN 'A-ID-'||LPAD(u.user_id,3,'0')
       ELSE (SELECT e.employee_code FROM employees e WHERE e.employee_id=u.employee_id)
     END
   WHERE u.staff_code IS NULL AND u.role <> 'CUSTOMER';
  ignore_expected('ALTER TABLE users DROP CONSTRAINT ck_user_principal');
  ignore_expected('ALTER TABLE users ADD CONSTRAINT ck_user_principal CHECK ((role = ''CUSTOMER'' AND customer_id IS NOT NULL AND employee_id IS NULL AND staff_code IS NULL) OR (role IN (''MANAGER'',''EMPLOYEE'') AND employee_id IS NOT NULL AND customer_id IS NULL AND staff_code IS NOT NULL) OR (role = ''ADMIN'' AND customer_id IS NULL AND employee_id IS NULL AND staff_code IS NOT NULL))');
  ignore_expected('ALTER TABLE users ADD CONSTRAINT uk_users_staff_code UNIQUE(staff_code)');
  ignore_expected('CREATE UNIQUE INDEX uk_users_staff_code_lower ON users(LOWER(staff_code))');
  ignore_expected('CREATE INDEX idx_users_staff_code_lower ON users(LOWER(staff_code))');
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Final Viva Hardening staff identity upgrade complete.');
END;
/
CREATE OR REPLACE TRIGGER trg_validate_user_staff_code
BEFORE INSERT OR UPDATE OF employee_id, staff_code, role ON users
FOR EACH ROW
DECLARE
  v_employee_code employees.employee_code%TYPE;
BEGIN
  IF :NEW.role IN ('MANAGER', 'EMPLOYEE') THEN
    SELECT employee_code INTO v_employee_code FROM employees WHERE employee_id = :NEW.employee_id;
    IF UPPER(TRIM(:NEW.staff_code)) <> UPPER(TRIM(v_employee_code)) THEN
      RAISE_APPLICATION_ERROR(-20310, 'Staff code must match the linked employee code.');
    END IF;
  ELSIF :NEW.role = 'CUSTOMER' AND :NEW.staff_code IS NOT NULL THEN
    RAISE_APPLICATION_ERROR(-20311, 'Customer users cannot have a staff code.');
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20312, 'Staff users must link to an existing employee.');
END;
/
SELECT name,type,line,position,text FROM user_errors ORDER BY name,sequence;

-- ===== database/sql/11_packages.sql =====
CREATE OR REPLACE PACKAGE pkg_banking_operations AS
  PROCEDURE open_account(p_customer_id NUMBER, p_branch_id NUMBER, p_account_type_id NUMBER, p_initial_deposit NUMBER, p_processed_by NUMBER, p_account_number OUT VARCHAR2);
  PROCEDURE deposit(p_account_number VARCHAR2, p_amount NUMBER, p_processed_by NUMBER, p_reference OUT VARCHAR2);
  PROCEDURE withdraw(p_account_number VARCHAR2, p_amount NUMBER, p_processed_by NUMBER, p_reference OUT VARCHAR2);
  PROCEDURE transfer_funds(p_from_account VARCHAR2, p_to_account VARCHAR2, p_amount NUMBER, p_processed_by NUMBER, p_owner_customer_id NUMBER, p_reference OUT VARCHAR2);
  PROCEDURE change_status(p_account_id NUMBER, p_status VARCHAR2);
  PROCEDURE reverse_transaction(p_transaction_id NUMBER, p_reversed_by NUMBER, p_reason VARCHAR2, p_reference OUT VARCHAR2);
  FUNCTION get_available_balance(p_account_number VARCHAR2) RETURN NUMBER;
END pkg_banking_operations;
/

CREATE OR REPLACE PACKAGE BODY pkg_banking_operations AS
  FUNCTION reference(p_prefix VARCHAR2) RETURN VARCHAR2 IS
  BEGIN RETURN p_prefix || TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3') || LPAD(seq_business_reference.NEXTVAL,6,'0'); END;

  PROCEDURE assert_amount(p_amount NUMBER) IS
  BEGIN IF p_amount IS NULL OR p_amount <= 0 THEN RAISE_APPLICATION_ERROR(-20010,'Amount must be greater than zero.'); END IF; END;

  PROCEDURE open_account(
    p_customer_id NUMBER,
    p_branch_id NUMBER,
    p_account_type_id NUMBER,
    p_initial_deposit NUMBER,
    p_processed_by NUMBER,
    p_account_number OUT VARCHAR2
  ) IS
    v_min NUMBER(15,2);
    v_customer NUMBER;
    v_branch NUMBER;
    v_type NUMBER;
    v_account_id NUMBER;
    v_initial_reference VARCHAR2(50);
  BEGIN
    SELECT COUNT(*)
      INTO v_customer
      FROM customers
     WHERE customer_id = p_customer_id
       AND status = 'ACTIVE';

    SELECT COUNT(*)
      INTO v_branch
      FROM branches
     WHERE branch_id = p_branch_id
       AND status = 'ACTIVE';

    SELECT COUNT(*), MAX(min_balance)
      INTO v_type, v_min
      FROM account_types
     WHERE account_type_id = p_account_type_id
       AND status = 'ACTIVE';

    IF v_customer = 0 THEN
      RAISE_APPLICATION_ERROR(-20011, 'Active customer not found.');
    END IF;

    IF v_branch = 0 THEN
      RAISE_APPLICATION_ERROR(-20012, 'Active branch not found.');
    END IF;

    IF v_type = 0 THEN
      RAISE_APPLICATION_ERROR(-20013, 'Active account type not found.');
    END IF;

    IF NVL(p_initial_deposit, 0) < v_min THEN
      RAISE_APPLICATION_ERROR(
        -20014,
        'Initial deposit is below the minimum balance.'
      );
    END IF;

    p_account_number := fn_generate_account_number();

    INSERT INTO accounts(
      account_number,
      customer_id,
      branch_id,
      account_type_id,
      balance
    )
    VALUES(
      p_account_number,
      p_customer_id,
      p_branch_id,
      p_account_type_id,
      NVL(p_initial_deposit, 0)
    )
    RETURNING account_id INTO v_account_id;

    IF NVL(p_initial_deposit, 0) > 0 THEN
      -- Generate the reference in PL/SQL before using it in SQL.
      v_initial_reference := reference('DEP');

      INSERT INTO transactions(
        account_id,
        transaction_type,
        amount,
        previous_balance,
        new_balance,
        reference_no,
        description,
        processed_by
      )
      VALUES(
        v_account_id,
        'DEPOSIT',
        p_initial_deposit,
        0,
        p_initial_deposit,
        v_initial_reference,
        'Initial deposit',
        p_processed_by
      );
    END IF;
  END;

  PROCEDURE deposit(p_account_number VARCHAR2, p_amount NUMBER, p_processed_by NUMBER, p_reference OUT VARCHAR2) IS
    v_id NUMBER; v_old NUMBER(15,2); v_status VARCHAR2(12);
  BEGIN
    SAVEPOINT deposit_start;
    assert_amount(p_amount);
    SELECT account_id,balance,status INTO v_id,v_old,v_status FROM accounts WHERE account_number=p_account_number FOR UPDATE;
    IF v_status <> 'ACTIVE' THEN RAISE_APPLICATION_ERROR(-20015,'Account is not active.'); END IF;
    p_reference:=reference('DEP');
    UPDATE accounts SET balance=v_old+p_amount,last_transaction_date=SYSTIMESTAMP WHERE account_id=v_id;
    INSERT INTO transactions(account_id,transaction_type,amount,previous_balance,new_balance,reference_no,description,processed_by)
    VALUES(v_id,'DEPOSIT',p_amount,v_old,v_old+p_amount,p_reference,'Cash deposit',p_processed_by);
  EXCEPTION WHEN NO_DATA_FOUND THEN ROLLBACK TO deposit_start; RAISE_APPLICATION_ERROR(-20016,'Account not found.'); WHEN OTHERS THEN ROLLBACK TO deposit_start; RAISE;
  END;

  PROCEDURE withdraw(p_account_number VARCHAR2, p_amount NUMBER, p_processed_by NUMBER, p_reference OUT VARCHAR2) IS
    v_id NUMBER; v_old NUMBER(15,2); v_min NUMBER(15,2); v_status VARCHAR2(12);
  BEGIN
    SAVEPOINT withdrawal_start;
    assert_amount(p_amount);
    SELECT a.account_id,a.balance,a.status,t.min_balance INTO v_id,v_old,v_status,v_min FROM accounts a JOIN account_types t ON t.account_type_id=a.account_type_id WHERE a.account_number=p_account_number FOR UPDATE OF a.balance;
    IF v_status <> 'ACTIVE' THEN RAISE_APPLICATION_ERROR(-20017,'Account is not active.'); END IF;
    IF v_old-p_amount < v_min THEN RAISE_APPLICATION_ERROR(-20018,'Insufficient available balance after minimum balance.'); END IF;
    p_reference:=reference('WDL'); UPDATE accounts SET balance=v_old-p_amount,last_transaction_date=SYSTIMESTAMP WHERE account_id=v_id;
    INSERT INTO transactions(account_id,transaction_type,amount,previous_balance,new_balance,reference_no,description,processed_by)
    VALUES(v_id,'WITHDRAWAL',p_amount,v_old,v_old-p_amount,p_reference,'Cash withdrawal',p_processed_by);
  EXCEPTION WHEN NO_DATA_FOUND THEN ROLLBACK TO withdrawal_start; RAISE_APPLICATION_ERROR(-20019,'Account not found.'); WHEN OTHERS THEN ROLLBACK TO withdrawal_start; RAISE;
  END;

  PROCEDURE transfer_funds(p_from_account VARCHAR2, p_to_account VARCHAR2, p_amount NUMBER, p_processed_by NUMBER, p_owner_customer_id NUMBER, p_reference OUT VARCHAR2) IS
    v_from_id NUMBER; v_to_id NUMBER; v_from_old NUMBER(15,2); v_to_old NUMBER(15,2); v_min NUMBER(15,2); v_from_status VARCHAR2(12); v_to_status VARCHAR2(12); v_owner NUMBER; v_debit NUMBER; v_credit NUMBER;
  BEGIN
    SAVEPOINT transfer_start;
    assert_amount(p_amount);
    IF p_from_account=p_to_account THEN RAISE_APPLICATION_ERROR(-20020,'Source and destination must differ.'); END IF;
    -- Lock in account-id order to reduce deadlock risk between concurrent transfers.
    SELECT account_id INTO v_from_id FROM accounts WHERE account_number=p_from_account;
    SELECT account_id INTO v_to_id FROM accounts WHERE account_number=p_to_account;
    FOR r IN (SELECT account_id FROM accounts WHERE account_id IN(v_from_id,v_to_id) ORDER BY account_id FOR UPDATE) LOOP NULL; END LOOP;
    SELECT a.balance,a.status,a.customer_id,t.min_balance INTO v_from_old,v_from_status,v_owner,v_min FROM accounts a JOIN account_types t ON t.account_type_id=a.account_type_id WHERE a.account_id=v_from_id;
    SELECT balance,status INTO v_to_old,v_to_status FROM accounts WHERE account_id=v_to_id;
    IF v_from_status<>'ACTIVE' OR v_to_status<>'ACTIVE' THEN RAISE_APPLICATION_ERROR(-20021,'Both accounts must be active.'); END IF;
    IF p_owner_customer_id IS NOT NULL AND v_owner<>p_owner_customer_id THEN RAISE_APPLICATION_ERROR(-20022,'Source account is not owned by this customer.'); END IF;
    IF v_from_old-p_amount<v_min THEN RAISE_APPLICATION_ERROR(-20023,'Insufficient available balance after minimum balance.'); END IF;
    p_reference:=reference('TRF');
    UPDATE accounts SET balance=v_from_old-p_amount,last_transaction_date=SYSTIMESTAMP WHERE account_id=v_from_id;
    UPDATE accounts SET balance=v_to_old+p_amount,last_transaction_date=SYSTIMESTAMP WHERE account_id=v_to_id;
    INSERT INTO transactions(account_id,related_account_id,transaction_type,amount,previous_balance,new_balance,reference_no,description,processed_by)
    VALUES(v_from_id,v_to_id,'TRANSFER_DEBIT',p_amount,v_from_old,v_from_old-p_amount,p_reference||'-D','Fund transfer debit',p_processed_by) RETURNING transaction_id INTO v_debit;
    INSERT INTO transactions(account_id,related_account_id,transaction_type,amount,previous_balance,new_balance,reference_no,description,processed_by)
    VALUES(v_to_id,v_from_id,'TRANSFER_CREDIT',p_amount,v_to_old,v_to_old+p_amount,p_reference||'-C','Fund transfer credit',p_processed_by) RETURNING transaction_id INTO v_credit;
    INSERT INTO fund_transfers(transfer_reference,from_account_id,to_account_id,amount,debit_transaction_id,credit_transaction_id,initiated_by)
    VALUES(p_reference,v_from_id,v_to_id,p_amount,v_debit,v_credit,p_processed_by);
  EXCEPTION WHEN NO_DATA_FOUND THEN ROLLBACK TO transfer_start; RAISE_APPLICATION_ERROR(-20024,'One or both accounts were not found.'); WHEN OTHERS THEN ROLLBACK TO transfer_start; RAISE;
  END;

  PROCEDURE change_status(p_account_id NUMBER,p_status VARCHAR2) IS v_balance NUMBER;
  BEGIN
    IF p_status NOT IN ('ACTIVE','FROZEN','CLOSED') THEN RAISE_APPLICATION_ERROR(-20025,'Invalid account status.'); END IF;
    SELECT balance INTO v_balance FROM accounts WHERE account_id=p_account_id FOR UPDATE;
    IF p_status='CLOSED' AND v_balance<>0 THEN RAISE_APPLICATION_ERROR(-20026,'A non-zero account cannot be closed.'); END IF;
    UPDATE accounts SET status=p_status,close_date=CASE WHEN p_status='CLOSED' THEN SYSDATE ELSE NULL END WHERE account_id=p_account_id;
  EXCEPTION WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20027,'Account not found.'); END;

  PROCEDURE reverse_transaction(p_transaction_id NUMBER, p_reversed_by NUMBER, p_reason VARCHAR2, p_reference OUT VARCHAR2) IS
    v_account_id NUMBER; v_amount NUMBER(15,2); v_type VARCHAR2(30); v_status VARCHAR2(12);
    v_account_number VARCHAR2(24); v_balance NUMBER(15,2); v_new_balance NUMBER(15,2);
    v_reversal_type VARCHAR2(30); v_reversal_id NUMBER;
  BEGIN
    SAVEPOINT reversal_start;
    IF TRIM(p_reason) IS NULL THEN RAISE_APPLICATION_ERROR(-20029,'Reversal reason is required.'); END IF;
    SELECT t.account_id,t.amount,t.transaction_type,t.status,a.account_number
      INTO v_account_id,v_amount,v_type,v_status,v_account_number
      FROM transactions t JOIN accounts a ON a.account_id=t.account_id
     WHERE t.transaction_id=p_transaction_id FOR UPDATE;
    IF v_status <> 'SUCCESS' THEN RAISE_APPLICATION_ERROR(-20030,'Only successful transactions can be reversed.'); END IF;
    IF v_type NOT IN ('DEPOSIT','WITHDRAWAL') THEN RAISE_APPLICATION_ERROR(-20031,'Only deposits and withdrawals can be reversed.'); END IF;
    SELECT COUNT(*) INTO v_reversal_id FROM transaction_reversals WHERE original_transaction_id=p_transaction_id;
    IF v_reversal_id > 0 THEN RAISE_APPLICATION_ERROR(-20032,'This transaction has already been reversed.'); END IF;
    SELECT balance,status INTO v_balance,v_status FROM accounts WHERE account_id=v_account_id FOR UPDATE;
    IF v_status <> 'ACTIVE' THEN RAISE_APPLICATION_ERROR(-20035,'Account is not active.'); END IF;
    IF v_type='DEPOSIT' THEN
      v_new_balance:=v_balance-v_amount; v_reversal_type:='REVERSAL_DEBIT';
      IF v_new_balance < 0 THEN RAISE_APPLICATION_ERROR(-20033,'Reversal would create a negative balance.'); END IF;
    ELSE
      v_new_balance:=v_balance+v_amount; v_reversal_type:='REVERSAL_CREDIT';
    END IF;
    p_reference:=reference('REV');
    UPDATE accounts SET balance=v_new_balance,last_transaction_date=SYSTIMESTAMP WHERE account_id=v_account_id;
    INSERT INTO transactions(account_id,transaction_type,amount,previous_balance,new_balance,reference_no,description,processed_by)
    VALUES(v_account_id,v_reversal_type,v_amount,v_balance,v_new_balance,p_reference,'Reversal of transaction '||p_transaction_id,p_reversed_by)
    RETURNING transaction_id INTO v_reversal_id;
    INSERT INTO transaction_reversals(original_transaction_id,reversal_transaction_id,reason,reversed_by)
    VALUES(p_transaction_id,v_reversal_id,TRIM(p_reason),p_reversed_by);
    INSERT INTO audit_log(table_name,record_id,action_name,action_by,new_summary)
    VALUES('TRANSACTIONS',p_transaction_id,'REVERSAL',NVL(TO_CHAR(p_reversed_by),'SYSTEM'),'reversal_reference='||p_reference||';reason='||TRIM(p_reason));
  EXCEPTION WHEN NO_DATA_FOUND THEN ROLLBACK TO reversal_start; RAISE_APPLICATION_ERROR(-20034,'Original transaction not found.');
    WHEN OTHERS THEN ROLLBACK TO reversal_start; RAISE;
  END;

  FUNCTION get_available_balance(p_account_number VARCHAR2) RETURN NUMBER IS v_balance NUMBER; v_min NUMBER;
  BEGIN SELECT a.balance,t.min_balance INTO v_balance,v_min FROM accounts a JOIN account_types t ON t.account_type_id=a.account_type_id WHERE a.account_number=p_account_number AND a.status='ACTIVE'; RETURN GREATEST(v_balance-v_min,0);
  EXCEPTION WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20028,'Active account not found.'); END;
END pkg_banking_operations;
/

CREATE OR REPLACE PACKAGE pkg_loan_operations AS
  PROCEDURE apply_for_loan(p_customer_id NUMBER,p_loan_type_id NUMBER,p_account_id NUMBER,p_amount NUMBER,p_term_months NUMBER,p_loan_number OUT VARCHAR2);
  PROCEDURE approve_loan(p_loan_id NUMBER,p_approved_amount NUMBER,p_reviewer_employee_id NUMBER,p_processed_by NUMBER,p_reference OUT VARCHAR2);
  PROCEDURE reject_loan(p_loan_id NUMBER,p_reason VARCHAR2,p_reviewer_employee_id NUMBER);
  PROCEDURE record_payment(p_loan_id NUMBER,p_account_number VARCHAR2,p_amount NUMBER,p_received_by NUMBER,p_reference OUT VARCHAR2);
  FUNCTION remaining_installments(p_loan_id NUMBER) RETURN NUMBER;
END pkg_loan_operations;
/

CREATE OR REPLACE PACKAGE BODY pkg_loan_operations AS
  PROCEDURE apply_for_loan(p_customer_id NUMBER,p_loan_type_id NUMBER,p_account_id NUMBER,p_amount NUMBER,p_term_months NUMBER,p_loan_number OUT VARCHAR2) IS v_min NUMBER;v_max NUMBER;v_rate NUMBER;v_tmin NUMBER;v_tmax NUMBER;v_owner NUMBER;
  BEGIN SELECT min_amount,max_amount,annual_interest_rate,min_term_months,max_term_months INTO v_min,v_max,v_rate,v_tmin,v_tmax FROM loan_types WHERE loan_type_id=p_loan_type_id AND status='ACTIVE'; SELECT customer_id INTO v_owner FROM accounts WHERE account_id=p_account_id AND status='ACTIVE';
    IF v_owner<>p_customer_id THEN RAISE_APPLICATION_ERROR(-20100,'Disbursement account is not owned by customer.'); END IF;
    IF p_amount NOT BETWEEN v_min AND v_max OR p_term_months NOT BETWEEN v_tmin AND v_tmax THEN RAISE_APPLICATION_ERROR(-20101,'Amount or term is outside loan type limits.'); END IF;
    p_loan_number:=fn_generate_loan_number(); INSERT INTO loans(loan_number,customer_id,loan_type_id,disbursement_account_id,requested_amount,interest_rate,term_months) VALUES(p_loan_number,p_customer_id,p_loan_type_id,p_account_id,p_amount,v_rate,p_term_months);
  EXCEPTION WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20102,'Loan type or account not found.'); END;
  PROCEDURE approve_loan(p_loan_id NUMBER,p_approved_amount NUMBER,p_reviewer_employee_id NUMBER,p_processed_by NUMBER,p_reference OUT VARCHAR2) IS v_status VARCHAR2(20);v_requested NUMBER;v_account NUMBER;v_old NUMBER;v_emi NUMBER;v_total NUMBER;v_term NUMBER;
  BEGIN SAVEPOINT loan_approval; SELECT status,requested_amount,disbursement_account_id,term_months INTO v_status,v_requested,v_account,v_term FROM loans WHERE loan_id=p_loan_id FOR UPDATE; IF v_status<>'PENDING' THEN RAISE_APPLICATION_ERROR(-20103,'Loan has already been decided.'); END IF; IF p_approved_amount<=0 OR p_approved_amount>v_requested THEN RAISE_APPLICATION_ERROR(-20104,'Approved amount is invalid.'); END IF;
    SELECT balance INTO v_old FROM accounts WHERE account_id=v_account AND status='ACTIVE' FOR UPDATE; SELECT fn_calculate_emi(p_approved_amount,interest_rate,term_months) INTO v_emi FROM loans WHERE loan_id=p_loan_id; v_total:=ROUND(v_emi*v_term,2); p_reference:='LND'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3')||seq_business_reference.NEXTVAL;
    UPDATE accounts SET balance=v_old+p_approved_amount,last_transaction_date=SYSTIMESTAMP WHERE account_id=v_account;
    INSERT INTO transactions(account_id,transaction_type,amount,previous_balance,new_balance,reference_no,description,processed_by) VALUES(v_account,'LOAN_DISBURSEMENT',p_approved_amount,v_old,v_old+p_approved_amount,p_reference,'Loan disbursement',p_processed_by);
    UPDATE loans SET approved_amount=p_approved_amount,monthly_installment=v_emi,total_repayable=v_total,outstanding_balance=v_total,status='ACTIVE',reviewed_by=p_reviewer_employee_id,reviewed_at=SYSTIMESTAMP,start_date=SYSDATE,end_date=ADD_MONTHS(SYSDATE,term_months) WHERE loan_id=p_loan_id;
  EXCEPTION WHEN NO_DATA_FOUND THEN ROLLBACK TO loan_approval; RAISE_APPLICATION_ERROR(-20105,'Pending loan or active account not found.'); WHEN OTHERS THEN ROLLBACK TO loan_approval; RAISE; END;
  PROCEDURE reject_loan(p_loan_id NUMBER,p_reason VARCHAR2,p_reviewer_employee_id NUMBER) IS v_status VARCHAR2(20); BEGIN IF TRIM(p_reason) IS NULL THEN RAISE_APPLICATION_ERROR(-20106,'Rejection reason is required.'); END IF; SELECT status INTO v_status FROM loans WHERE loan_id=p_loan_id FOR UPDATE; IF v_status<>'PENDING' THEN RAISE_APPLICATION_ERROR(-20107,'Loan has already been decided.'); END IF; UPDATE loans SET status='REJECTED',rejection_reason=TRIM(p_reason),reviewed_by=p_reviewer_employee_id,reviewed_at=SYSTIMESTAMP WHERE loan_id=p_loan_id; EXCEPTION WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20108,'Loan not found.'); END;
  PROCEDURE record_payment(p_loan_id NUMBER,p_account_number VARCHAR2,p_amount NUMBER,p_received_by NUMBER,p_reference OUT VARCHAR2) IS
    v_out NUMBER;
    v_status VARCHAR2(20);
    v_account NUMBER;
    v_old NUMBER;
    v_tx NUMBER;
    v_new NUMBER;
    v_loan_customer NUMBER;
    v_account_customer NUMBER;
  BEGIN
    SAVEPOINT loan_payment;
    IF p_amount IS NULL OR p_amount<=0 THEN RAISE_APPLICATION_ERROR(-20109,'Payment must be positive.'); END IF;
    SELECT outstanding_balance,status,customer_id
      INTO v_out,v_status,v_loan_customer
      FROM loans WHERE loan_id=p_loan_id FOR UPDATE;
    IF v_status<>'ACTIVE' THEN RAISE_APPLICATION_ERROR(-20110,'Only active loans accept payment.'); END IF;
    IF p_amount>v_out THEN RAISE_APPLICATION_ERROR(-20111,'Payment exceeds outstanding balance.'); END IF;
    SELECT account_id,balance,customer_id
      INTO v_account,v_old,v_account_customer
      FROM accounts WHERE account_number=p_account_number AND status='ACTIVE' FOR UPDATE;
    IF v_account_customer<>v_loan_customer THEN RAISE_APPLICATION_ERROR(-20115,'Payment account does not belong to the loan customer.'); END IF;
    IF p_amount>v_old THEN RAISE_APPLICATION_ERROR(-20112,'Insufficient account balance.'); END IF;
    v_new:=v_out-p_amount;
    p_reference:='LNP'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3')||seq_business_reference.NEXTVAL;
    UPDATE accounts SET balance=v_old-p_amount,last_transaction_date=SYSTIMESTAMP WHERE account_id=v_account;
    INSERT INTO transactions(account_id,transaction_type,amount,previous_balance,new_balance,reference_no,description,processed_by)
    VALUES(v_account,'LOAN_PAYMENT',p_amount,v_old,v_old-p_amount,p_reference,'Loan payment',p_received_by)
    RETURNING transaction_id INTO v_tx;
    INSERT INTO loan_payments(loan_id,account_id,transaction_id,amount,previous_outstanding,new_outstanding,received_by)
    VALUES(p_loan_id,v_account,v_tx,p_amount,v_out,v_new,p_received_by);
    UPDATE loans SET outstanding_balance=v_new,status=CASE WHEN v_new=0 THEN 'COMPLETED' ELSE 'ACTIVE' END WHERE loan_id=p_loan_id;
  EXCEPTION WHEN NO_DATA_FOUND THEN ROLLBACK TO loan_payment; RAISE_APPLICATION_ERROR(-20113,'Loan or account not found.'); WHEN OTHERS THEN ROLLBACK TO loan_payment; RAISE; END;
  FUNCTION remaining_installments(p_loan_id NUMBER) RETURN NUMBER IS v_out NUMBER;v_emi NUMBER; BEGIN SELECT outstanding_balance,monthly_installment INTO v_out,v_emi FROM loans WHERE loan_id=p_loan_id; RETURN CASE WHEN v_out=0 THEN 0 ELSE CEIL(v_out/v_emi) END; EXCEPTION WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20114,'Loan not found.'); END;
END pkg_loan_operations;
/

-- ===== database/sql/08_procedures.sql =====
-- Compatibility wrappers for classroom demonstrations. New application code calls packages.
CREATE OR REPLACE PROCEDURE pr_deposit(p_account_number VARCHAR2,p_amount NUMBER,p_processed_by NUMBER,p_reference OUT VARCHAR2) AS
BEGIN pkg_banking_operations.deposit(p_account_number,p_amount,p_processed_by,p_reference); END;
/
CREATE OR REPLACE PROCEDURE pr_withdraw(p_account_number VARCHAR2,p_amount NUMBER,p_processed_by NUMBER,p_reference OUT VARCHAR2) AS
BEGIN pkg_banking_operations.withdraw(p_account_number,p_amount,p_processed_by,p_reference); END;
/
CREATE OR REPLACE PROCEDURE pr_transfer(p_from_account VARCHAR2,p_to_account VARCHAR2,p_amount NUMBER,p_processed_by NUMBER,p_owner_customer_id NUMBER,p_reference OUT VARCHAR2) AS
BEGIN pkg_banking_operations.transfer_funds(p_from_account,p_to_account,p_amount,p_processed_by,p_owner_customer_id,p_reference); END;
/

-- ===== database/sql/04_views.sql =====
CREATE OR REPLACE VIEW vw_customer_account_summary AS
SELECT c.customer_id,c.first_name||' '||c.last_name customer_name,a.account_id,a.account_number,
       t.type_name,b.branch_name,a.balance,a.currency,a.status,a.open_date
FROM customers c JOIN accounts a ON a.customer_id=c.customer_id
JOIN account_types t ON t.account_type_id=a.account_type_id JOIN branches b ON b.branch_id=a.branch_id;

CREATE OR REPLACE VIEW vw_branch_performance AS
SELECT b.branch_id,b.branch_code,b.branch_name,
       COUNT(DISTINCT a.account_id) total_accounts,COUNT(DISTINCT a.customer_id) total_customers,
       NVL(SUM(CASE WHEN a.status<>'CLOSED' THEN a.balance ELSE 0 END),0) total_balance
FROM branches b LEFT JOIN accounts a ON a.branch_id=b.branch_id GROUP BY b.branch_id,b.branch_code,b.branch_name;

CREATE OR REPLACE VIEW vw_account_transaction_summary AS
SELECT a.account_id,a.account_number,COUNT(t.transaction_id) transaction_count,
       NVL(SUM(CASE WHEN t.transaction_type IN('DEPOSIT','TRANSFER_CREDIT','LOAN_DISBURSEMENT') THEN t.amount ELSE 0 END),0) total_credit,
       NVL(SUM(CASE WHEN t.transaction_type IN('WITHDRAWAL','TRANSFER_DEBIT','LOAN_PAYMENT') THEN t.amount ELSE 0 END),0) total_debit
FROM accounts a LEFT JOIN transactions t ON t.account_id=a.account_id GROUP BY a.account_id,a.account_number;

CREATE OR REPLACE VIEW vw_loan_summary AS
SELECT l.loan_id,l.loan_number,c.first_name||' '||c.last_name customer_name,lt.type_name,
       l.requested_amount,l.approved_amount,l.monthly_installment,l.outstanding_balance,l.status,l.application_date
FROM loans l JOIN customers c ON c.customer_id=l.customer_id JOIN loan_types lt ON lt.loan_type_id=l.loan_type_id;

CREATE OR REPLACE VIEW vw_daily_transaction_totals AS
SELECT TRUNC(transaction_date) transaction_day,transaction_type,COUNT(*) transaction_count,SUM(amount) total_amount
FROM transactions WHERE status='SUCCESS' GROUP BY TRUNC(transaction_date),transaction_type;

CREATE OR REPLACE VIEW vw_pending_loan_applications AS
SELECT l.loan_id,l.loan_number,l.customer_id,c.first_name||' '||c.last_name customer_name,
       lt.type_name,l.requested_amount,l.term_months,l.application_date,a.branch_id
FROM loans l JOIN customers c ON c.customer_id=l.customer_id JOIN loan_types lt ON lt.loan_type_id=l.loan_type_id
JOIN accounts a ON a.account_id=l.disbursement_account_id WHERE l.status='PENDING';

CREATE OR REPLACE VIEW vw_account_statement AS
SELECT t.transaction_id,t.account_id,t.reference_no,t.transaction_type,t.amount,t.previous_balance,t.new_balance running_balance,
       t.status,t.transaction_date,
       CASE WHEN t.transaction_type IN ('DEPOSIT','TRANSFER_CREDIT','LOAN_DISBURSEMENT','REVERSAL_CREDIT') THEN t.amount ELSE 0 END credit,
       CASE WHEN t.transaction_type IN ('WITHDRAWAL','TRANSFER_DEBIT','LOAN_PAYMENT','REVERSAL_DEBIT') THEN t.amount ELSE 0 END debit
FROM transactions t;

CREATE OR REPLACE VIEW vw_deposit_certificate_reminders AS
SELECT d.certificate_id,d.certificate_number,d.customer_id,d.account_id,d.maturity_date,
       d.expected_maturity_amount,d.status,s.scheme_name,
       CASE WHEN d.status='MATURED' OR d.maturity_date < TRUNC(SYSDATE) THEN 'ALREADY_MATURED'
            WHEN d.maturity_date <= TRUNC(SYSDATE)+7 THEN 'WITHIN_7_DAYS'
            WHEN EXTRACT(MONTH FROM d.maturity_date)=EXTRACT(MONTH FROM SYSDATE)
             AND EXTRACT(YEAR FROM d.maturity_date)=EXTRACT(YEAR FROM SYSDATE) THEN 'THIS_MONTH'
            ELSE 'FUTURE' END reminder_category
FROM deposit_certificates d JOIN deposit_schemes s ON s.scheme_id=d.scheme_id
WHERE d.status IN ('QUOTATION','ACTIVE','MATURED');

-- ===== database/sql/10_triggers.sql =====
CREATE OR REPLACE FUNCTION fn_audit_actor RETURN VARCHAR2 IS
BEGIN
  RETURN COALESCE(
    SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'),
    SYS_CONTEXT('USERENV', 'SESSION_USER')
  );
END;
/

CREATE OR REPLACE TRIGGER trg_audit_customer_update
AFTER UPDATE ON customers
FOR EACH ROW
BEGIN
  INSERT INTO audit_log(table_name,record_id,action_name,action_by,old_summary,new_summary)
  VALUES(
    'CUSTOMERS', :NEW.customer_id, 'UPDATE', fn_audit_actor(),
    'status='||:OLD.status||';phone='||:OLD.phone,
    'status='||:NEW.status||';phone='||:NEW.phone
  );
END;
/

CREATE OR REPLACE TRIGGER trg_audit_account_status
AFTER UPDATE OF status ON accounts
FOR EACH ROW
WHEN (OLD.status <> NEW.status)
BEGIN
  INSERT INTO audit_log(table_name,record_id,action_name,action_by,old_summary,new_summary)
  VALUES('ACCOUNTS',:NEW.account_id,'STATUS_CHANGE',fn_audit_actor(),'status='||:OLD.status,'status='||:NEW.status);
END;
/

CREATE OR REPLACE TRIGGER trg_audit_loan_status
AFTER UPDATE OF status ON loans
FOR EACH ROW
WHEN (OLD.status <> NEW.status)
BEGIN
  INSERT INTO audit_log(table_name,record_id,action_name,action_by,old_summary,new_summary)
  VALUES('LOANS',:NEW.loan_id,'STATUS_CHANGE',fn_audit_actor(),'status='||:OLD.status,'status='||:NEW.status);
END;
/

CREATE OR REPLACE TRIGGER trg_protect_financial_history
BEFORE UPDATE OR DELETE ON transactions
BEGIN
  RAISE_APPLICATION_ERROR(-20200,'Financial transaction history cannot be updated or deleted. Use a controlled reversal entry.');
END;
/

CREATE OR REPLACE TRIGGER trg_validate_user_staff_code
BEFORE INSERT OR UPDATE OF employee_id, staff_code, role ON users
FOR EACH ROW
DECLARE
  v_employee_code employees.employee_code%TYPE;
BEGIN
  IF :NEW.role IN ('MANAGER', 'EMPLOYEE') THEN
    SELECT employee_code INTO v_employee_code FROM employees WHERE employee_id = :NEW.employee_id;
    IF UPPER(TRIM(:NEW.staff_code)) <> UPPER(TRIM(v_employee_code)) THEN
      RAISE_APPLICATION_ERROR(-20310, 'Staff code must match the linked employee code.');
    END IF;
  ELSIF :NEW.role = 'CUSTOMER' AND :NEW.staff_code IS NOT NULL THEN
    RAISE_APPLICATION_ERROR(-20311, 'Customer users cannot have a staff code.');
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20312, 'Staff users must link to an existing employee.');
END;
/
