import { useEffect, useState } from "react";
import { Edit3, Plus, UserCheck } from "lucide-react";
import { useNavigate } from "react-router-dom";
import api, { messageFrom } from "../services/api";
import { Empty, ErrorBox, Loading, Modal, PageHeader, Pagination, Status } from "../components/UI";
import { useAuth } from "../context/AuthContext";

const empty = { sourceAccountNumber: "", beneficiaryAccountNumber: "", nickname: "" };
export default function Beneficiaries() {
  const { user } = useAuth(); const navigate = useNavigate(); const [data, setData] = useState(null); const [accounts, setAccounts] = useState([]); const [form, setForm] = useState(empty); const [editing, setEditing] = useState(null); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false); const [page, setPage] = useState(1);
  async function load() { try { const response = await api.get("/beneficiaries", { params: { page, pageSize: 10 } }); setData(response.data); setError(""); } catch (requestError) { setError(messageFrom(requestError)); } }
  useEffect(() => { load(); if (user.role === "CUSTOMER") api.get("/accounts", { params: { pageSize: 100 } }).then((response) => setAccounts(response.data.items || [])).catch((requestError) => setError(messageFrom(requestError))); }, [page]); // eslint-disable-line react-hooks/exhaustive-deps
  async function save(event) { event.preventDefault(); if (busy) return; setBusy(true); try { if (editing) await api.patch(`/beneficiaries/${editing.BENEFICIARY_ID}`, { nickname: form.nickname, status: editing.STATUS }); else await api.post("/beneficiaries", form); setNotice(editing ? "Beneficiary renamed." : "Beneficiary added."); setEditing(null); setForm(empty); await load(); } catch (requestError) { setError(messageFrom(requestError)); } finally { setBusy(false); } }
  async function deactivate(row) { if (!window.confirm(`Deactivate ${row.NICKNAME}?`)) return; setBusy(true); try { await api.patch(`/beneficiaries/${row.BENEFICIARY_ID}`, { status: "INACTIVE" }); await load(); } catch (requestError) { setError(messageFrom(requestError)); } finally { setBusy(false); } }
  if (!data && !error) return <Loading />;
  return <><PageHeader title="Beneficiaries" subtitle="Saved transfer destinations; historical records are deactivated, never deleted." action={user.role === "CUSTOMER" && <button className="btn-primary" onClick={() => { setEditing("new"); setForm(empty); }}><Plus size={16} /> Add beneficiary</button>} />{notice && <div className="mb-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</div>}<ErrorBox message={error} />{!data?.items.length ? <Empty text="No beneficiaries found." /> : <div className="table-wrap"><table className="data-table"><thead><tr><th>Nickname</th><th>Source account</th><th>Beneficiary account</th><th>Status</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{data.items.map((row) => <tr key={row.BENEFICIARY_ID}><td className="font-semibold">{row.NICKNAME}</td><td>{row.SOURCE_ACCOUNT_NUMBER}</td><td>{row.BENEFICIARY_ACCOUNT_NUMBER}</td><td><Status value={row.STATUS} /></td><td>{new Date(row.UPDATED_AT).toLocaleString()}</td><td><div className="flex flex-wrap gap-2 text-sm">{user.role === "CUSTOMER" && row.STATUS === "ACTIVE" && <><button className="text-blue-700" onClick={() => navigate(`/transactions?beneficiary=${row.BENEFICIARY_ACCOUNT_NUMBER}`)}><UserCheck size={14} className="inline" /> Transfer</button><button className="text-violet-700" onClick={() => { setEditing(row); setForm({ ...form, nickname: row.NICKNAME }); }}><Edit3 size={14} className="inline" /> Rename</button><button className="text-red-700" onClick={() => deactivate(row)}>Deactivate</button></>}</div></td></tr>)}</tbody></table></div>}{data && <Pagination page={data.page} pageSize={data.pageSize} total={data.total} onPage={setPage} />}{editing && <Modal title={editing === "new" ? "Add beneficiary" : "Rename beneficiary"} onClose={() => !busy && setEditing(null)}><form onSubmit={save} className="grid gap-4">{editing === "new" && <><label className="field">Source account<select required value={form.sourceAccountNumber} onChange={(event) => setForm({ ...form, sourceAccountNumber: event.target.value })}><option value="">Select account</option>{accounts.map((account) => <option key={account.ACCOUNT_NUMBER}>{account.ACCOUNT_NUMBER}</option>)}</select></label><label className="field">Beneficiary account<input required value={form.beneficiaryAccountNumber} onChange={(event) => setForm({ ...form, beneficiaryAccountNumber: event.target.value })} /></label></>}<label className="field">Nickname<input required maxLength="100" value={form.nickname} onChange={(event) => setForm({ ...form, nickname: event.target.value })} /></label><button className="btn-primary" disabled={busy}>{busy ? "Saving…" : "Save beneficiary"}</button></form></Modal>}</>;
}
