import { useEffect, useMemo, useState } from "react";
import { Download, RefreshCw, Search } from "lucide-react";
import api, { messageFrom } from "../services/api";
import { Empty, ErrorBox, Loading, Modal, PageHeader, Pagination } from "../components/UI";
import { useAuth } from "../context/AuthContext";

export default function DatabaseExplorer() {
  const { user } = useAuth(); const [resources, setResources] = useState([]); const [resource, setResource] = useState(""); const [data, setData] = useState(null); const [filters, setFilters] = useState({ search: "", sort: "", direction: "DESC", page: 1, pageSize: 20 }); const [error, setError] = useState(""); const [details, setDetails] = useState(null);
  const allowed = ["ADMIN", "MANAGER"].includes(user.role);
  useEffect(() => { if (allowed) api.get("/explorer/resources").then((response) => { setResources(response.data); setResource(response.data[0]?.key || ""); }).catch((requestError) => setError(messageFrom(requestError))); }, [allowed]);
  const selected = useMemo(() => resources.find((item) => item.key === resource), [resources, resource]);
  async function load() { if (!resource) return; try { const query = new URLSearchParams(filters); Object.keys(filters).forEach((key) => !filters[key] && query.delete(key)); const response = await api.get(`/explorer/${resource}?${query}`); setData(response.data); setError(""); } catch (requestError) { setError(messageFrom(requestError)); } }
  useEffect(() => { load(); }, [resource, filters]); // eslint-disable-line react-hooks/exhaustive-deps
  function update(key, value) { setFilters((current) => ({ ...current, [key]: value, page: key === "page" ? value : 1 })); }
  async function exportCsv() { try { const response = await api.get(`/explorer/${resource}`, { params: { ...filters, format: "csv" }, responseType: "blob" }); const url = URL.createObjectURL(response.data); const link = document.createElement("a"); link.href = url; link.download = `${resource}.csv`; link.click(); URL.revokeObjectURL(url); } catch (requestError) { setError(messageFrom(requestError)); } }
  if (!allowed) return <ErrorBox message="Database Explorer is available to Admin and Manager roles only." />;
  if (!resources.length && !error) return <Loading />;
  return <><PageHeader title="Database Explorer" subtitle="Read-only, allowlisted Oracle resources with server-side branch scope." action={<div className="flex gap-2"><button className="btn-secondary" disabled={!resource} onClick={load}><RefreshCw size={16} /> Refresh</button><button className="btn-primary" disabled={!resource} onClick={exportCsv}><Download size={16} /> Export CSV</button></div>} /><ErrorBox message={error} />
    <section className="card mb-5"><div className="grid gap-3 md:grid-cols-4"><label className="field">Resource<select value={resource} onChange={(event) => { setResource(event.target.value); setFilters((current) => ({ ...current, page: 1, sort: "" })); }}>{resources.map((item) => <option key={item.key} value={item.key}>{item.label}</option>)}</select></label><label className="field md:col-span-2"><span className="sr-only">Search resource</span><span className="flex items-center gap-2"><Search size={16} /><input placeholder="Search approved columns" value={filters.search} onChange={(event) => update("search", event.target.value)} /></span></label><label className="field">Rows per page<select value={filters.pageSize} onChange={(event) => update("pageSize", event.target.value)}><option value="10">10</option><option value="20">20</option><option value="50">50</option><option value="100">100</option></select></label><label className="field">Sort<select value={filters.sort} onChange={(event) => update("sort", event.target.value)}><option value="">Default</option>{selected?.sort.map((column) => <option key={column}>{column}</option>)}</select></label><label className="field">Direction<select value={filters.direction} onChange={(event) => update("direction", event.target.value)}><option>DESC</option><option>ASC</option></select></label></div></section>
    {data && <p className="mb-3 text-sm text-slate-500">{data.total} total rows · page {data.page}</p>}{!data?.items?.length ? <Empty text="No rows match this approved resource." /> : <div className="table-wrap"><table className="data-table"><thead><tr>{data.columns.map((column) => <th key={column}>{column.replaceAll("_", " ")}</th>)}<th>Details</th></tr></thead><tbody>{data.items.map((row, index) => <tr key={`${resource}-${index}`}>{data.columns.map((column) => <td key={column}>{String(row[column] ?? "—")}</td>)}<td><button className="text-blue-700" onClick={() => setDetails(row)}>View</button></td></tr>)}</tbody></table></div>}{data && <Pagination page={data.page} pageSize={data.pageSize} total={data.total} onPage={(page) => update("page", page)} />}
    {details && <Modal title={`${selected?.label || "Row"} details`} onClose={() => setDetails(null)}><dl className="grid gap-3 text-sm sm:grid-cols-2">{Object.entries(details).filter(([key]) => key !== "TOTAL_COUNT").map(([key, value]) => <div key={key}><dt className="text-xs uppercase text-slate-500">{key.replaceAll("_", " ")}</dt><dd className="break-words font-semibold">{String(value ?? "—")}</dd></div>)}</dl></Modal>}
  </>;
}
