import { useEffect, useState } from "react";
import api, { messageFrom } from "../services/api";
import { Empty, ErrorBox, Loading, Modal, PageHeader, Pagination, Status } from "../components/UI";
import { useAuth } from "../context/AuthContext";

export default function Kyc() {
  const { user } = useAuth(); const staff = ["ADMIN", "MANAGER"].includes(user.role); const [data, setData] = useState(null); const [form, setForm] = useState({ documentType: "NID", documentReference: "" }); const [review, setReview] = useState(null); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false); const [page, setPage] = useState(1);
  async function load() { try { const response = await api.get("/kyc", { params: { page, pageSize: 10 } }); setData(response.data); const pending = response.data.items?.find((item) => item.STATUS === "PENDING"); if (pending && user.role === "CUSTOMER") setForm({ documentType: pending.DOCUMENT_TYPE || "NID", documentReference: pending.DOCUMENT_REFERENCE || "" }); setError(""); } catch (requestError) { setError(messageFrom(requestError)); } }
  useEffect(() => { load(); }, [page]); // eslint-disable-line react-hooks/exhaustive-deps
  async function submit(event) { event.preventDefault(); if (busy) return; setBusy(true); try { await api.post("/kyc", form); setNotice("KYC submission saved."); await load(); } catch (requestError) { setError(messageFrom(requestError)); } finally { setBusy(false); } }
  async function decide(decision) { if (busy) return; const rejectionReason = decision === "REJECTED" ? window.prompt("Required rejection reason") : ""; if (decision === "REJECTED" && !rejectionReason?.trim()) return; setBusy(true); try { await api.post(`/kyc/${review.KYC_ID}/review`, { decision, rejectionReason }); setReview(null); setNotice("KYC review saved."); await load(); } catch (requestError) { setError(messageFrom(requestError)); } finally { setBusy(false); } }
  if (!data && !error) return <Loading />;
  return <><PageHeader title="Customer KYC" subtitle={staff ? "Review KYC records within your authorization scope." : "Submit identity reference details for academic KYC review."} />{notice && <div className="mb-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</div>}<ErrorBox message={error} />{user.role === "CUSTOMER" && <form className="card mb-5 grid gap-4 sm:grid-cols-3" onSubmit={submit}><label className="field">Document type<select value={form.documentType} onChange={(event) => setForm({ ...form, documentType: event.target.value })}><option>NID</option><option>PASSPORT</option><option>DRIVING_LICENSE</option></select></label><label className="field sm:col-span-2">Document reference<input required value={form.documentReference} onChange={(event) => setForm({ ...form, documentReference: event.target.value })} /></label><button className="btn-primary sm:col-span-3" disabled={busy}>{busy ? "Saving…" : "Save pending KYC"}</button></form>}{!data?.items.length ? <Empty text="No KYC records found." /> : <div className="table-wrap"><table className="data-table"><thead><tr><th>Customer</th><th>Document</th><th>Reference</th><th>Status</th><th>Submitted</th><th>Review</th></tr></thead><tbody>{data.items.map((row) => <tr key={row.KYC_ID}><td>{row.CUSTOMER_NAME || "Your profile"}</td><td>{row.DOCUMENT_TYPE || "Pending submission"}</td><td>{row.DOCUMENT_REFERENCE || "—"}</td><td><Status value={row.STATUS} /></td><td>{new Date(row.SUBMITTED_AT).toLocaleString()}</td><td>{staff && row.STATUS === "PENDING" && <button className="text-blue-700" onClick={() => setReview(row)}>Review</button>}{row.STATUS === "REJECTED" && <span className="text-xs text-red-700">{row.REJECTION_REASON}</span>}</td></tr>)}</tbody></table></div>}{data && <Pagination page={data.page} pageSize={data.pageSize} total={data.total} onPage={setPage} />}{review && <Modal title={`Review KYC · ${review.CUSTOMER_NAME}`} onClose={() => setReview(null)}><p className="mb-4 text-sm text-slate-600">{review.DOCUMENT_TYPE}: {review.DOCUMENT_REFERENCE}</p><div className="flex gap-3"><button className="btn-primary" disabled={busy} onClick={() => decide("VERIFIED")}>Verify</button><button className="btn-secondary" disabled={busy} onClick={() => decide("REJECTED")}>Reject</button></div></Modal>}</>;
}
