import { useEffect, useState } from "react";
import api, { messageFrom } from "../services/api";
import { Empty, ErrorBox, Loading, Modal, PageHeader, Pagination, Status } from "../components/UI";
import { useAuth } from "../context/AuthContext";

const types = ["ACCOUNT_FREEZE", "ACCOUNT_UNFREEZE", "STATEMENT", "PROFILE_HELP", "BENEFICIARY_HELP", "LOAN_INFORMATION", "GENERAL_SUPPORT"];
export default function ServiceRequests() {
  const { user } = useAuth(); const [data, setData] = useState(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [modal, setModal] = useState(false); const [form, setForm] = useState({ requestType: "GENERAL_SUPPORT", subject: "", description: "" });
  async function load() { try { setData((await api.get("/service-requests", { params: { pageSize: 20 } })).data); setError(""); } catch (e) { setError(messageFrom(e)); } }
  useEffect(() => { load(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  async function create(event) { event.preventDefault(); if (busy) return; setBusy(true); try { await api.post("/service-requests", form); setModal(false); setForm({ requestType: "GENERAL_SUPPORT", subject: "", description: "" }); await load(); } catch (e) { setError(messageFrom(e)); } finally { setBusy(false); } }
  async function update(id, status) { if (busy) return; setBusy(true); try { await api.patch(`/service-requests/${id}/status`, { status }); await load(); } catch (e) { setError(messageFrom(e)); } finally { setBusy(false); } }
  async function assign(id) { if (busy) return; setBusy(true); try { await api.patch(`/service-requests/${id}/assign`, {}); await load(); } catch (e) { setError(messageFrom(e)); } finally { setBusy(false); } }
  if (!data && !error) return <Loading />;
  return <><PageHeader title="Service Requests" subtitle="Oracle-backed customer support queue; requests never directly change account state." action={user.role === "CUSTOMER" && <button className="btn-primary" onClick={() => setModal(true)}>New request</button>} /><ErrorBox message={error} />{!data?.items?.length ? <Empty text="No service requests found." /> : <div className="table-wrap"><table className="data-table"><thead><tr><th>Request</th><th>Customer</th><th>Type</th><th>Subject</th><th>Status</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{data.items.map((item) => <tr key={item.REQUEST_ID}><td className="font-mono">{item.REQUEST_NUMBER}</td><td>{item.CUSTOMER_NAME}</td><td>{item.REQUEST_TYPE.replaceAll("_", " ")}</td><td>{item.SUBJECT}</td><td><Status value={item.STATUS} /></td><td>{new Date(item.UPDATED_AT).toLocaleString()}</td><td className="flex gap-2">{user.role !== "CUSTOMER" && item.STATUS === "OPEN" && <button className="text-emerald-700" disabled={busy} onClick={() => assign(item.REQUEST_ID)}>Assign to me</button>}{user.role !== "CUSTOMER" && ["OPEN", "IN_PROGRESS"].includes(item.STATUS) && <button className="text-blue-700" disabled={busy} onClick={() => update(item.REQUEST_ID, "RESOLVED")}>Resolve</button>}{user.role === "CUSTOMER" && item.STATUS === "OPEN" && <button className="text-red-700" disabled={busy} onClick={() => update(item.REQUEST_ID, "CANCELLED")}>Cancel</button>}</td></tr>)}</tbody></table></div>}{data && <Pagination page={data.page} pageSize={data.pageSize} total={data.total} onPage={() => {}} />}{modal && <Modal title="New service request" onClose={() => !busy && setModal(false)}><form className="space-y-4" onSubmit={create}><label className="field">Request type<select value={form.requestType} onChange={(e) => setForm({ ...form, requestType: e.target.value })}>{types.map((type) => <option key={type}>{type}</option>)}</select></label><label className="field">Subject<input required maxLength={160} value={form.subject} onChange={(e) => setForm({ ...form, subject: e.target.value })} /></label><label className="field">Description<textarea required rows="4" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><button className="btn-primary" disabled={busy}>{busy ? "Submitting…" : "Submit request"}</button></form></Modal>}</>;
}
