import { useEffect, useState } from "react";
import { Download, Printer, RefreshCw } from "lucide-react";
import api, { messageFrom } from "../services/api";
import { Empty, ErrorBox, Loading, PageHeader, money } from "../components/UI";

function defaultDates() { const to = new Date(); const from = new Date(); from.setDate(to.getDate() - 30); return { from: from.toISOString().slice(0, 10), to: to.toISOString().slice(0, 10) }; }

export default function Statement() {
  const [accounts, setAccounts] = useState([]); const [accountNumber, setAccountNumber] = useState(""); const [dates, setDates] = useState(defaultDates); const [statement, setStatement] = useState(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { api.get("/accounts", { params: { pageSize: 100 } }).then((response) => { setAccounts(response.data.items || []); if (response.data.items?.[0]) setAccountNumber(response.data.items[0].ACCOUNT_NUMBER); }).catch((requestError) => setError(messageFrom(requestError))); }, []);
  async function generate(event) { event?.preventDefault(); if (busy || !accountNumber) return; setBusy(true); try { const response = await api.get("/statements", { params: { accountNumber, ...dates } }); setStatement(response.data); setError(""); } catch (requestError) { setError(messageFrom(requestError)); } finally { setBusy(false); } }
  async function exportCsv() { try { const response = await api.get("/statements", { params: { accountNumber, ...dates, format: "csv" }, responseType: "blob" }); const url = URL.createObjectURL(response.data); const link = document.createElement("a"); link.href = url; link.download = `statement-${accountNumber}.csv`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); } catch (requestError) { setError(messageFrom(requestError)); } }
  if (!accounts.length && !error) return <Loading />;
  return <><PageHeader title="Bank Statement" subtitle="Stored transaction balances with server-side account ownership checks" action={<div className="flex gap-2"><button className="btn-secondary" disabled={!statement} onClick={exportCsv}><Download size={16} /> CSV</button><button className="btn-secondary" disabled={!statement} onClick={() => window.print()}><Printer size={16} /> Print</button></div>} /><ErrorBox message={error} /><form className="card mb-5 grid gap-4 sm:grid-cols-4" onSubmit={generate}><label className="field sm:col-span-2">Account<select required value={accountNumber} onChange={(event) => setAccountNumber(event.target.value)}><option value="">Select account</option>{accounts.map((account) => <option key={account.ACCOUNT_NUMBER} value={account.ACCOUNT_NUMBER}>{account.ACCOUNT_NUMBER} · {account.CUSTOMER_NAME || "Account"}</option>)}</select></label><label className="field">From date<input required type="date" value={dates.from} onChange={(event) => setDates({ ...dates, from: event.target.value })} /></label><label className="field">To date<input required type="date" value={dates.to} onChange={(event) => setDates({ ...dates, to: event.target.value })} /></label><button className="btn-primary sm:col-span-4" disabled={busy || !accountNumber}>{busy ? "Generating…" : <><RefreshCw size={16} /> Generate statement</>}</button></form>
    {!statement ? <Empty text="Choose an account and date range to generate a statement." /> : <section className="statement-print"><div className="mb-5 grid gap-3 sm:grid-cols-5"><div className="card"><span className="text-xs text-slate-500">Opening</span><strong className="block text-lg">{money(statement.openingBalance)}</strong></div><div className="card"><span className="text-xs text-slate-500">Closing</span><strong className="block text-lg">{money(statement.closingBalance)}</strong></div><div className="card"><span className="text-xs text-slate-500">Credits</span><strong className="block text-lg text-emerald-700">{money(statement.totalCredit)}</strong></div><div className="card"><span className="text-xs text-slate-500">Debits</span><strong className="block text-lg text-red-700">{money(statement.totalDebit)}</strong></div><div className="card"><span className="text-xs text-slate-500">Transactions</span><strong className="block text-lg">{statement.transactionCount}</strong></div></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Date</th><th>Reference</th><th>Type</th><th>Credit</th><th>Debit</th><th>Running balance</th><th>Status</th></tr></thead><tbody>{statement.rows.map((row) => <tr key={row.TRANSACTION_ID}><td>{new Date(row.TRANSACTION_DATE).toLocaleString()}</td><td>{row.REFERENCE_NO}</td><td>{row.TRANSACTION_TYPE.replaceAll("_", " ")}</td><td className="text-emerald-700">{Number(row.CREDIT) ? money(row.CREDIT) : "—"}</td><td className="text-red-700">{Number(row.DEBIT) ? money(row.DEBIT) : "—"}</td><td>{money(row.RUNNING_BALANCE)}</td><td>{row.STATUS}</td></tr>)}</tbody></table></div></section>}
  </>;
}
