import { useEffect, useState } from "react";
import { KeyRound, LockKeyhole, Plus, Search, ShieldCheck, UnlockKeyhole } from "lucide-react";
import api, { messageFrom } from "../services/api";
import { Empty, ErrorBox, Loading, Modal, PageHeader, Pagination, Status } from "../components/UI";
import { useAuth } from "../context/AuthContext";

const emptyForm = { employeeId: "", role: "EMPLOYEE", username: "", temporaryPassword: "", confirmTemporaryPassword: "", isActive: true, forcePasswordChange: true };

export default function UserManagement() {
  const { user } = useAuth();
  const [data, setData] = useState(null); const [employees, setEmployees] = useState([]); const [filters, setFilters] = useState({ search: "", role: "", active: "", branchId: "", page: 1 });
  const [form, setForm] = useState(emptyForm); const [modal, setModal] = useState(null); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false); const [details, setDetails] = useState(null);
  const canManage = ["ADMIN", "MANAGER"].includes(user.role);
  async function load() { try { const query = new URLSearchParams({ ...filters, pageSize: 10 }); Object.keys(filters).forEach((key) => !filters[key] && query.delete(key)); const result = await api.get(`/staff/users?${query}`); setData(result.data); setError(""); } catch (requestError) { setError(messageFrom(requestError)); } }
  async function loadEmployees() { try { const result = await api.get("/staff/users/eligible-employees"); setEmployees(result.data); } catch (requestError) { setError(messageFrom(requestError)); } }
  useEffect(() => { if (canManage) load(); }, [filters, canManage]); // eslint-disable-line react-hooks/exhaustive-deps
  function filterChange(key, value) { setFilters((current) => ({ ...current, [key]: value, page: key === "page" ? value : 1 })); }
  async function create(event) { event.preventDefault(); if (busy) return; setBusy(true); try { await api.post("/staff/users", form); setNotice("Staff login created without exposing the temporary password."); setModal(null); setForm(emptyForm); await load(); } catch (requestError) { setError(messageFrom(requestError)); } finally { setBusy(false); } }
  async function action(path, payload, message) { if (busy) return; setBusy(true); try { await api[path.method || "post"](path.url, payload); setNotice(message); await load(); } catch (requestError) { setError(messageFrom(requestError)); } finally { setBusy(false); } }
  async function toggle(row) { const next = row.IS_ACTIVE === "Y" ? "N" : "Y"; if (!window.confirm(`${next === "Y" ? "Activate" : "Deactivate"} ${row.USERNAME}?`)) return; await action({ url: `/staff/users/${row.USER_ID}/status` }, { status: next }, "Account status updated."); }
  async function reset(row) { const password = window.prompt("Enter a temporary password (10+ characters). It will not be displayed again."); if (!password) return; const confirmPassword = window.prompt("Confirm the temporary password."); if (password !== confirmPassword) { setError("Temporary passwords do not match."); return; } await action({ url: `/staff/users/${row.USER_ID}/reset-password` }, { temporaryPassword: password, confirmTemporaryPassword: confirmPassword }, "Password reset; the user must change it at first login."); }
  if (!canManage) return <ErrorBox message="You do not have permission to access User Management." />;
  if (!data && !error) return <Loading />;
  return <>
    <PageHeader title="User Management" subtitle="Manage staff login accounts without exposing password material." action={<button className="btn-primary" disabled={busy} onClick={() => { loadEmployees(); setModal("create"); }}><Plus size={17} /> Create Login Account</button>} />
    {notice && <div className="mb-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700" role="status">{notice}</div>}<ErrorBox message={error} />
    <section className="card mb-5"><div className="grid gap-3 md:grid-cols-4"><label className="field md:col-span-2"><span className="sr-only">Search users</span><span className="flex items-center gap-2"><Search size={16} /><input placeholder="Username, employee name or code" value={filters.search} onChange={(event) => filterChange("search", event.target.value)} /></span></label><label className="field">Role<select value={filters.role} onChange={(event) => filterChange("role", event.target.value)}><option value="">All roles</option>{["ADMIN", "MANAGER", "EMPLOYEE", "CUSTOMER"].map((role) => <option key={role}>{role}</option>)}</select></label><label className="field">Status<select value={filters.active} onChange={(event) => filterChange("active", event.target.value)}><option value="">All statuses</option><option value="Y">Active</option><option value="N">Inactive</option></select></label></div></section>
    {!data?.items?.length ? <Empty text="No user accounts match these filters." /> : <div className="table-wrap"><table className="data-table"><thead><tr><th>Username</th><th>Role</th><th>Employee / branch</th><th>Status</th><th>Failed logins</th><th>Last login</th><th>Actions</th></tr></thead><tbody>{data.items.map((row) => <tr key={row.USER_ID}><td className="font-semibold">{row.USERNAME}</td><td><Status value={row.ROLE} /></td><td>{row.EMPLOYEE_NAME || row.CUSTOMER_NAME || "System"}<span className="block text-xs text-slate-500">{row.BRANCH_NAME || "Global"}{row.EMPLOYEE_CODE ? ` Ã‚Â· ${row.EMPLOYEE_CODE}` : ""}</span></td><td><Status value={row.IS_ACTIVE === "Y" ? "ACTIVE" : "INACTIVE"} />{row.ACCOUNT_LOCKED === "Y" && <span className="ml-1 text-xs text-red-600">Locked</span>}</td><td>{row.FAILED_LOGIN_COUNT}</td><td>{row.LAST_LOGIN ? new Date(row.LAST_LOGIN).toLocaleString() : "Never"}</td><td><div className="flex flex-wrap gap-2 text-sm"><button className="text-blue-700" disabled={busy} onClick={async () => { try { setDetails((await api.get(`/staff/users/${row.USER_ID}`)).data); } catch (requestError) { setError(messageFrom(requestError)); } }}>View</button>{row.ROLE !== "CUSTOMER" && <><button className="text-amber-700" disabled={busy} onClick={() => toggle(row)}>{row.IS_ACTIVE === "Y" ? "Deactivate" : "Activate"}</button><button className="text-violet-700" disabled={busy} onClick={() => reset(row)}><KeyRound size={14} className="inline" /> Reset</button>{row.ACCOUNT_LOCKED === "Y" && <button className="text-emerald-700" disabled={busy} onClick={() => action({ url: `/staff/users/${row.USER_ID}/unlock` }, null, "Account unlocked.")}><UnlockKeyhole size={14} className="inline" /> Unlock</button>}</>}</div></td></tr>)}</tbody></table></div>}
    {data && <Pagination page={data.page} pageSize={data.pageSize} total={data.total} onPage={(page) => filterChange("page", page)} />}
    {modal === "create" && <Modal title="Create staff login" onClose={() => !busy && setModal(null)}><form onSubmit={create} className="grid gap-4"><label className="field">Eligible employee<select required value={form.employeeId} onChange={(event) => setForm({ ...form, employeeId: event.target.value })}><option value="">Select an employee</option>{employees.map((employee) => <option key={employee.EMPLOYEE_ID} value={employee.EMPLOYEE_ID}>{employee.EMPLOYEE_CODE} Ã‚Â· {employee.EMPLOYEE_NAME} Ã‚Â· {employee.BRANCH_NAME} Ã‚Â· {employee.JOB_TITLE}</option>)}</select></label><div className="rounded-lg bg-slate-50 p-3 text-xs text-slate-600">Only active employees without an existing login are shown. Managers receive only their own-branch employees.</div><label className="field">Role<select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })}><option value="EMPLOYEE">Employee</option>{user.role === "ADMIN" && <><option value="MANAGER">Manager</option><option value="ADMIN">Admin</option></>}</select></label><label className="field">Username<input required minLength="4" value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value })} /></label><label className="field">Temporary password<input required minLength="10" type="password" value={form.temporaryPassword} onChange={(event) => setForm({ ...form, temporaryPassword: event.target.value })} /></label><label className="field">Confirm temporary password<input required minLength="10" type="password" value={form.confirmTemporaryPassword} onChange={(event) => setForm({ ...form, confirmTemporaryPassword: event.target.value })} /></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.isActive} onChange={(event) => setForm({ ...form, isActive: event.target.checked })} /> Account active</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.forcePasswordChange} onChange={(event) => setForm({ ...form, forcePasswordChange: event.target.checked })} /> Force password change on first login</label><button className="btn-primary" disabled={busy}>{busy ? "CreatingÃ¢â‚¬Â¦" : "Create login"}</button></form></Modal>}
    {details && <Modal title={`User details Ã‚Â· ${details.USERNAME}`} onClose={() => setDetails(null)}><dl className="grid gap-3 text-sm sm:grid-cols-2">{[["Username", details.USERNAME], ["Role", details.ROLE], ["Employee", details.EMPLOYEE_NAME || details.CUSTOMER_NAME || "System"], ["Branch", details.BRANCH_NAME || "Global"], ["Failed logins", details.FAILED_LOGIN_COUNT], ["Last login", details.LAST_LOGIN ? new Date(details.LAST_LOGIN).toLocaleString() : "Never"], ["Password change", details.MUST_CHANGE_PASSWORD === "Y" ? "Required" : "Not required"], ["Account", details.IS_ACTIVE === "Y" ? "Active" : "Inactive"]].map(([label, value]) => <div key={label}><dt className="text-xs uppercase text-slate-500">{label}</dt><dd className="font-semibold">{value}</dd></div>)}</dl><div className="mt-5 flex gap-2 text-sm"><LockKeyhole size={17} className="text-emerald-600" /> Password hashes and temporary passwords are never returned.</div><ShieldCheck size={18} className="mt-4 text-emerald-600" /></Modal>}
  </>;
}
