-- Non-destructive Phase 1 upgrade. Run as the BANK_APP schema owner.
-- It adds only staff-login lifecycle metadata and login history.
SET SERVEROUTPUT ON
DECLARE
  PROCEDURE add_column(p_sql VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-1430, -2260) THEN RAISE; END IF;
  END;
  PROCEDURE add_index(p_sql VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
  END;
BEGIN
  add_column('ALTER TABLE users ADD (must_change_password CHAR(1) DEFAULT ''N'' NOT NULL)');
  add_column('ALTER TABLE users ADD (account_locked CHAR(1) DEFAULT ''N'' NOT NULL)');
  add_column('ALTER TABLE users ADD (locked_at TIMESTAMP)');
  add_column('ALTER TABLE users ADD (password_changed_at TIMESTAMP)');
  add_column('ALTER TABLE users ADD (updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)');
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE users ADD CONSTRAINT ck_users_must_change CHECK (must_change_password IN (''Y'',''N''))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-2260, -2275) THEN RAISE; END IF; END;
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE users ADD CONSTRAINT ck_users_locked CHECK (account_locked IN (''Y'',''N''))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-2260, -2275) THEN RAISE; END IF; END;
  BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE login_history (login_history_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_login_history PRIMARY KEY, user_id NUMBER CONSTRAINT fk_login_history_user REFERENCES users(user_id), attempted_username VARCHAR2(50) NOT NULL, success_flag CHAR(1) NOT NULL CONSTRAINT ck_login_history_success CHECK (success_flag IN (''Y'',''N'')), event_type VARCHAR2(20) DEFAULT ''LOGIN'' NOT NULL, failure_reason VARCHAR2(100), occurred_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)';
  EXCEPTION WHEN OTHERS THEN IF SQLCODE <> -955 THEN RAISE; END IF;
  END;
  add_index('CREATE INDEX idx_users_username_lower ON users(LOWER(username))');
  add_index('CREATE INDEX idx_users_role_active ON users(role,is_active,account_locked)');
  add_index('CREATE INDEX idx_users_employee ON users(employee_id)');
  add_index('CREATE INDEX idx_login_history_user_date ON login_history(user_id,occurred_at DESC)');
  add_index('CREATE INDEX idx_login_history_attempt_date ON login_history(attempted_username,occurred_at DESC)');
  DBMS_OUTPUT.PUT_LINE('Phase 1 staff-login upgrade complete.');
END;
/
SELECT name,type,line,position,text FROM user_errors ORDER BY name,sequence;
