-- Non-destructive Phase 2 upgrade. Run as the BANK_APP schema owner.
-- It preserves existing ledger rows and adds only compensating-ledger metadata,
-- customer tools, and supporting indexes.
SET SERVEROUTPUT ON
DECLARE
  PROCEDURE exec_ignore(p_sql VARCHAR2, p_codes SYS.ODCINUMBERLIST) IS
    v_ignored BOOLEAN := FALSE;
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION WHEN OTHERS THEN
    FOR i IN 1..p_codes.COUNT LOOP IF SQLCODE=p_codes(i) THEN v_ignored:=TRUE; END IF; END LOOP;
    IF NOT v_ignored THEN RAISE; END IF;
  END;
BEGIN
  exec_ignore('ALTER TABLE transactions DROP CONSTRAINT ck_transaction_type', SYS.ODCINUMBERLIST(-2443));
  exec_ignore('ALTER TABLE transactions ADD CONSTRAINT ck_transaction_type CHECK (transaction_type IN (''DEPOSIT'',''WITHDRAWAL'',''TRANSFER_DEBIT'',''TRANSFER_CREDIT'',''LOAN_DISBURSEMENT'',''LOAN_PAYMENT'',''REVERSAL_DEBIT'',''REVERSAL_CREDIT''))', SYS.ODCINUMBERLIST(-2260,-2275));
  exec_ignore('CREATE TABLE transaction_reversals (reversal_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_transaction_reversals PRIMARY KEY,original_transaction_id NUMBER NOT NULL CONSTRAINT fk_reversal_original REFERENCES transactions(transaction_id),reversal_transaction_id NUMBER NOT NULL CONSTRAINT fk_reversal_transaction REFERENCES transactions(transaction_id),reason VARCHAR2(500) NOT NULL,reversed_by NUMBER CONSTRAINT fk_reversal_user REFERENCES users(user_id),reversed_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,status VARCHAR2(12) DEFAULT ''COMPLETED'' NOT NULL CONSTRAINT ck_reversal_status CHECK (status IN (''COMPLETED'',''FAILED'')),CONSTRAINT uk_reversal_original UNIQUE(original_transaction_id),CONSTRAINT uk_reversal_transaction UNIQUE(reversal_transaction_id))', SYS.ODCINUMBERLIST(-955));
  exec_ignore('CREATE TABLE user_preferences (user_id NUMBER CONSTRAINT pk_user_preferences PRIMARY KEY REFERENCES users(user_id),theme VARCHAR2(10) DEFAULT ''SYSTEM'' NOT NULL CONSTRAINT ck_preferences_theme CHECK (theme IN (''LIGHT'',''DARK'',''SYSTEM'')),rows_per_page NUMBER DEFAULT 20 NOT NULL CONSTRAINT ck_preferences_rows CHECK (rows_per_page BETWEEN 5 AND 100),currency_display VARCHAR2(3) DEFAULT ''BDT'' NOT NULL CONSTRAINT ck_preferences_currency CHECK (currency_display=''BDT''),notifications_enabled CHAR(1) DEFAULT ''Y'' NOT NULL CONSTRAINT ck_preferences_notifications CHECK (notifications_enabled IN (''Y'',''N'')),updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)', SYS.ODCINUMBERLIST(-955));
  exec_ignore('CREATE TABLE beneficiaries (beneficiary_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_beneficiaries PRIMARY KEY,customer_id NUMBER NOT NULL CONSTRAINT fk_beneficiary_customer REFERENCES customers(customer_id),source_account_id NUMBER NOT NULL CONSTRAINT fk_beneficiary_source REFERENCES accounts(account_id),beneficiary_account_id NUMBER NOT NULL CONSTRAINT fk_beneficiary_target REFERENCES accounts(account_id),nickname VARCHAR2(100) NOT NULL,status VARCHAR2(12) DEFAULT ''ACTIVE'' NOT NULL CONSTRAINT ck_beneficiary_status CHECK (status IN (''ACTIVE'',''INACTIVE'')),created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,CONSTRAINT ck_beneficiary_different CHECK (source_account_id<>beneficiary_account_id))', SYS.ODCINUMBERLIST(-955));
  exec_ignore('CREATE TABLE customer_kyc (kyc_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_customer_kyc PRIMARY KEY,customer_id NUMBER NOT NULL CONSTRAINT fk_kyc_customer REFERENCES customers(customer_id),document_type VARCHAR2(40),document_reference VARCHAR2(100),status VARCHAR2(12) DEFAULT ''PENDING'' NOT NULL CONSTRAINT ck_kyc_status CHECK (status IN (''PENDING'',''VERIFIED'',''REJECTED'')),submitted_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,reviewed_by NUMBER CONSTRAINT fk_kyc_reviewer REFERENCES users(user_id),reviewed_at TIMESTAMP,rejection_reason VARCHAR2(500),updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)', SYS.ODCINUMBERLIST(-955));
  exec_ignore('CREATE INDEX idx_reversal_original ON transaction_reversals(original_transaction_id)', SYS.ODCINUMBERLIST(-955,-1408));
  exec_ignore('CREATE INDEX idx_reversal_date ON transaction_reversals(reversed_at DESC)', SYS.ODCINUMBERLIST(-955,-1408));
  exec_ignore('CREATE INDEX idx_beneficiary_customer_status ON beneficiaries(customer_id,status,updated_at DESC)', SYS.ODCINUMBERLIST(-955,-1408));
  exec_ignore('CREATE INDEX idx_beneficiary_source ON beneficiaries(source_account_id,status)', SYS.ODCINUMBERLIST(-955,-1408));
  exec_ignore('CREATE UNIQUE INDEX uk_beneficiary_active ON beneficiaries(CASE WHEN status=''ACTIVE'' THEN customer_id END,CASE WHEN status=''ACTIVE'' THEN source_account_id END,CASE WHEN status=''ACTIVE'' THEN beneficiary_account_id END)', SYS.ODCINUMBERLIST(-955,-1408));
  exec_ignore('CREATE INDEX idx_kyc_customer_status ON customer_kyc(customer_id,status,updated_at DESC)', SYS.ODCINUMBERLIST(-955,-1408));
  exec_ignore('CREATE INDEX idx_kyc_status_date ON customer_kyc(status,submitted_at DESC)', SYS.ODCINUMBERLIST(-955,-1408));
  DBMS_OUTPUT.PUT_LINE('Phase 2 customer-tools upgrade complete.');
END;
/
SELECT name,type,line,position,text FROM user_errors ORDER BY name,sequence;
-- Recompile the maintained package/view sources after the DDL upgrade:
@@../sql/11_packages.sql
@@../sql/04_views.sql
