-- Non-destructive Phase 3 upgrade. Run as the BANK_APP schema owner.
-- This adds educational schemes/quotations only; it never posts money or changes balances.
SET SERVEROUTPUT ON
DECLARE
  PROCEDURE exec_ignore(p_sql VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
  END;
BEGIN
  exec_ignore('CREATE TABLE deposit_schemes (scheme_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_deposit_schemes PRIMARY KEY,scheme_code VARCHAR2(20) NOT NULL CONSTRAINT uk_deposit_scheme_code UNIQUE,scheme_name VARCHAR2(100) NOT NULL CONSTRAINT uk_deposit_scheme_name UNIQUE,scheme_type VARCHAR2(30) NOT NULL CONSTRAINT ck_deposit_scheme_type CHECK (scheme_type IN (''FIXED_DEPOSIT'',''MONTHLY_PROFIT'',''DPS'',''SAVINGS_PROFIT'',''SENIOR_CITIZEN'',''STUDENT_SAVINGS'')),minimum_amount NUMBER(15,2) NOT NULL CONSTRAINT ck_deposit_scheme_min CHECK (minimum_amount > 0),maximum_amount NUMBER(15,2),minimum_months NUMBER NOT NULL,maximum_months NUMBER NOT NULL,annual_profit_rate NUMBER(7,4) NOT NULL CONSTRAINT ck_deposit_scheme_rate CHECK (annual_profit_rate BETWEEN 0 AND 100),calculation_method VARCHAR2(20) DEFAULT ''SIMPLE'' NOT NULL CONSTRAINT ck_deposit_scheme_method CHECK (calculation_method IN (''SIMPLE'',''MONTHLY_COMPOUND'')),payment_frequency VARCHAR2(20) DEFAULT ''AT_MATURITY'' NOT NULL CONSTRAINT ck_deposit_scheme_frequency CHECK (payment_frequency IN (''AT_MATURITY'',''MONTHLY'',''RECURRING'')),tax_percentage NUMBER(5,2) DEFAULT 0 NOT NULL CONSTRAINT ck_deposit_scheme_tax CHECK (tax_percentage BETWEEN 0 AND 100),early_withdrawal_rate NUMBER(7,4),senior_only CHAR(1) DEFAULT ''N'' NOT NULL,student_only CHAR(1) DEFAULT ''N'' NOT NULL,status VARCHAR2(12) DEFAULT ''ACTIVE'' NOT NULL,created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)');
  exec_ignore('CREATE TABLE deposit_certificates (certificate_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_deposit_certificates PRIMARY KEY,certificate_number VARCHAR2(40) NOT NULL CONSTRAINT uk_certificate_number UNIQUE,customer_id NUMBER NOT NULL CONSTRAINT fk_certificate_customer REFERENCES customers(customer_id),account_id NUMBER CONSTRAINT fk_certificate_account REFERENCES accounts(account_id),scheme_id NUMBER NOT NULL CONSTRAINT fk_certificate_scheme REFERENCES deposit_schemes(scheme_id),principal_amount NUMBER(15,2) NOT NULL,annual_profit_rate NUMBER(7,4) NOT NULL,duration_months NUMBER NOT NULL,calculation_method VARCHAR2(20) NOT NULL,tax_percentage NUMBER(5,2) DEFAULT 0 NOT NULL,expected_gross_profit NUMBER(15,2) NOT NULL,expected_tax NUMBER(15,2) NOT NULL,expected_net_profit NUMBER(15,2) NOT NULL,expected_maturity_amount NUMBER(15,2) NOT NULL,opening_date DATE NOT NULL,maturity_date DATE NOT NULL,status VARCHAR2(24) DEFAULT ''QUOTATION'' NOT NULL,created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)');
  exec_ignore('CREATE INDEX idx_deposit_scheme_status ON deposit_schemes(status,scheme_type)');
  exec_ignore('CREATE INDEX idx_certificate_customer_status ON deposit_certificates(customer_id,status,maturity_date)');
  exec_ignore('CREATE INDEX idx_certificate_account ON deposit_certificates(account_id,status)');
  exec_ignore('CREATE INDEX idx_certificate_maturity ON deposit_certificates(maturity_date,status)');
  exec_ignore('ALTER TABLE deposit_schemes ADD CONSTRAINT ck_deposit_scheme_type CHECK (scheme_type IN (''FIXED_DEPOSIT'',''MONTHLY_PROFIT'',''DPS'',''SAVINGS_PROFIT'',''SENIOR_CITIZEN'',''STUDENT_SAVINGS''))');
  exec_ignore('ALTER TABLE deposit_schemes ADD CONSTRAINT ck_deposit_scheme_rate CHECK (annual_profit_rate BETWEEN 0 AND 100)');
  exec_ignore('ALTER TABLE deposit_schemes ADD CONSTRAINT ck_deposit_scheme_method CHECK (calculation_method IN (''SIMPLE'',''MONTHLY_COMPOUND''))');
  exec_ignore('ALTER TABLE deposit_schemes ADD CONSTRAINT ck_deposit_scheme_frequency CHECK (payment_frequency IN (''AT_MATURITY'',''MONTHLY'',''RECURRING''))');
  exec_ignore('ALTER TABLE deposit_schemes ADD CONSTRAINT ck_deposit_scheme_tax CHECK (tax_percentage BETWEEN 0 AND 100)');
  exec_ignore('ALTER TABLE deposit_schemes ADD CONSTRAINT ck_deposit_scheme_senior CHECK (senior_only IN (''Y'',''N''))');
  exec_ignore('ALTER TABLE deposit_schemes ADD CONSTRAINT ck_deposit_scheme_student CHECK (student_only IN (''Y'',''N''))');
  exec_ignore('ALTER TABLE deposit_schemes ADD CONSTRAINT ck_deposit_scheme_status CHECK (status IN (''ACTIVE'',''INACTIVE''))');
  exec_ignore('ALTER TABLE deposit_schemes ADD CONSTRAINT ck_deposit_scheme_months CHECK (minimum_months > 0 AND maximum_months >= minimum_months)');
  exec_ignore('ALTER TABLE deposit_schemes ADD CONSTRAINT ck_deposit_scheme_max CHECK (maximum_amount IS NULL OR maximum_amount >= minimum_amount)');
  exec_ignore('ALTER TABLE deposit_certificates ADD CONSTRAINT ck_certificate_principal CHECK (principal_amount > 0)');
  exec_ignore('ALTER TABLE deposit_certificates ADD CONSTRAINT ck_certificate_rate CHECK (annual_profit_rate BETWEEN 0 AND 100)');
  exec_ignore('ALTER TABLE deposit_certificates ADD CONSTRAINT ck_certificate_duration CHECK (duration_months > 0)');
  exec_ignore('ALTER TABLE deposit_certificates ADD CONSTRAINT ck_certificate_method CHECK (calculation_method IN (''SIMPLE'',''MONTHLY_COMPOUND''))');
  exec_ignore('ALTER TABLE deposit_certificates ADD CONSTRAINT ck_certificate_tax CHECK (tax_percentage BETWEEN 0 AND 100)');
  exec_ignore('ALTER TABLE deposit_certificates ADD CONSTRAINT ck_certificate_status CHECK (status IN (''QUOTATION'',''ACTIVE'',''MATURED'',''CLOSED'',''PREMATURELY_CLOSED'',''BLOCKED''))');
  exec_ignore('ALTER TABLE deposit_certificates ADD CONSTRAINT ck_certificate_dates CHECK (maturity_date >= opening_date)');
  INSERT INTO deposit_schemes(scheme_code,scheme_name,scheme_type,minimum_amount,maximum_amount,minimum_months,maximum_months,annual_profit_rate,calculation_method,payment_frequency,tax_percentage,early_withdrawal_rate) SELECT 'FD-SIMPLE','Classroom Fixed Deposit','FIXED_DEPOSIT',10000,5000000,3,36,8,'SIMPLE','AT_MATURITY',10,3 FROM dual WHERE NOT EXISTS (SELECT 1 FROM deposit_schemes WHERE scheme_code='FD-SIMPLE');
  INSERT INTO deposit_schemes(scheme_code,scheme_name,scheme_type,minimum_amount,maximum_amount,minimum_months,maximum_months,annual_profit_rate,calculation_method,payment_frequency,tax_percentage,early_withdrawal_rate) SELECT 'FD-COMPOUND','Monthly Compound Deposit','MONTHLY_PROFIT',10000,5000000,6,36,8.5,'MONTHLY_COMPOUND','AT_MATURITY',10,3 FROM dual WHERE NOT EXISTS (SELECT 1 FROM deposit_schemes WHERE scheme_code='FD-COMPOUND');
  INSERT INTO deposit_schemes(scheme_code,scheme_name,scheme_type,minimum_amount,maximum_amount,minimum_months,maximum_months,annual_profit_rate,calculation_method,payment_frequency,tax_percentage,early_withdrawal_rate) SELECT 'DPS-EDU','Educational DPS','DPS',500,100000,12,36,7.25,'MONTHLY_COMPOUND','RECURRING',5,2 FROM dual WHERE NOT EXISTS (SELECT 1 FROM deposit_schemes WHERE scheme_code='DPS-EDU');
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Phase 3 deposit-profit upgrade complete.');
END;
/
SELECT name,type,line,position,text FROM user_errors ORDER BY name,sequence;
