-- Non-destructive Phase 2 upgrade. Adds notifications and customer service requests.
DECLARE
  PROCEDURE create_if_missing(p_sql VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION WHEN OTHERS THEN
    IF SQLCODE <> -955 THEN RAISE; END IF;
  END;
BEGIN
  create_if_missing(q'[CREATE TABLE notifications (
    notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_notifications PRIMARY KEY,
    user_id NUMBER NOT NULL CONSTRAINT fk_notification_user REFERENCES users(user_id),
    event_type VARCHAR2(40) NOT NULL, title VARCHAR2(160) NOT NULL, message VARCHAR2(1000) NOT NULL,
    entity_type VARCHAR2(40), entity_id NUMBER, is_read CHAR(1) DEFAULT 'N' NOT NULL CONSTRAINT ck_notification_read CHECK (is_read IN ('Y','N')),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, read_at TIMESTAMP) ]');
  create_if_missing(q'[CREATE TABLE service_requests (
    request_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_service_requests PRIMARY KEY,
    request_number VARCHAR2(30) NOT NULL CONSTRAINT uk_service_request_number UNIQUE,
    customer_id NUMBER NOT NULL CONSTRAINT fk_service_request_customer REFERENCES customers(customer_id),
    branch_id NUMBER NOT NULL CONSTRAINT fk_service_request_branch REFERENCES branches(branch_id),
    request_type VARCHAR2(30) NOT NULL CONSTRAINT ck_service_request_type CHECK (request_type IN ('ACCOUNT_FREEZE','ACCOUNT_UNFREEZE','STATEMENT','PROFILE_HELP','BENEFICIARY_HELP','LOAN_INFORMATION','GENERAL_SUPPORT')),
    subject VARCHAR2(160) NOT NULL, description VARCHAR2(1000) NOT NULL,
    status VARCHAR2(20) DEFAULT 'OPEN' NOT NULL CONSTRAINT ck_service_request_status CHECK (status IN ('OPEN','IN_PROGRESS','RESOLVED','REJECTED','CANCELLED')),
    assigned_to NUMBER CONSTRAINT fk_service_request_assignee REFERENCES employees(employee_id),
    resolution_note VARCHAR2(1000), created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, resolved_at TIMESTAMP) ]');
  create_if_missing('CREATE INDEX idx_notifications_user_read ON notifications(user_id,is_read,created_at DESC)');
  create_if_missing('CREATE INDEX idx_service_requests_customer ON service_requests(customer_id,status,updated_at DESC)');
  create_if_missing('CREATE INDEX idx_service_requests_branch ON service_requests(branch_id,status,updated_at DESC)');
  create_if_missing('CREATE INDEX idx_service_requests_assignee ON service_requests(assigned_to,status,updated_at DESC)');
  COMMIT;
END;
/
SELECT name,type,line,position,text FROM user_errors ORDER BY name,sequence;
