-- Non-destructive unified staff-principal migration.
-- It links every staff application user to an EMPLOYEES row and preserves
-- customer records, passwords, accounts, and ledger history.
SET SERVEROUTPUT ON

DECLARE
  PROCEDURE exec_ignore(p_sql VARCHAR2, p_codes SYS.ODCINUMBERLIST) IS
    v_ignored BOOLEAN := FALSE;
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION WHEN OTHERS THEN
    FOR i IN 1..p_codes.COUNT LOOP
      IF SQLCODE = p_codes(i) THEN v_ignored := TRUE; END IF;
    END LOOP;
    IF NOT v_ignored THEN RAISE; END IF;
  END;
  v_invalid NUMBER;
BEGIN
  exec_ignore(q'~CREATE TABLE bank_profile (
    profile_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_bank_profile PRIMARY KEY,
    bank_name VARCHAR2(120) NOT NULL, short_name VARCHAR2(40) NOT NULL CONSTRAINT uk_bank_profile_short_name UNIQUE,
    head_office_address VARCHAR2(240) NOT NULL, support_phone VARCHAR2(30) NOT NULL,
    support_email VARCHAR2(120) NOT NULL, website VARCHAR2(160), swift_code VARCHAR2(20),
    currency VARCHAR2(3) DEFAULT 'BDT' NOT NULL CONSTRAINT ck_bank_profile_currency CHECK (currency='BDT'),
    status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL CONSTRAINT ck_bank_profile_status CHECK (status IN ('ACTIVE','INACTIVE')),
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_bank_profile_singleton CHECK (profile_id=1)
  )~', SYS.ODCINUMBERLIST(-955));
  exec_ignore('ALTER TABLE users ADD (staff_code VARCHAR2(20))', SYS.ODCINUMBERLIST(-1430,-2260));
  exec_ignore('ALTER TABLE users ADD (display_name VARCHAR2(100))', SYS.ODCINUMBERLIST(-1430,-2260));
  exec_ignore('ALTER TABLE users DROP CONSTRAINT ck_user_principal', SYS.ODCINUMBERLIST(-2443));

  MERGE INTO bank_profile b USING (SELECT 1 profile_id FROM dual) s ON (b.profile_id=s.profile_id)
  WHEN MATCHED THEN UPDATE SET bank_name='Smart Bank Limited',short_name='Smart Bank',head_office_address='DEMO Head Office, Motijheel, Dhaka',support_phone='DEMO-09600-00000',support_email='support@example.test',website='https://smartbank.example.test',swift_code='DEMO-SBMS-000',currency='BDT',status='ACTIVE',updated_at=SYSTIMESTAMP
  WHEN NOT MATCHED THEN INSERT(profile_id,bank_name,short_name,head_office_address,support_phone,support_email,website,swift_code,currency,status) VALUES(1,'Smart Bank Limited','Smart Bank','DEMO Head Office, Motijheel, Dhaka','DEMO-09600-00000','support@example.test','https://smartbank.example.test','DEMO-SBMS-000','BDT','ACTIVE');

  MERGE INTO branches b USING (SELECT 'HO-001' branch_code FROM dual) s ON (b.branch_code=s.branch_code)
  WHEN MATCHED THEN UPDATE SET branch_name='Smart Bank Head Office',city='Dhaka',address='DEMO Head Office, Motijheel',phone='DEMO-02-0000',swift_code='DEMO-SBMS-HO',status='ACTIVE'
  WHEN NOT MATCHED THEN INSERT(branch_code,branch_name,city,address,phone,swift_code) VALUES('HO-001','Smart Bank Head Office','Dhaka','DEMO Head Office, Motijheel','DEMO-02-0000','DEMO-SBMS-HO');
  MERGE INTO branches b USING (SELECT 'DHK-001' branch_code FROM dual) s ON (b.branch_code=s.branch_code)
  WHEN MATCHED THEN UPDATE SET branch_name='Dhanmondi Main Branch',city='Dhaka',address='DEMO Campus Road, Dhanmondi',phone='DEMO-02-0001',swift_code='DEMO-SBMS-001',status='ACTIVE'
  WHEN NOT MATCHED THEN INSERT(branch_code,branch_name,city,address,phone,swift_code) VALUES('DHK-001','Dhanmondi Main Branch','Dhaka','DEMO Campus Road, Dhanmondi','DEMO-02-0001','DEMO-SBMS-001');
  MERGE INTO branches b USING (SELECT 'UTT-001' branch_code FROM dual) s ON (b.branch_code=s.branch_code)
  WHEN MATCHED THEN UPDATE SET branch_name='Uttara Branch',city='Dhaka',address='DEMO Sector 7, Uttara',phone='DEMO-02-0002',swift_code='DEMO-SBMS-002',status='ACTIVE'
  WHEN NOT MATCHED THEN INSERT(branch_code,branch_name,city,address,phone,swift_code) VALUES('UTT-001','Uttara Branch','Dhaka','DEMO Sector 7, Uttara','DEMO-02-0002','DEMO-SBMS-002');
  MERGE INTO branches b USING (SELECT 'CTG-001' branch_code FROM dual) s ON (b.branch_code=s.branch_code)
  WHEN MATCHED THEN UPDATE SET branch_name='Agrabad Branch',city='Chattogram',address='DEMO Commercial Area, Agrabad',phone='DEMO-02-0003',swift_code='DEMO-SBMS-003',status='ACTIVE'
  WHEN NOT MATCHED THEN INSERT(branch_code,branch_name,city,address,phone,swift_code) VALUES('CTG-001','Agrabad Branch','Chattogram','DEMO Commercial Area, Agrabad','DEMO-02-0003','DEMO-SBMS-003');
  MERGE INTO branches b USING (SELECT 'CHP-001' branch_code FROM dual) s ON (b.branch_code=s.branch_code)
  WHEN MATCHED THEN UPDATE SET branch_name='Chandpur Branch',city='Chandpur',address='DEMO River Road, Chandpur',phone='DEMO-02-0004',swift_code='DEMO-SBMS-004',status='ACTIVE'
  WHEN NOT MATCHED THEN INSERT(branch_code,branch_name,city,address,phone,swift_code) VALUES('CHP-001','Chandpur Branch','Chandpur','DEMO River Road, Chandpur','DEMO-02-0004','DEMO-SBMS-004');

  MERGE INTO employees e USING (
    SELECT 'A-ID-001' employee_code,'Mohammad' first_name,'Mrinmoy' last_name,'DEMO-EMP-NID-001' national_id,'System Administrator' job_title,'mohammad.mrinmoy@example.test' email,'DEMO-018-0101' phone,120000 salary,'HO-001' branch_code FROM dual UNION ALL
    SELECT 'A-ID-002','Sirajum','Monira','DEMO-EMP-NID-002','System Administrator','sirajum.monira@example.test','DEMO-018-0102',118000,'HO-001' FROM dual UNION ALL
    SELECT 'A-ID-003','Ashik','Uz-zaman','DEMO-EMP-NID-003','System Administrator','ashik.uzzaman@example.test','DEMO-018-0103',116000,'HO-001' FROM dual UNION ALL
    SELECT 'A-ID-004','Ikhteir','Asif','DEMO-EMP-NID-004','System Administrator','ikhteir.asif@example.test','DEMO-018-0104',114000,'HO-001' FROM dual UNION ALL
    SELECT 'M-ID-001','Mayen','Majumder','DEMO-EMP-NID-005','Project Supervisor / Branch Manager','mayen.majumder@example.test','DEMO-018-0105',90000,'DHK-001' FROM dual UNION ALL
    SELECT 'E-ID-001','Mashrur','Hasan','DEMO-EMP-NID-006','Senior Banking Officer','mashrur.hasan@example.test','DEMO-018-0106',55000,'DHK-001' FROM dual UNION ALL
    SELECT 'E-ID-002','Risha','Khan','DEMO-EMP-NID-007','Customer Service Officer','risha.khan@example.test','DEMO-018-0107',52000,'UTT-001' FROM dual UNION ALL
    SELECT 'E-ID-003','Samin','Hasan','DEMO-EMP-NID-008','Credit Officer','samin.hasan@example.test','DEMO-018-0108',56000,'CTG-001' FROM dual UNION ALL
    SELECT 'E-ID-004','Abrar','Karib','DEMO-EMP-NID-009','Service Officer','abrar.karib@example.test','DEMO-018-0109',51000,'CHP-001' FROM dual UNION ALL
    SELECT 'E-ID-005','Rakib','Hasan','DEMO-EMP-NID-010','Operations Officer','rakib.hasan@example.test','DEMO-018-0110',53000,'DHK-001' FROM dual UNION ALL
    SELECT 'E-ID-006','Prapto','Sorkar','DEMO-EMP-NID-011','Account Officer','prapto.sorkar@example.test','DEMO-018-0111',50000,'UTT-001' FROM dual UNION ALL
    SELECT 'E-ID-007','Sayba','Tasnim','DEMO-EMP-NID-012','Loan Officer','sayba.tasnim@example.test','DEMO-018-0112',54000,'CTG-001' FROM dual UNION ALL
    SELECT 'E-ID-008','Tasnia','Suborno','DEMO-EMP-NID-013','Customer Support Officer','tasnia.suborno@example.test','DEMO-018-0113',50000,'CHP-001' FROM dual
  ) s ON (e.employee_code=s.employee_code)
  WHEN MATCHED THEN UPDATE SET branch_id=(SELECT branch_id FROM branches WHERE branch_code=s.branch_code),first_name=s.first_name,last_name=s.last_name,national_id=s.national_id,job_title=s.job_title,email=s.email,phone=s.phone,salary=s.salary,status='ACTIVE'
  WHEN NOT MATCHED THEN INSERT(branch_id,employee_code,first_name,last_name,national_id,job_title,email,phone,salary,status) VALUES((SELECT branch_id FROM branches WHERE branch_code=s.branch_code),s.employee_code,s.first_name,s.last_name,s.national_id,s.job_title,s.email,s.phone,s.salary,'ACTIVE');

  UPDATE users SET username='admin.mrinmoy001',display_name='Mohammad Mrinmoy' WHERE LOWER(username)='admin' AND staff_code='A-ID-001' AND NOT EXISTS (SELECT 1 FROM users WHERE LOWER(username)='admin.mrinmoy001');
  UPDATE users SET username='mayen.majumder001',display_name='Mayen Majumder' WHERE LOWER(username)='manager' AND staff_code='M-ID-001' AND NOT EXISTS (SELECT 1 FROM users WHERE LOWER(username)='mayen.majumder001');
  UPDATE users SET username='mashrur.hasan001',display_name='Mashrur Hasan' WHERE LOWER(username)='employee' AND staff_code='E-ID-001' AND NOT EXISTS (SELECT 1 FROM users WHERE LOWER(username)='mashrur.hasan001');
  UPDATE users SET staff_code='A-ID-001',display_name='Mohammad Mrinmoy' WHERE role='ADMIN' AND LOWER(username) IN ('admin','admin.mrinmoy001') AND staff_code IS NULL;
  UPDATE users SET staff_code='A-ID-002',display_name='Sirajum Monira' WHERE role='ADMIN' AND LOWER(username)='admin.monira002' AND staff_code IS NULL;
  UPDATE users SET staff_code='A-ID-003',display_name='Ashik Uz-zaman' WHERE role='ADMIN' AND LOWER(username)='admin.ashik003' AND staff_code IS NULL;
  UPDATE users SET staff_code='A-ID-004',display_name='Ikhteir Asif' WHERE role='ADMIN' AND LOWER(username)='admin.asif004' AND staff_code IS NULL;
  UPDATE users u SET staff_code=(SELECT e.employee_code FROM employees e WHERE e.employee_id=u.employee_id),display_name=NVL(u.display_name,(SELECT e.first_name||' '||e.last_name FROM employees e WHERE e.employee_id=u.employee_id)) WHERE u.role IN ('ADMIN','MANAGER','EMPLOYEE') AND u.employee_id IS NOT NULL;
  UPDATE users u SET employee_id=(SELECT e.employee_id FROM employees e WHERE e.employee_code=UPPER(TRIM(u.staff_code))),display_name=NVL(u.display_name,(SELECT e.first_name||' '||e.last_name FROM employees e WHERE e.employee_code=UPPER(TRIM(u.staff_code)))) WHERE u.role IN ('ADMIN','MANAGER','EMPLOYEE') AND u.employee_id IS NULL AND u.staff_code IS NOT NULL;
  UPDATE users SET employee_id=NULL,staff_code=NULL WHERE role='CUSTOMER';

  SELECT COUNT(*) INTO v_invalid FROM users WHERE role IN ('ADMIN','MANAGER','EMPLOYEE') AND (employee_id IS NULL OR staff_code IS NULL);
  IF v_invalid > 0 THEN RAISE_APPLICATION_ERROR(-20601,'Unified staff migration found staff users without employee links.'); END IF;
  SELECT COUNT(*) INTO v_invalid FROM users WHERE role='CUSTOMER' AND (customer_id IS NULL OR employee_id IS NOT NULL OR staff_code IS NOT NULL);
  IF v_invalid > 0 THEN RAISE_APPLICATION_ERROR(-20602,'Unified staff migration found invalid customer principals.'); END IF;

  exec_ignore('ALTER TABLE users ADD CONSTRAINT ck_user_principal CHECK ((role = ''CUSTOMER'' AND customer_id IS NOT NULL AND employee_id IS NULL AND staff_code IS NULL) OR (role IN (''ADMIN'',''MANAGER'',''EMPLOYEE'') AND employee_id IS NOT NULL AND customer_id IS NULL AND staff_code IS NOT NULL))', SYS.ODCINUMBERLIST(-2260,-2275));
  exec_ignore('CREATE UNIQUE INDEX uk_users_username_lower ON users(LOWER(username))', SYS.ODCINUMBERLIST(-955,-1408));
  exec_ignore('CREATE UNIQUE INDEX uk_users_staff_code_lower ON users(LOWER(staff_code))', SYS.ODCINUMBERLIST(-955,-1408));
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Unified staff principal migration complete.');
END;
/

CREATE OR REPLACE TRIGGER trg_validate_user_staff_code
BEFORE INSERT OR UPDATE OF employee_id, staff_code, role ON users
FOR EACH ROW
DECLARE
  v_employee_code employees.employee_code%TYPE;
BEGIN
  :NEW.username := LOWER(TRIM(:NEW.username));
  :NEW.role := UPPER(TRIM(:NEW.role));
  IF :NEW.staff_code IS NOT NULL THEN :NEW.staff_code := UPPER(TRIM(:NEW.staff_code)); END IF;
  IF :NEW.role IN ('ADMIN','MANAGER','EMPLOYEE') THEN
    IF :NEW.employee_id IS NULL OR :NEW.customer_id IS NOT NULL THEN RAISE_APPLICATION_ERROR(-20309,'Staff users must link to an employee and cannot link to a customer.'); END IF;
    SELECT employee_code INTO v_employee_code FROM employees WHERE employee_id=:NEW.employee_id AND status='ACTIVE';
    IF :NEW.staff_code IS NULL OR :NEW.staff_code<>UPPER(TRIM(v_employee_code)) THEN RAISE_APPLICATION_ERROR(-20310,'Staff code must match the linked active employee code.'); END IF;
  ELSIF :NEW.role='CUSTOMER' THEN
    IF :NEW.customer_id IS NULL OR :NEW.employee_id IS NOT NULL OR :NEW.staff_code IS NOT NULL THEN RAISE_APPLICATION_ERROR(-20311,'Customer users must link only to a customer.'); END IF;
  ELSE
    RAISE_APPLICATION_ERROR(-20313,'Unsupported application role.');
  END IF;
EXCEPTION WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20312,'Staff users must link to an existing active employee.');
END;
/

SELECT name,type,line,position,text FROM user_errors ORDER BY name,sequence;
